# Installing pandas and numpy

In [8]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\ak180\appdata\local\programs\python\python312\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.26.0 in c:\users\ak180\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ak180\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ak180\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ak180\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\ak180\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [9]:
%pip install numpy

Requirement already satisfied: numpy in c:\users\ak180\appdata\local\programs\python\python312\lib\site-packages (2.1.1)Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

In [4]:
import numpy as np

Object Creation

In [12]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [1]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

importing oprnpyxl

In [5]:
import openpyxl

reading excel file randomAI

In [6]:
df = pd.read_excel("randomAI.xlsx")
df

     Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6
0           52         93         15         72         61         21
1           83         87         75         75         88         24
2            3         22         53          2         88         30
3           38          2         64         60         21         33
4           76         58         22         89         49         91
..         ...        ...        ...        ...        ...        ...
195         33         68         86         66         10          5
196         74         97         38         13         31         47
197         88         52         56         15         29          8
198          5         29         47         68         76         45
199          2         27         95         36         36         26

[200 rows x 6 columns]

Printing the uper portion

In [7]:
print(df.head)

<bound method NDFrame.head of      Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6
0           52         93         15         72         61         21
1           83         87         75         75         88         24
2            3         22         53          2         88         30
3           38          2         64         60         21         33
4           76         58         22         89         49         91
..         ...        ...        ...        ...        ...        ...
195         33         68         86         66         10          5
196         74         97         38         13         31         47
197         88         52         56         15         29          8
198          5         29         47         68         76         45
199          2         27         95         36         36         26

[200 rows x 6 columns]>

Printing the down portion

In [7]:
print(df.tail)

<bound method NDFrame.tail of      Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6
0           52         93         15         72         61         21
1           83         87         75         75         88         24
2            3         22         53          2         88         30
3           38          2         64         60         21         33
4           76         58         22         89         49         91
..         ...        ...        ...        ...        ...        ...
195         33         68         86         66         10          5
196         74         97         38         13         31         47
197         88         52         56         15         29          8
198          5         29         47         68         76         45
199          2         27         95         36         36         26

[200 rows x 6 columns]>

Printing the index of data

In [8]:
df.index

RangeIndex(start=0, stop=200, step=1)

Printing columns

In [10]:
df.columns

Index(['Feature_1', 'Feature_2', 'Feature_3', 'Feature_4', 'Feature_5',
       'Feature_6'],
      dtype='object')

Used to describe data

In [11]:
df.describe

<bound method NDFrame.describe of      Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6
0           52         93         15         72         61         21
1           83         87         75         75         88         24
2            3         22         53          2         88         30
3           38          2         64         60         21         33
4           76         58         22         89         49         91
..         ...        ...        ...        ...        ...        ...
195         33         68         86         66         10          5
196         74         97         38         13         31         47
197         88         52         56         15         29          8
198          5         29         47         68         76         45
199          2         27         95         36         36         26

[200 rows x 6 columns]>

Displaying only selected Column

In [12]:
df.loc[:,"Feature_1"]

0      52
1      83
2       3
3      38
4      76
       ..
195    33
196    74
197    88
198     5
199     2
Name: Feature_1, Length: 200, dtype: int64

Mean od Data

In [13]:
df.mean

<bound method DataFrame.mean of      Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6
0           52         93         15         72         61         21
1           83         87         75         75         88         24
2            3         22         53          2         88         30
3           38          2         64         60         21         33
4           76         58         22         89         49         91
..         ...        ...        ...        ...        ...        ...
195         33         68         86         66         10          5
196         74         97         38         13         31         47
197         88         52         56         15         29          8
198          5         29         47         68         76         45
199          2         27         95         36         36         26

[200 rows x 6 columns]>

Median of Data

In [14]:
df.median

<bound method DataFrame.median of      Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6
0           52         93         15         72         61         21
1           83         87         75         75         88         24
2            3         22         53          2         88         30
3           38          2         64         60         21         33
4           76         58         22         89         49         91
..         ...        ...        ...        ...        ...        ...
195         33         68         86         66         10          5
196         74         97         38         13         31         47
197         88         52         56         15         29          8
198          5         29         47         68         76         45
199          2         27         95         36         36         26

[200 rows x 6 columns]>

Mode of Data

In [15]:
df.mode

<bound method DataFrame.mode of      Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6
0           52         93         15         72         61         21
1           83         87         75         75         88         24
2            3         22         53          2         88         30
3           38          2         64         60         21         33
4           76         58         22         89         49         91
..         ...        ...        ...        ...        ...        ...
195         33         68         86         66         10          5
196         74         97         38         13         31         47
197         88         52         56         15         29          8
198          5         29         47         68         76         45
199          2         27         95         36         36         26

[200 rows x 6 columns]>

Alinging Data

In [16]:
df.align

<bound method NDFrame.align of      Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6
0           52         93         15         72         61         21
1           83         87         75         75         88         24
2            3         22         53          2         88         30
3           38          2         64         60         21         33
4           76         58         22         89         49         91
..         ...        ...        ...        ...        ...        ...
195         33         68         86         66         10          5
196         74         97         38         13         31         47
197         88         52         56         15         29          8
198          5         29         47         68         76         45
199          2         27         95         36         36         26

[200 rows x 6 columns]>

Transpose of data

In [17]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
Feature_1,52,83,3,38,76,59,62,64,39,9,...,97,53,67,15,29,33,74,88,5,2
Feature_2,93,87,22,2,58,42,62,3,18,90,...,25,51,7,29,38,68,97,52,29,27
Feature_3,15,75,53,64,22,92,47,51,4,53,...,17,39,51,33,57,86,38,56,47,95
Feature_4,72,75,2,60,89,60,62,7,89,2,...,97,51,72,94,97,66,13,15,68,36
Feature_5,61,88,88,21,49,80,51,21,60,84,...,66,70,42,27,27,10,31,29,76,36
Feature_6,21,24,30,33,91,15,55,73,14,92,...,78,6,64,36,55,5,47,8,45,26

Slicing the Data

In [8]:
df[0:6]

   Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6
0         52         93         15         72         61         21
1         83         87         75         75         88         24
2          3         22         53          2         88         30
3         38          2         64         60         21         33
4         76         58         22         89         49         91
5         59         42         92         60         80         15

Displaying a specific DataSet

In [9]:
df.loc[150]

Feature_1     4
Feature_2    56
Feature_3    25
Feature_4    67
Feature_5    96
Feature_6    67
Name: 150, dtype: int64

Displaying a specific DataSet with specific Columns

In [10]:
df.loc[0:10, ["Feature_1", "Feature_5"]]

    Feature_1  Feature_5
0          52         61
1          83         88
2           3         88
3          38         21
4          76         49
5          59         80
6          62         51
7          64         21
8          39         60
9           9         84
10         60         47

Droping any rows that have missing data:

In [11]:
df.dropna(how="any")

     Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6
0           52         93         15         72         61         21
1           83         87         75         75         88         24
2            3         22         53          2         88         30
3           38          2         64         60         21         33
4           76         58         22         89         49         91
..         ...        ...        ...        ...        ...        ...
195         33         68         86         66         10          5
196         74         97         38         13         31         47
197         88         52         56         15         29          8
198          5         29         47         68         76         45
199          2         27         95         36         36         26

[200 rows x 6 columns]

Operations on Data

Stats

Mean Value of column

In [13]:
df['Feature_3'].mean()

np.float64(45.125)

In [14]:
df.value_counts("Feature_3")

Feature_3
8     7
1     6
19    5
62    5
52    5
     ..
84    1
87    1
79    1
93    1
95    1
Name: count, Length: 87, dtype: int64