installinhg pandas

In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\ak180\appdata\local\programs\python\python312\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.26.0 in c:\users\ak180\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ak180\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ak180\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ak180\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\ak180\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

installing numpy

In [2]:
%pip install numpy

Requirement already satisfied: numpy in c:\users\ak180\appdata\local\programs\python\python312\lib\site-packages (2.1.1)Note: you may need to restart the kernel to use updated packages.

importing pandas

In [3]:
import pandas as pd

importing numpy

In [4]:
import numpy as np

installing openpyxl

In [5]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\ak180\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\ak180\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

Reading excel file

In [6]:
data = pd.read_excel("random_data.xlsx")
data

,Column_1,Column_2,Column_3,Column_4,Column_5,Column_6,Column_7,Column_8
0,0.789243,0.702892,0.731086,0.748492,0.265637,0.400561,0.907841,0.974681
1,0.631811,0.959799,0.832163,0.602203,0.170158,0.773807,0.916541,0.105137
2,0.917600,0.523119,0.350832,0.690714,0.214096,0.947411,0.824273,0.761261
3,0.101639,0.300388,0.687362,0.482220,0.865535,0.679808,0.243005,0.778744
4,0.356569,0.136909,0.218621,0.665562,0.184865,0.805371,0.714744,0.914403
...,...,...,...,...,...,...,...,...
195,0.493435,0.049773,0.196317,0.751555,0.698836,0.679639,0.722044,0.666422
196,0.566661,0.015056,0.364775,0.081686,0.290895,0.905771,0.390466,0.659182
197,0.125489,0.541543,0.243888,0.004001,0.732435,0.999055,0.550730,0.627574
198,0.620958,0.995015,0.777763,0.926860,0.695247,0.255455,0.452709,0.157216
199,0.657727,0.102253,0.846828,0.222946,0.890899,0.133791,0.922453,0.485249

printing upper part

In [7]:
print(data.head)

<bound method NDFrame.head of      Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0    0.789243  0.702892  0.731086  0.748492  0.265637  0.400561  0.907841
1    0.631811  0.959799  0.832163  0.602203  0.170158  0.773807  0.916541
2    0.917600  0.523119  0.350832  0.690714  0.214096  0.947411  0.824273
3    0.101639  0.300388  0.687362  0.482220  0.865535  0.679808  0.243005
4    0.356569  0.136909  0.218621  0.665562  0.184865  0.805371  0.714744
..        ...       ...       ...       ...       ...       ...       ...
195  0.493435  0.049773  0.196317  0.751555  0.698836  0.679639  0.722044
196  0.566661  0.015056  0.364775  0.081686  0.290895  0.905771  0.390466
197  0.125489  0.541543  0.243888  0.004001  0.732435  0.999055  0.550730
198  0.620958  0.995015  0.777763  0.926860  0.695247  0.255455  0.452709
199  0.657727  0.102253  0.846828  0.222946  0.890899  0.133791  0.922453

     Column_8
0    0.974681
1    0.105137
2    0.761261
3    0.778744
4    0.914403
..        ...
195  0.666422
196  0.659182
197  0.627574
198  0.157216
199  0.485249

[200 rows x 8 columns]>

Printing lower part

In [8]:
print(data.tail)

<bound method NDFrame.tail of      Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0    0.789243  0.702892  0.731086  0.748492  0.265637  0.400561  0.907841
1    0.631811  0.959799  0.832163  0.602203  0.170158  0.773807  0.916541
2    0.917600  0.523119  0.350832  0.690714  0.214096  0.947411  0.824273
3    0.101639  0.300388  0.687362  0.482220  0.865535  0.679808  0.243005
4    0.356569  0.136909  0.218621  0.665562  0.184865  0.805371  0.714744
..        ...       ...       ...       ...       ...       ...       ...
195  0.493435  0.049773  0.196317  0.751555  0.698836  0.679639  0.722044
196  0.566661  0.015056  0.364775  0.081686  0.290895  0.905771  0.390466
197  0.125489  0.541543  0.243888  0.004001  0.732435  0.999055  0.550730
198  0.620958  0.995015  0.777763  0.926860  0.695247  0.255455  0.452709
199  0.657727  0.102253  0.846828  0.222946  0.890899  0.133791  0.922453

     Column_8
0    0.974681
1    0.105137
2    0.761261
3    0.778744
4    0.914403
..        ...
195  0.666422
196  0.659182
197  0.627574
198  0.157216
199  0.485249

[200 rows x 8 columns]>

prnting index

In [9]:
data.index

RangeIndex(start=0, stop=200, step=1)

printing data

In [10]:
data.columns

Index(['Column_1', 'Column_2', 'Column_3', 'Column_4', 'Column_5', 'Column_6',
       'Column_7', 'Column_8'],
      dtype='object')

Describing the data

In [11]:
data.describe

<bound method NDFrame.describe of      Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0    0.789243  0.702892  0.731086  0.748492  0.265637  0.400561  0.907841
1    0.631811  0.959799  0.832163  0.602203  0.170158  0.773807  0.916541
2    0.917600  0.523119  0.350832  0.690714  0.214096  0.947411  0.824273
3    0.101639  0.300388  0.687362  0.482220  0.865535  0.679808  0.243005
4    0.356569  0.136909  0.218621  0.665562  0.184865  0.805371  0.714744
..        ...       ...       ...       ...       ...       ...       ...
195  0.493435  0.049773  0.196317  0.751555  0.698836  0.679639  0.722044
196  0.566661  0.015056  0.364775  0.081686  0.290895  0.905771  0.390466
197  0.125489  0.541543  0.243888  0.004001  0.732435  0.999055  0.550730
198  0.620958  0.995015  0.777763  0.926860  0.695247  0.255455  0.452709
199  0.657727  0.102253  0.846828  0.222946  0.890899  0.133791  0.922453

     Column_8
0    0.974681
1    0.105137
2    0.761261
3    0.778744
4    0.914403
..        ...
195  0.666422
196  0.659182
197  0.627574
198  0.157216
199  0.485249

[200 rows x 8 columns]>

displying slected column

In [12]:
data.loc[:,"Column_4"]

0      0.748492
1      0.602203
2      0.690714
3      0.482220
4      0.665562
         ...
195    0.751555
196    0.081686
197    0.004001
198    0.926860
199    0.222946
Name: Column_4, Length: 200, dtype: float64

Mean of data

In [13]:
data.mean

<bound method DataFrame.mean of      Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0    0.789243  0.702892  0.731086  0.748492  0.265637  0.400561  0.907841
1    0.631811  0.959799  0.832163  0.602203  0.170158  0.773807  0.916541
2    0.917600  0.523119  0.350832  0.690714  0.214096  0.947411  0.824273
3    0.101639  0.300388  0.687362  0.482220  0.865535  0.679808  0.243005
4    0.356569  0.136909  0.218621  0.665562  0.184865  0.805371  0.714744
..        ...       ...       ...       ...       ...       ...       ...
195  0.493435  0.049773  0.196317  0.751555  0.698836  0.679639  0.722044
196  0.566661  0.015056  0.364775  0.081686  0.290895  0.905771  0.390466
197  0.125489  0.541543  0.243888  0.004001  0.732435  0.999055  0.550730
198  0.620958  0.995015  0.777763  0.926860  0.695247  0.255455  0.452709
199  0.657727  0.102253  0.846828  0.222946  0.890899  0.133791  0.922453

     Column_8
0    0.974681
1    0.105137
2    0.761261
3    0.778744
4    0.914403
..        ...
195  0.666422
196  0.659182
197  0.627574
198  0.157216
199  0.485249

[200 rows x 8 columns]>

Median of data

In [14]:
data.median

<bound method DataFrame.median of      Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0    0.789243  0.702892  0.731086  0.748492  0.265637  0.400561  0.907841
1    0.631811  0.959799  0.832163  0.602203  0.170158  0.773807  0.916541
2    0.917600  0.523119  0.350832  0.690714  0.214096  0.947411  0.824273
3    0.101639  0.300388  0.687362  0.482220  0.865535  0.679808  0.243005
4    0.356569  0.136909  0.218621  0.665562  0.184865  0.805371  0.714744
..        ...       ...       ...       ...       ...       ...       ...
195  0.493435  0.049773  0.196317  0.751555  0.698836  0.679639  0.722044
196  0.566661  0.015056  0.364775  0.081686  0.290895  0.905771  0.390466
197  0.125489  0.541543  0.243888  0.004001  0.732435  0.999055  0.550730
198  0.620958  0.995015  0.777763  0.926860  0.695247  0.255455  0.452709
199  0.657727  0.102253  0.846828  0.222946  0.890899  0.133791  0.922453

     Column_8
0    0.974681
1    0.105137
2    0.761261
3    0.778744
4    0.914403
..        ...
195  0.666422
196  0.659182
197  0.627574
198  0.157216
199  0.485249

[200 rows x 8 columns]>

Mode of data

In [15]:
data.mode

<bound method DataFrame.mode of      Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0    0.789243  0.702892  0.731086  0.748492  0.265637  0.400561  0.907841
1    0.631811  0.959799  0.832163  0.602203  0.170158  0.773807  0.916541
2    0.917600  0.523119  0.350832  0.690714  0.214096  0.947411  0.824273
3    0.101639  0.300388  0.687362  0.482220  0.865535  0.679808  0.243005
4    0.356569  0.136909  0.218621  0.665562  0.184865  0.805371  0.714744
..        ...       ...       ...       ...       ...       ...       ...
195  0.493435  0.049773  0.196317  0.751555  0.698836  0.679639  0.722044
196  0.566661  0.015056  0.364775  0.081686  0.290895  0.905771  0.390466
197  0.125489  0.541543  0.243888  0.004001  0.732435  0.999055  0.550730
198  0.620958  0.995015  0.777763  0.926860  0.695247  0.255455  0.452709
199  0.657727  0.102253  0.846828  0.222946  0.890899  0.133791  0.922453

     Column_8
0    0.974681
1    0.105137
2    0.761261
3    0.778744
4    0.914403
..        ...
195  0.666422
196  0.659182
197  0.627574
198  0.157216
199  0.485249

[200 rows x 8 columns]>

alling data

In [16]:
data.align

<bound method NDFrame.align of      Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0    0.789243  0.702892  0.731086  0.748492  0.265637  0.400561  0.907841
1    0.631811  0.959799  0.832163  0.602203  0.170158  0.773807  0.916541
2    0.917600  0.523119  0.350832  0.690714  0.214096  0.947411  0.824273
3    0.101639  0.300388  0.687362  0.482220  0.865535  0.679808  0.243005
4    0.356569  0.136909  0.218621  0.665562  0.184865  0.805371  0.714744
..        ...       ...       ...       ...       ...       ...       ...
195  0.493435  0.049773  0.196317  0.751555  0.698836  0.679639  0.722044
196  0.566661  0.015056  0.364775  0.081686  0.290895  0.905771  0.390466
197  0.125489  0.541543  0.243888  0.004001  0.732435  0.999055  0.550730
198  0.620958  0.995015  0.777763  0.926860  0.695247  0.255455  0.452709
199  0.657727  0.102253  0.846828  0.222946  0.890899  0.133791  0.922453

     Column_8
0    0.974681
1    0.105137
2    0.761261
3    0.778744
4    0.914403
..        ...
195  0.666422
196  0.659182
197  0.627574
198  0.157216
199  0.485249

[200 rows x 8 columns]>

Transpose of data

In [17]:
data.T

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
Column_1,0.789243,0.631811,0.917600,0.101639,0.356569,0.990304,0.152516,0.516147,0.947504,0.752731,...,0.261999,0.116371,0.869325,0.129093,0.672618,0.493435,0.566661,0.125489,0.620958,0.657727
Column_2,0.702892,0.959799,0.523119,0.300388,0.136909,0.663817,0.820469,0.913999,0.087237,0.418997,...,0.661535,0.500579,0.708769,0.294579,0.129959,0.049773,0.015056,0.541543,0.995015,0.102253
Column_3,0.731086,0.832163,0.350832,0.687362,0.218621,0.752256,0.400345,0.989148,0.169047,0.312011,...,0.398643,0.438205,0.844289,0.565677,0.658498,0.196317,0.364775,0.243888,0.777763,0.846828
Column_4,0.748492,0.602203,0.690714,0.482220,0.665562,0.749042,0.191263,0.818672,0.713559,0.322087,...,0.198466,0.610214,0.533938,0.074183,0.423448,0.751555,0.081686,0.004001,0.926860,0.222946
Column_5,0.265637,0.170158,0.214096,0.865535,0.184865,0.449711,0.790064,0.775071,0.659814,0.815641,...,0.941675,0.776424,0.835188,0.823056,0.514436,0.698836,0.290895,0.732435,0.695247,0.890899
Column_6,0.400561,0.773807,0.947411,0.679808,0.805371,0.415399,0.706992,0.144489,0.426965,0.118436,...,0.471789,0.481216,0.185241,0.788360,0.982477,0.679639,0.905771,0.999055,0.255455,0.133791
Column_7,0.907841,0.916541,0.824273,0.243005,0.714744,0.278210,0.649334,0.090497,0.447316,0.189855,...,0.080141,0.989879,0.817774,0.306040,0.949252,0.722044,0.390466,0.550730,0.452709,0.922453
Column_8,0.974681,0.105137,0.761261,0.778744,0.914403,0.766936,0.578040,0.847404,0.866656,0.863199,...,0.030593,0.103114,0.371532,0.101514,0.504169,0.666422,0.659182,0.627574,0.157216,0.485249

Slicing the data

In [18]:
data[0:8]

,Column_1,Column_2,Column_3,Column_4,Column_5,Column_6,Column_7,Column_8
0,0.789243,0.702892,0.731086,0.748492,0.265637,0.400561,0.907841,0.974681
1,0.631811,0.959799,0.832163,0.602203,0.170158,0.773807,0.916541,0.105137
2,0.917600,0.523119,0.350832,0.690714,0.214096,0.947411,0.824273,0.761261
3,0.101639,0.300388,0.687362,0.482220,0.865535,0.679808,0.243005,0.778744
4,0.356569,0.136909,0.218621,0.665562,0.184865,0.805371,0.714744,0.914403
5,0.990304,0.663817,0.752256,0.749042,0.449711,0.415399,0.278210,0.766936
6,0.152516,0.820469,0.400345,0.191263,0.790064,0.706992,0.649334,0.578040
7,0.516147,0.913999,0.989148,0.818672,0.775071,0.144489,0.090497,0.847404

displying a specific dataset

In [19]:
data.loc[150]

Column_1    0.767852
Column_2    0.183165
Column_3    0.592833
Column_4    0.484563
Column_5    0.723736
Column_6    0.743687
Column_7    0.484838
Column_8    0.040684
Name: 150, dtype: float64

Displaying a specific DataSet with specific Columns

In [21]:
data.loc[0:10, ["Column_1", "Column_5"]]

    Column_1  Column_5
0   0.789243  0.265637
1   0.631811  0.170158
2   0.917600  0.214096
3   0.101639  0.865535
4   0.356569  0.184865
5   0.990304  0.449711
6   0.152516  0.790064
7   0.516147  0.775071
8   0.947504  0.659814
9   0.752731  0.815641
10  0.942707  0.089712

disply row with missing data

In [22]:
data.dropna(how="any")

,Column_1,Column_2,Column_3,Column_4,Column_5,Column_6,Column_7,Column_8
0,0.789243,0.702892,0.731086,0.748492,0.265637,0.400561,0.907841,0.974681
1,0.631811,0.959799,0.832163,0.602203,0.170158,0.773807,0.916541,0.105137
2,0.917600,0.523119,0.350832,0.690714,0.214096,0.947411,0.824273,0.761261
3,0.101639,0.300388,0.687362,0.482220,0.865535,0.679808,0.243005,0.778744
4,0.356569,0.136909,0.218621,0.665562,0.184865,0.805371,0.714744,0.914403
...,...,...,...,...,...,...,...,...
195,0.493435,0.049773,0.196317,0.751555,0.698836,0.679639,0.722044,0.666422
196,0.566661,0.015056,0.364775,0.081686,0.290895,0.905771,0.390466,0.659182
197,0.125489,0.541543,0.243888,0.004001,0.732435,0.999055,0.550730,0.627574
198,0.620958,0.995015,0.777763,0.926860,0.695247,0.255455,0.452709,0.157216
199,0.657727,0.102253,0.846828,0.222946,0.890899,0.133791,0.922453,0.485249

Operations on Data

Stats

Mean Value of column

In [24]:
data['Column_3'].mean()

np.float64(0.5361984679727745)

In [25]:
data.value_counts("Column_3")

Column_3
0.011265    1
0.013042    1
0.039954    1
0.056920    1
0.057312    1
           ..
0.972609    1
0.981301    1
0.982300    1
0.987000    1
0.989148    1
Name: count, Length: 200, dtype: int64