In [4]:
### Pandas Practice
# import pandas library

In [6]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.2.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.23.2 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd

In [8]:
a = pd.read_excel("business.xlsx")
a

,Business Name,Owner Name,Location,Phone Number,Email,Established Year,Revenue ($),Employees
0,Business_1,Owner_1,City_2,3000000001,business_1@email.com,2001,51000,11
1,Business_2,Owner_2,City_3,3000000002,business_2@email.com,2002,52000,12
2,Business_3,Owner_3,City_4,3000000003,business_3@email.com,2003,53000,13
3,Business_4,Owner_4,City_5,3000000004,business_4@email.com,2004,54000,14
4,Business_5,Owner_5,City_6,3000000005,business_5@email.com,2005,55000,15
...,...,...,...,...,...,...,...,...
195,Business_196,Owner_196,City_7,3000000196,business_196@email.com,2016,246000,11
196,Business_197,Owner_197,City_8,3000000197,business_197@email.com,2017,247000,12
197,Business_198,Owner_198,City_9,3000000198,business_198@email.com,2018,248000,13
198,Business_199,Owner_199,City_10,3000000199,business_199@email.com,2019,249000,14
199,Business_200,Owner_200,City_1,3000000200,business_200@email.com,2000,250000,15

# Displays first five rows of dataset

In [9]:
a.head()

,Business Name,Owner Name,Location,Phone Number,Email,Established Year,Revenue ($),Employees
0,Business_1,Owner_1,City_2,3000000001,business_1@email.com,2001,51000,11
1,Business_2,Owner_2,City_3,3000000002,business_2@email.com,2002,52000,12
2,Business_3,Owner_3,City_4,3000000003,business_3@email.com,2003,53000,13
3,Business_4,Owner_4,City_5,3000000004,business_4@email.com,2004,54000,14
4,Business_5,Owner_5,City_6,3000000005,business_5@email.com,2005,55000,15

## Displays last five rows of dataset

In [10]:
a.tail()

,Business Name,Owner Name,Location,Phone Number,Email,Established Year,Revenue ($),Employees
195,Business_196,Owner_196,City_7,3000000196,business_196@email.com,2016,246000,11
196,Business_197,Owner_197,City_8,3000000197,business_197@email.com,2017,247000,12
197,Business_198,Owner_198,City_9,3000000198,business_198@email.com,2018,248000,13
198,Business_199,Owner_199,City_10,3000000199,business_199@email.com,2019,249000,14
199,Business_200,Owner_200,City_1,3000000200,business_200@email.com,2000,250000,15

## index and Columns

In [11]:
a.index

RangeIndex(start=0, stop=200, step=1)

In [12]:
a.columns

Index(['Business Name', 'Owner Name', 'Location', 'Phone Number', 'Email',
       'Established Year', 'Revenue ($)', 'Employees'],
      dtype='object')

## describe() shows a quick statistic summary of your data:

In [13]:
a.describe

<bound method NDFrame.describe of     Business Name Owner Name Location  Phone Number                   Email  \
0      Business_1    Owner_1   City_2    3000000001    business_1@email.com
1      Business_2    Owner_2   City_3    3000000002    business_2@email.com
2      Business_3    Owner_3   City_4    3000000003    business_3@email.com
3      Business_4    Owner_4   City_5    3000000004    business_4@email.com
4      Business_5    Owner_5   City_6    3000000005    business_5@email.com
..            ...        ...      ...           ...                     ...
195  Business_196  Owner_196   City_7    3000000196  business_196@email.com
196  Business_197  Owner_197   City_8    3000000197  business_197@email.com
197  Business_198  Owner_198   City_9    3000000198  business_198@email.com
198  Business_199  Owner_199  City_10    3000000199  business_199@email.com
199  Business_200  Owner_200   City_1    3000000200  business_200@email.com

     Established Year  Revenue ($)  Employees
0                2001        51000         11
1                2002        52000         12
2                2003        53000         13
3                2004        54000         14
4                2005        55000         15
..                ...          ...        ...
195              2016       246000         11
196              2017       247000         12
197              2018       248000         13
198              2019       249000         14
199              2000       250000         15

[200 rows x 8 columns]>

## Transpose

In [14]:
a.T

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
Business Name,Business_1,Business_2,Business_3,Business_4,Business_5,Business_6,Business_7,Business_8,Business_9,Business_10,...,Business_191,Business_192,Business_193,Business_194,Business_195,Business_196,Business_197,Business_198,Business_199,Business_200
Owner Name,Owner_1,Owner_2,Owner_3,Owner_4,Owner_5,Owner_6,Owner_7,Owner_8,Owner_9,Owner_10,...,Owner_191,Owner_192,Owner_193,Owner_194,Owner_195,Owner_196,Owner_197,Owner_198,Owner_199,Owner_200
Location,City_2,City_3,City_4,City_5,City_6,City_7,City_8,City_9,City_10,City_1,...,City_2,City_3,City_4,City_5,City_6,City_7,City_8,City_9,City_10,City_1
Phone Number,3000000001,3000000002,3000000003,3000000004,3000000005,3000000006,3000000007,3000000008,3000000009,3000000010,...,3000000191,3000000192,3000000193,3000000194,3000000195,3000000196,3000000197,3000000198,3000000199,3000000200
Email,business_1@email.com,business_2@email.com,business_3@email.com,business_4@email.com,business_5@email.com,business_6@email.com,business_7@email.com,business_8@email.com,business_9@email.com,business_10@email.com,...,business_191@email.com,business_192@email.com,business_193@email.com,business_194@email.com,business_195@email.com,business_196@email.com,business_197@email.com,business_198@email.com,business_199@email.com,business_200@email.com
Established Year,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2000
Revenue ($),51000,52000,53000,54000,55000,56000,57000,58000,59000,60000,...,241000,242000,243000,244000,245000,246000,247000,248000,249000,250000
Employees,11,12,13,14,15,16,17,18,19,20,...,21,22,23,24,10,11,12,13,14,15

In [16]:
a.sort_values(by="Email")

,Business Name,Owner Name,Location,Phone Number,Email,Established Year,Revenue ($),Employees
99,Business_100,Owner_100,City_1,3000000100,business_100@email.com,2000,150000,20
100,Business_101,Owner_101,City_2,3000000101,business_101@email.com,2001,151000,21
101,Business_102,Owner_102,City_3,3000000102,business_102@email.com,2002,152000,22
102,Business_103,Owner_103,City_4,3000000103,business_103@email.com,2003,153000,23
103,Business_104,Owner_104,City_5,3000000104,business_104@email.com,2004,154000,24
...,...,...,...,...,...,...,...,...
95,Business_96,Owner_96,City_7,3000000096,business_96@email.com,2016,146000,16
96,Business_97,Owner_97,City_8,3000000097,business_97@email.com,2017,147000,17
97,Business_98,Owner_98,City_9,3000000098,business_98@email.com,2018,148000,18
98,Business_99,Owner_99,City_10,3000000099,business_99@email.com,2019,149000,19
8,Business_9,Owner_9,City_10,3000000009,business_9@email.com,2009,59000,19

In [18]:
a["Employees"]

0      11
1      12
2      13
3      14
4      15
       ..
195    11
196    12
197    13
198    14
199    15
Name: Employees, Length: 200, dtype: int64

In [19]:
a[10:20]

,Business Name,Owner Name,Location,Phone Number,Email,Established Year,Revenue ($),Employees
10,Business_11,Owner_11,City_2,3000000011,business_11@email.com,2011,61000,21
11,Business_12,Owner_12,City_3,3000000012,business_12@email.com,2012,62000,22
12,Business_13,Owner_13,City_4,3000000013,business_13@email.com,2013,63000,23
13,Business_14,Owner_14,City_5,3000000014,business_14@email.com,2014,64000,24
14,Business_15,Owner_15,City_6,3000000015,business_15@email.com,2015,65000,10
15,Business_16,Owner_16,City_7,3000000016,business_16@email.com,2016,66000,11
16,Business_17,Owner_17,City_8,3000000017,business_17@email.com,2017,67000,12
17,Business_18,Owner_18,City_9,3000000018,business_18@email.com,2018,68000,13
18,Business_19,Owner_19,City_10,3000000019,business_19@email.com,2019,69000,14
19,Business_20,Owner_20,City_1,3000000020,business_20@email.com,2000,70000,15

In [21]:
a.loc[50]

Business Name                 Business_51
Owner Name                       Owner_51
Location                           City_2
Phone Number                   3000000051
Email               business_51@email.com
Established Year                     2011
Revenue ($)                        101000
Employees                              16
Name: 50, dtype: object

In [25]:
a.loc[0:10,["Employees", "Location"]]

    Employees Location
0          11   City_2
1          12   City_3
2          13   City_4
3          14   City_5
4          15   City_6
5          16   City_7
6          17   City_8
7          18   City_9
8          19  City_10
9          20   City_1
10         21   City_2

In [26]:
a.iloc[1]

Business Name                 Business_2
Owner Name                       Owner_2
Location                          City_3
Phone Number                  3000000002
Email               business_2@email.com
Established Year                    2002
Revenue ($)                        52000
Employees                             12
Name: 1, dtype: object

In [32]:
a.dropna(how="any")

,Business Name,Owner Name,Location,Phone Number,Email,Established Year,Revenue ($),Employees
0,Business_1,Owner_1,City_2,3000000001,business_1@email.com,2001,51000,11
1,Business_2,Owner_2,City_3,3000000002,business_2@email.com,2002,52000,12
2,Business_3,Owner_3,City_4,3000000003,business_3@email.com,2003,53000,13
3,Business_4,Owner_4,City_5,3000000004,business_4@email.com,2004,54000,14
4,Business_5,Owner_5,City_6,3000000005,business_5@email.com,2005,55000,15
...,...,...,...,...,...,...,...,...
195,Business_196,Owner_196,City_7,3000000196,business_196@email.com,2016,246000,11
196,Business_197,Owner_197,City_8,3000000197,business_197@email.com,2017,247000,12
197,Business_198,Owner_198,City_9,3000000198,business_198@email.com,2018,248000,13
198,Business_199,Owner_199,City_10,3000000199,business_199@email.com,2019,249000,14
199,Business_200,Owner_200,City_1,3000000200,business_200@email.com,2000,250000,15

In [33]:
a.fillna(value=0000)

,Business Name,Owner Name,Location,Phone Number,Email,Established Year,Revenue ($),Employees
0,Business_1,Owner_1,City_2,3000000001,business_1@email.com,2001,51000,11
1,Business_2,Owner_2,City_3,3000000002,business_2@email.com,2002,52000,12
2,Business_3,Owner_3,City_4,3000000003,business_3@email.com,2003,53000,13
3,Business_4,Owner_4,City_5,3000000004,business_4@email.com,2004,54000,14
4,Business_5,Owner_5,City_6,3000000005,business_5@email.com,2005,55000,15
...,...,...,...,...,...,...,...,...
195,Business_196,Owner_196,City_7,3000000196,business_196@email.com,2016,246000,11
196,Business_197,Owner_197,City_8,3000000197,business_197@email.com,2017,247000,12
197,Business_198,Owner_198,City_9,3000000198,business_198@email.com,2018,248000,13
198,Business_199,Owner_199,City_10,3000000199,business_199@email.com,2019,249000,14
199,Business_200,Owner_200,City_1,3000000200,business_200@email.com,2000,250000,15

In [36]:
a['Revenue ($)'].mean()

np.float64(150500.0)

In [35]:
a.value_counts("Revenue ($)")

Revenue ($)
51000     1
52000     1
53000     1
54000     1
55000     1
         ..
246000    1
247000    1
248000    1
249000    1
250000    1
Name: count, Length: 200, dtype: int64

In [37]:
a.mean

<bound method DataFrame.mean of     Business Name Owner Name Location  Phone Number                   Email  \
0      Business_1    Owner_1   City_2    3000000001    business_1@email.com
1      Business_2    Owner_2   City_3    3000000002    business_2@email.com
2      Business_3    Owner_3   City_4    3000000003    business_3@email.com
3      Business_4    Owner_4   City_5    3000000004    business_4@email.com
4      Business_5    Owner_5   City_6    3000000005    business_5@email.com
..            ...        ...      ...           ...                     ...
195  Business_196  Owner_196   City_7    3000000196  business_196@email.com
196  Business_197  Owner_197   City_8    3000000197  business_197@email.com
197  Business_198  Owner_198   City_9    3000000198  business_198@email.com
198  Business_199  Owner_199  City_10    3000000199  business_199@email.com
199  Business_200  Owner_200   City_1    3000000200  business_200@email.com

     Established Year  Revenue ($)  Employees
0                2001        51000         11
1                2002        52000         12
2                2003        53000         13
3                2004        54000         14
4                2005        55000         15
..                ...          ...        ...
195              2016       246000         11
196              2017       247000         12
197              2018       248000         13
198              2019       249000         14
199              2000       250000         15

[200 rows x 8 columns]>

In [38]:
a.mode

<bound method DataFrame.mode of     Business Name Owner Name Location  Phone Number                   Email  \
0      Business_1    Owner_1   City_2    3000000001    business_1@email.com
1      Business_2    Owner_2   City_3    3000000002    business_2@email.com
2      Business_3    Owner_3   City_4    3000000003    business_3@email.com
3      Business_4    Owner_4   City_5    3000000004    business_4@email.com
4      Business_5    Owner_5   City_6    3000000005    business_5@email.com
..            ...        ...      ...           ...                     ...
195  Business_196  Owner_196   City_7    3000000196  business_196@email.com
196  Business_197  Owner_197   City_8    3000000197  business_197@email.com
197  Business_198  Owner_198   City_9    3000000198  business_198@email.com
198  Business_199  Owner_199  City_10    3000000199  business_199@email.com
199  Business_200  Owner_200   City_1    3000000200  business_200@email.com

     Established Year  Revenue ($)  Employees
0                2001        51000         11
1                2002        52000         12
2                2003        53000         13
3                2004        54000         14
4                2005        55000         15
..                ...          ...        ...
195              2016       246000         11
196              2017       247000         12
197              2018       248000         13
198              2019       249000         14
199              2000       250000         15

[200 rows x 8 columns]>

In [39]:
a.mode

<bound method DataFrame.mode of     Business Name Owner Name Location  Phone Number                   Email  \
0      Business_1    Owner_1   City_2    3000000001    business_1@email.com
1      Business_2    Owner_2   City_3    3000000002    business_2@email.com
2      Business_3    Owner_3   City_4    3000000003    business_3@email.com
3      Business_4    Owner_4   City_5    3000000004    business_4@email.com
4      Business_5    Owner_5   City_6    3000000005    business_5@email.com
..            ...        ...      ...           ...                     ...
195  Business_196  Owner_196   City_7    3000000196  business_196@email.com
196  Business_197  Owner_197   City_8    3000000197  business_197@email.com
197  Business_198  Owner_198   City_9    3000000198  business_198@email.com
198  Business_199  Owner_199  City_10    3000000199  business_199@email.com
199  Business_200  Owner_200   City_1    3000000200  business_200@email.com

     Established Year  Revenue ($)  Employees
0                2001        51000         11
1                2002        52000         12
2                2003        53000         13
3                2004        54000         14
4                2005        55000         15
..                ...          ...        ...
195              2016       246000         11
196              2017       247000         12
197              2018       248000         13
198              2019       249000         14
199              2000       250000         15

[200 rows x 8 columns]>