**Title: Excel Dataset 'Countries'**

**Submitted by: Ayesha**

**Importing libraries pandas and numpy**

In [5]:
import pandas as pd
import numpy as np

**Read Excel Dataset "Countries.xlsx"**

In [6]:
df=pd.read_excel("Countries.xlsx")

In [3]:
df

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
0,1,0.833924,0.468438,0.095948,0.904593,0.233213,0.096233,0.575247,0.957163,0.275796
1,2,0.202625,0.104224,0.866294,0.151645,0.411856,0.138506,0.279925,0.935101,0.596370
2,3,0.296203,0.936568,0.686544,0.645033,0.862706,0.364900,0.890937,0.387882,0.845204
3,4,0.163554,0.535208,0.866781,0.240554,0.113160,0.574719,0.216449,0.839201,0.777353
4,5,0.439157,0.730283,0.899978,0.632945,0.067405,0.306290,0.577608,0.212130,0.696360
...,...,...,...,...,...,...,...,...,...,...
206,207,0.052870,0.307746,0.432467,0.844604,0.741771,0.866744,0.030094,0.652044,0.421857
207,208,0.764549,0.038046,0.761691,0.278519,0.143301,0.540240,0.807247,0.418377,0.296205
208,209,0.514533,0.651745,0.414647,0.493129,0.705009,0.660811,0.269408,0.745009,0.357690
209,210,0.526972,0.936736,0.760946,0.595550,0.512512,0.266746,0.249187,0.447963,0.242949
210,211,0.719486,0.137211,0.700355,0.156539,0.646584,0.808359,0.899380,0.477262,0.619177

**Using all Pandas' functions**

**Data type function**

In [4]:
df.dtypes

Countries       int64
Pakistan      float64
England       float64
France        float64
Ireland       float64
Bangladesh    float64
India         float64
China         float64
Malaysia      float64
Japan         float64
dtype: object

**Creating Series of data**

In [7]:
s = pd.Series([df])

In [8]:
s

0         Countries  Pakistan   England    France  ...
dtype: object

**Date Function**

In [11]:
dates = pd.date_range("20240922", periods=6)

dates

DatetimeIndex(['2024-09-22', '2024-09-23', '2024-09-24', '2024-09-25',
               '2024-09-26', '2024-09-27'],
              dtype='datetime64[ns]', freq='D')

**Viewing Data**

**head(), tail(), index, columns functions**

In [5]:
df.head()

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
0,1,0.833924,0.468438,0.095948,0.904593,0.233213,0.096233,0.575247,0.957163,0.275796
1,2,0.202625,0.104224,0.866294,0.151645,0.411856,0.138506,0.279925,0.935101,0.596370
2,3,0.296203,0.936568,0.686544,0.645033,0.862706,0.364900,0.890937,0.387882,0.845204
3,4,0.163554,0.535208,0.866781,0.240554,0.113160,0.574719,0.216449,0.839201,0.777353
4,5,0.439157,0.730283,0.899978,0.632945,0.067405,0.306290,0.577608,0.212130,0.696360

In [6]:
df.tail(3)

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
208,209,0.514533,0.651745,0.414647,0.493129,0.705009,0.660811,0.269408,0.745009,0.357690
209,210,0.526972,0.936736,0.760946,0.595550,0.512512,0.266746,0.249187,0.447963,0.242949
210,211,0.719486,0.137211,0.700355,0.156539,0.646584,0.808359,0.899380,0.477262,0.619177

In [7]:
df.index

RangeIndex(start=0, stop=211, step=1)

In [8]:
df.columns

Index(['Countries', 'Pakistan', 'England', 'France', 'Ireland', 'Bangladesh',
       'India', 'China', 'Malaysia', 'Japan'],
      dtype='object')

**DataFrame.to_numpy() return a NumPy representation of data**

In [9]:
df.to_numpy()

array([[1.00000000e+00, 8.33923952e-01, 4.68437656e-01, ...,
        5.75246538e-01, 9.57163265e-01, 2.75795510e-01],
       [2.00000000e+00, 2.02625215e-01, 1.04223574e-01, ...,
        2.79925382e-01, 9.35100628e-01, 5.96370002e-01],
       [3.00000000e+00, 2.96203067e-01, 9.36567703e-01, ...,
        8.90937006e-01, 3.87882438e-01, 8.45204020e-01],
       ...,
       [2.09000000e+02, 5.14532677e-01, 6.51745263e-01, ...,
        2.69408004e-01, 7.45008683e-01, 3.57690209e-01],
       [2.10000000e+02, 5.26972174e-01, 9.36736405e-01, ...,
        2.49187139e-01, 4.47963043e-01, 2.42949065e-01],
       [2.11000000e+02, 7.19485950e-01, 1.37210579e-01, ...,
        8.99380129e-01, 4.77261608e-01, 6.19177441e-01]])

**describe() function shows the statistics of data**

In [10]:
df.describe()

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
count,211.00000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000
mean,106.00000,0.508663,0.525189,0.505250,0.476187,0.518576,0.498315,0.482564,0.541539,0.501819
std,61.05462,0.288201,0.309383,0.284018,0.296567,0.279038,0.291102,0.300672,0.281385,0.296679
min,1.00000,0.004021,0.005630,0.007692,0.002475,0.003530,0.008182,0.002393,0.004270,0.007621
25%,53.50000,0.274546,0.208432,0.270829,0.206663,0.285189,0.241194,0.220099,0.320935,0.238821
50%,106.00000,0.531893,0.553448,0.503806,0.462348,0.520815,0.479728,0.470906,0.562049,0.494288
75%,158.50000,0.745937,0.811816,0.736857,0.714290,0.756451,0.738763,0.750980,0.788837,0.760264
max,211.00000,0.996872,0.995400,0.995003,0.999377,0.994540,0.991868,0.999610,0.996227,0.999953

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Countries   211 non-null    int64
 1   Pakistan    211 non-null    float64
 2   England     211 non-null    float64
 3   France      211 non-null    float64
 4   Ireland     211 non-null    float64
 5   Bangladesh  211 non-null    float64
 6   India       211 non-null    float64
 7   China       211 non-null    float64
 8   Malaysia    211 non-null    float64
 9   Japan       211 non-null    float64
dtypes: float64(9), int64(1)
memory usage: 16.6 KB

**df.T takes transpose of data**

In [13]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,201,202,203,204,205,206,207,208,209,210
Countries,1.000000,2.000000,3.000000,4.000000,5.000000,6.000000,7.000000,8.000000,9.000000,10.000000,...,202.000000,203.000000,204.000000,205.000000,206.000000,207.000000,208.000000,209.000000,210.000000,211.000000
Pakistan,0.833924,0.202625,0.296203,0.163554,0.439157,0.729732,0.976021,0.284538,0.790656,0.646244,...,0.309878,0.339075,0.744271,0.140526,0.596655,0.052870,0.764549,0.514533,0.526972,0.719486
England,0.468438,0.104224,0.936568,0.535208,0.730283,0.341075,0.831999,0.122512,0.616224,0.068346,...,0.190780,0.470920,0.672616,0.163762,0.576417,0.307746,0.038046,0.651745,0.936736,0.137211
France,0.095948,0.866294,0.686544,0.866781,0.899978,0.657711,0.140151,0.260198,0.021431,0.895482,...,0.745054,0.276289,0.707695,0.811422,0.995003,0.432467,0.761691,0.414647,0.760946,0.700355
Ireland,0.904593,0.151645,0.645033,0.240554,0.632945,0.092706,0.354894,0.017634,0.700729,0.172926,...,0.061116,0.477380,0.272229,0.394911,0.125688,0.844604,0.278519,0.493129,0.595550,0.156539
Bangladesh,0.233213,0.411856,0.862706,0.113160,0.067405,0.396754,0.283919,0.723463,0.276668,0.728627,...,0.801099,0.524758,0.020388,0.071098,0.694167,0.741771,0.143301,0.705009,0.512512,0.646584
India,0.096233,0.138506,0.364900,0.574719,0.306290,0.424519,0.934934,0.746887,0.591335,0.103740,...,0.401671,0.190378,0.210675,0.459578,0.131699,0.866744,0.540240,0.660811,0.266746,0.808359
China,0.575247,0.279925,0.890937,0.216449,0.577608,0.788068,0.228595,0.507473,0.185024,0.195139,...,0.167460,0.518785,0.417283,0.964873,0.003586,0.030094,0.807247,0.269408,0.249187,0.899380
Malaysia,0.957163,0.935101,0.387882,0.839201,0.212130,0.685315,0.402528,0.941627,0.461291,0.550232,...,0.658099,0.416940,0.588926,0.187654,0.733464,0.652044,0.418377,0.745009,0.447963,0.477262
Japan,0.275796,0.596370,0.845204,0.777353,0.696360,0.581654,0.800813,0.681480,0.433925,0.502282,...,0.926063,0.717018,0.313265,0.444583,0.737588,0.421857,0.296205,0.357690,0.242949,0.619177

In [20]:
df.median()

Countries     106.000000
Pakistan        0.531893
England         0.553448
France          0.503806
Ireland         0.462348
Bangladesh      0.520815
India           0.479728
China           0.470906
Malaysia        0.562049
Japan           0.494288
dtype: float64

**Mode shows the most frequent data**

In [21]:
df.mode()

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
0,1,0.004021,0.005630,0.007692,0.002475,0.003530,0.008182,0.002393,0.004270,0.007621
1,2,0.005212,0.015862,0.014939,0.002698,0.007923,0.016033,0.003586,0.020895,0.009631
2,3,0.011667,0.016461,0.021431,0.013743,0.018170,0.023441,0.007679,0.023930,0.015471
3,4,0.013540,0.016607,0.025395,0.017634,0.020388,0.025441,0.009694,0.028075,0.018670
4,5,0.018483,0.019923,0.025653,0.024329,0.023598,0.026739,0.009767,0.029415,0.019579
...,...,...,...,...,...,...,...,...,...,...
206,207,0.975789,0.976042,0.977142,0.975633,0.981859,0.982591,0.991013,0.980352,0.993453
207,208,0.976021,0.979888,0.978719,0.993953,0.983865,0.985152,0.993627,0.981563,0.995086
208,209,0.982784,0.982499,0.990099,0.994708,0.990151,0.985822,0.994231,0.987322,0.995460
209,210,0.985108,0.982698,0.990842,0.997781,0.993424,0.988855,0.996519,0.989139,0.998536
210,211,0.996872,0.995400,0.995003,0.999377,0.994540,0.991868,0.999610,0.996227,0.999953

**Mean gives the average of data**

In [19]:
df.mean()

Countries     106.000000
Pakistan        0.508663
England         0.525189
France          0.505250
Ireland         0.476187
Bangladesh      0.518576
India           0.498315
China           0.482564
Malaysia        0.541539
Japan           0.501819
dtype: float64

**DataFrame.sort_index() sorts by an axis**

In [14]:
df.sort_index(axis=1, ascending=False)

,Pakistan,Malaysia,Japan,Ireland,India,France,England,Countries,China,Bangladesh
0,0.833924,0.957163,0.275796,0.904593,0.096233,0.095948,0.468438,1,0.575247,0.233213
1,0.202625,0.935101,0.596370,0.151645,0.138506,0.866294,0.104224,2,0.279925,0.411856
2,0.296203,0.387882,0.845204,0.645033,0.364900,0.686544,0.936568,3,0.890937,0.862706
3,0.163554,0.839201,0.777353,0.240554,0.574719,0.866781,0.535208,4,0.216449,0.113160
4,0.439157,0.212130,0.696360,0.632945,0.306290,0.899978,0.730283,5,0.577608,0.067405
...,...,...,...,...,...,...,...,...,...,...
206,0.052870,0.652044,0.421857,0.844604,0.866744,0.432467,0.307746,207,0.030094,0.741771
207,0.764549,0.418377,0.296205,0.278519,0.540240,0.761691,0.038046,208,0.807247,0.143301
208,0.514533,0.745009,0.357690,0.493129,0.660811,0.414647,0.651745,209,0.269408,0.705009
209,0.526972,0.447963,0.242949,0.595550,0.266746,0.760946,0.936736,210,0.249187,0.512512
210,0.719486,0.477262,0.619177,0.156539,0.808359,0.700355,0.137211,211,0.899380,0.646584

**DataFrame.sort_values() sorts by values**

In [15]:
df.sort_values(by="England")

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
40,41,0.272920,0.005630,0.698172,0.997781,0.180640,0.401929,0.983976,0.128694,0.506812
47,48,0.184558,0.015862,0.869031,0.013743,0.994540,0.150771,0.685556,0.894684,0.607277
122,123,0.031488,0.016461,0.755804,0.273259,0.055653,0.580235,0.031307,0.048541,0.211033
133,134,0.358215,0.016607,0.396646,0.702044,0.811071,0.643149,0.455758,0.063451,0.928047
153,154,0.526525,0.019923,0.655086,0.732369,0.110308,0.162053,0.372783,0.424608,0.169551
...,...,...,...,...,...,...,...,...,...,...
116,117,0.705066,0.976042,0.753546,0.259861,0.258089,0.426526,0.114949,0.463627,0.980240
17,18,0.273605,0.979888,0.416025,0.129557,0.851355,0.957352,0.952793,0.490943,0.764184
51,52,0.836146,0.982499,0.477661,0.780700,0.669740,0.815201,0.474415,0.178133,0.196811
196,197,0.099799,0.982698,0.639635,0.075035,0.070191,0.654878,0.996519,0.031398,0.526981
76,77,0.480625,0.995400,0.327664,0.780346,0.077403,0.016033,0.538957,0.118883,0.957545

**Selection**

**Getitem ()**

In [24]:
df["Pakistan"]

0      0.833924
1      0.202625
2      0.296203
3      0.163554
4      0.439157
         ...
206    0.052870
207    0.764549
208    0.514533
209    0.526972
210    0.719486
Name: Pakistan, Length: 211, dtype: float64

**Slicing**

In [25]:
df[1:9]

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
1,2,0.202625,0.104224,0.866294,0.151645,0.411856,0.138506,0.279925,0.935101,0.596370
2,3,0.296203,0.936568,0.686544,0.645033,0.862706,0.364900,0.890937,0.387882,0.845204
3,4,0.163554,0.535208,0.866781,0.240554,0.113160,0.574719,0.216449,0.839201,0.777353
4,5,0.439157,0.730283,0.899978,0.632945,0.067405,0.306290,0.577608,0.212130,0.696360
5,6,0.729732,0.341075,0.657711,0.092706,0.396754,0.424519,0.788068,0.685315,0.581654
6,7,0.976021,0.831999,0.140151,0.354894,0.283919,0.934934,0.228595,0.402528,0.800813
7,8,0.284538,0.122512,0.260198,0.017634,0.723463,0.746887,0.507473,0.941627,0.681480
8,9,0.790656,0.616224,0.021431,0.700729,0.276668,0.591335,0.185024,0.461291,0.433925

**DataFrame.loc() or DataFrame.at()**

In [16]:
df.loc[:, ["France", "India"]]

       France     India
0    0.095948  0.096233
1    0.866294  0.138506
2    0.686544  0.364900
3    0.866781  0.574719
4    0.899978  0.306290
..        ...       ...
206  0.432467  0.866744
207  0.761691  0.540240
208  0.414647  0.660811
209  0.760946  0.266746
210  0.700355  0.808359

[211 rows x 2 columns]

**Selection by position**

In [18]:
df.iloc[2]

Countries     3.000000
Pakistan      0.296203
England       0.936568
France        0.686544
Ireland       0.645033
Bangladesh    0.862706
India         0.364900
China         0.890937
Malaysia      0.387882
Japan         0.845204
Name: 2, dtype: float64

In [19]:
df.iloc[3:5, 0:2]

   Countries  Pakistan
3          4  0.163554
4          5  0.439157

In [20]:
df.iloc[1:3, :]

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
1,2,0.202625,0.104224,0.866294,0.151645,0.411856,0.138506,0.279925,0.935101,0.596370
2,3,0.296203,0.936568,0.686544,0.645033,0.862706,0.364900,0.890937,0.387882,0.845204

In [21]:
df.iloc[1, 1]

0.20262521512892873

In [22]:
df.iat[1, 1]

0.20262521512892873

**Indexing Boolean**

In [23]:
df[df["China"] > 0]

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
0,1,0.833924,0.468438,0.095948,0.904593,0.233213,0.096233,0.575247,0.957163,0.275796
1,2,0.202625,0.104224,0.866294,0.151645,0.411856,0.138506,0.279925,0.935101,0.596370
2,3,0.296203,0.936568,0.686544,0.645033,0.862706,0.364900,0.890937,0.387882,0.845204
3,4,0.163554,0.535208,0.866781,0.240554,0.113160,0.574719,0.216449,0.839201,0.777353
4,5,0.439157,0.730283,0.899978,0.632945,0.067405,0.306290,0.577608,0.212130,0.696360
...,...,...,...,...,...,...,...,...,...,...
206,207,0.052870,0.307746,0.432467,0.844604,0.741771,0.866744,0.030094,0.652044,0.421857
207,208,0.764549,0.038046,0.761691,0.278519,0.143301,0.540240,0.807247,0.418377,0.296205
208,209,0.514533,0.651745,0.414647,0.493129,0.705009,0.660811,0.269408,0.745009,0.357690
209,210,0.526972,0.936736,0.760946,0.595550,0.512512,0.266746,0.249187,0.447963,0.242949
210,211,0.719486,0.137211,0.700355,0.156539,0.646584,0.808359,0.899380,0.477262,0.619177

In [24]:
df[df > 0]

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
0,1,0.833924,0.468438,0.095948,0.904593,0.233213,0.096233,0.575247,0.957163,0.275796
1,2,0.202625,0.104224,0.866294,0.151645,0.411856,0.138506,0.279925,0.935101,0.596370
2,3,0.296203,0.936568,0.686544,0.645033,0.862706,0.364900,0.890937,0.387882,0.845204
3,4,0.163554,0.535208,0.866781,0.240554,0.113160,0.574719,0.216449,0.839201,0.777353
4,5,0.439157,0.730283,0.899978,0.632945,0.067405,0.306290,0.577608,0.212130,0.696360
...,...,...,...,...,...,...,...,...,...,...
206,207,0.052870,0.307746,0.432467,0.844604,0.741771,0.866744,0.030094,0.652044,0.421857
207,208,0.764549,0.038046,0.761691,0.278519,0.143301,0.540240,0.807247,0.418377,0.296205
208,209,0.514533,0.651745,0.414647,0.493129,0.705009,0.660811,0.269408,0.745009,0.357690
209,210,0.526972,0.936736,0.760946,0.595550,0.512512,0.266746,0.249187,0.447963,0.242949
210,211,0.719486,0.137211,0.700355,0.156539,0.646584,0.808359,0.899380,0.477262,0.619177

In [27]:
df.iat[0, 1] = 0

In [28]:
df

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
0,1,0.000000,0.468438,0.095948,0.904593,0.233213,0.096233,0.575247,0.957163,0.275796
1,2,0.202625,0.104224,0.866294,0.151645,0.411856,0.138506,0.279925,0.935101,0.596370
2,3,0.296203,0.936568,0.686544,0.645033,0.862706,0.364900,0.890937,0.387882,0.845204
3,4,0.163554,0.535208,0.866781,0.240554,0.113160,0.574719,0.216449,0.839201,0.777353
4,5,0.439157,0.730283,0.899978,0.632945,0.067405,0.306290,0.577608,0.212130,0.696360
...,...,...,...,...,...,...,...,...,...,...
206,207,0.052870,0.307746,0.432467,0.844604,0.741771,0.866744,0.030094,0.652044,0.421857
207,208,0.764549,0.038046,0.761691,0.278519,0.143301,0.540240,0.807247,0.418377,0.296205
208,209,0.514533,0.651745,0.414647,0.493129,0.705009,0.660811,0.269408,0.745009,0.357690
209,210,0.526972,0.936736,0.760946,0.595550,0.512512,0.266746,0.249187,0.447963,0.242949
210,211,0.719486,0.137211,0.700355,0.156539,0.646584,0.808359,0.899380,0.477262,0.619177

In [29]:
df2 = df.copy()

df2[df2 > 0] = -df2

df2

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
0,-1,0.000000,-0.468438,-0.095948,-0.904593,-0.233213,-0.096233,-0.575247,-0.957163,-0.275796
1,-2,-0.202625,-0.104224,-0.866294,-0.151645,-0.411856,-0.138506,-0.279925,-0.935101,-0.596370
2,-3,-0.296203,-0.936568,-0.686544,-0.645033,-0.862706,-0.364900,-0.890937,-0.387882,-0.845204
3,-4,-0.163554,-0.535208,-0.866781,-0.240554,-0.113160,-0.574719,-0.216449,-0.839201,-0.777353
4,-5,-0.439157,-0.730283,-0.899978,-0.632945,-0.067405,-0.306290,-0.577608,-0.212130,-0.696360
...,...,...,...,...,...,...,...,...,...,...
206,-207,-0.052870,-0.307746,-0.432467,-0.844604,-0.741771,-0.866744,-0.030094,-0.652044,-0.421857
207,-208,-0.764549,-0.038046,-0.761691,-0.278519,-0.143301,-0.540240,-0.807247,-0.418377,-0.296205
208,-209,-0.514533,-0.651745,-0.414647,-0.493129,-0.705009,-0.660811,-0.269408,-0.745009,-0.357690
209,-210,-0.526972,-0.936736,-0.760946,-0.595550,-0.512512,-0.266746,-0.249187,-0.447963,-0.242949
210,-211,-0.719486,-0.137211,-0.700355,-0.156539,-0.646584,-0.808359,-0.899380,-0.477262,-0.619177

In [30]:
pd.isna(df)

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
206,False,False,False,False,False,False,False,False,False,False
207,False,False,False,False,False,False,False,False,False,False
208,False,False,False,False,False,False,False,False,False,False
209,False,False,False,False,False,False,False,False,False,False
210,False,False,False,False,False,False,False,False,False,False

In [31]:
df.mean(axis=1)

0       0.460663
1       0.568654
2       0.891598
3       0.832698
4       0.956216
         ...
206    21.135020
207    21.204817
208    21.381198
209    21.453956
210    21.616435
Length: 211, dtype: float64

In [32]:
df.sub(s, axis="index")

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
0,Countries Pakistan England France ...,Countries Pakistan England France ...,Countries Pakistan England France ...,Countries Pakistan England France ...,Countries Pakistan England France ...,Countries Pakistan England France ...,Countries Pakistan England France ...,Countries Pakistan England France ...,Countries Pakistan England France ...,Countries Pakistan England France ...
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**user define function**

In [33]:
df.agg(lambda x: np.mean(x) * 5.6)

Countries     593.600000
Pakistan        2.826382
England         2.941058
France          2.829399
Ireland         2.666646
Bangladesh      2.904024
India           2.790564
China           2.702357
Malaysia        3.032618
Japan           2.810188
dtype: float64

In [34]:
df.transform(lambda x: x * 101.2)

,Countries,Pakistan,England,France,Ireland,Bangladesh,India,China,Malaysia,Japan
0,101.2,0.000000,47.405891,9.709964,91.544768,23.601134,9.738761,58.214950,96.864922,27.910506
1,202.4,20.505672,10.547426,87.668906,15.346434,41.679823,14.016811,28.328449,94.632184,60.352644
2,303.6,29.975750,94.780652,69.478220,65.277323,87.305824,36.927858,90.162825,39.253703,85.534647
3,404.8,16.551659,54.163061,87.718207,24.344046,11.451767,58.161600,21.904620,84.927132,78.668131
4,506.0,44.442709,73.904684,91.077792,64.054050,6.821357,30.996524,58.453924,21.467604,70.471644
...,...,...,...,...,...,...,...,...,...,...
206,20948.4,5.350486,31.143930,43.765675,85.473926,75.067207,87.714477,3.045506,65.986861,42.691892
207,21049.6,77.372328,3.850283,77.083166,28.186120,14.502011,54.672302,81.693435,42.339725,29.975913
208,21150.8,52.070707,65.956621,41.962324,49.904640,71.346897,66.874057,27.264090,75.394879,36.198249
209,21252.0,53.329584,94.797724,77.007729,60.269680,51.866247,26.994744,25.217738,45.333860,24.586445
210,21353.2,72.811978,13.885711,70.875895,15.841741,65.434265,81.805943,91.017269,48.298875,62.660757

In [35]:
df.value_counts()

Countries  Pakistan  England   France    Ireland   Bangladesh  India     China     Malaysia  Japan
1          0.000000  0.468438  0.095948  0.904593  0.233213    0.096233  0.575247  0.957163  0.275796    1
159        0.813713  0.919559  0.558588  0.566791  0.809163    0.603503  0.254763  0.127226  0.995086    1
135        0.513565  0.747898  0.943295  0.999377  0.756436    0.954280  0.474869  0.121252  0.974830    1
136        0.724316  0.108048  0.428056  0.124489  0.564790    0.528828  0.493545  0.421903  0.253578    1
137        0.732761  0.671341  0.436845  0.058325  0.450246    0.482830  0.139768  0.591102  0.956477    1
                                                                                                        ..
74         0.050892  0.565277  0.598633  0.072588  0.545174    0.165470  0.009694  0.267363  0.730367    1
75         0.409673  0.866585  0.291837  0.466914  0.405720    0.295160  0.915518  0.216628  0.462749    1
76         0.833188  0.583076  0.697821  0.914883  0.420764    0.141608  0.876676  0.858137  0.597184    1
77         0.480625  0.995400  0.327664  0.780346  0.077403    0.016033  0.538957  0.118883  0.957545    1
211        0.719486  0.137211  0.700355  0.156539  0.646584    0.808359  0.899380  0.477262  0.619177    1
Name: count, Length: 211, dtype: int64

In [36]:
df = pd.DataFrame(np.random.randn(10, 4))

df

          0         1         2         3
0  0.631062 -0.528054 -0.470573  1.823920
1 -0.092035 -1.886617 -0.951518 -1.378333
2  0.339931  0.392467  0.667496 -0.050798
3  0.875088  1.441261 -0.500300 -0.884654
4 -0.335705 -0.862674 -2.054561  0.071912
5 -0.315846  0.207461 -0.754125 -1.907456
6  1.036129  1.845841  1.015150 -0.423537
7 -0.385867  0.380777  0.125247  0.361655
8 -0.795357 -0.275441  1.213855 -1.184538
9  1.107389 -0.949443  0.224924 -0.689817

In [37]:
pieces = [df[:3], df[3:7], df[7:]]

pd.concat(pieces)

          0         1         2         3
0  0.631062 -0.528054 -0.470573  1.823920
1 -0.092035 -1.886617 -0.951518 -1.378333
2  0.339931  0.392467  0.667496 -0.050798
3  0.875088  1.441261 -0.500300 -0.884654
4 -0.335705 -0.862674 -2.054561  0.071912
5 -0.315846  0.207461 -0.754125 -1.907456
6  1.036129  1.845841  1.015150 -0.423537
7 -0.385867  0.380777  0.125247  0.361655
8 -0.795357 -0.275441  1.213855 -1.184538
9  1.107389 -0.949443  0.224924 -0.689817

**Stack function**

In [41]:
stacked = df.stack(future_stack=True)

stacked

0  0    0.631062
   1   -0.528054
   2   -0.470573
   3    1.823920
1  0   -0.092035
   1   -1.886617
   2   -0.951518
   3   -1.378333
2  0    0.339931
   1    0.392467
   2    0.667496
   3   -0.050798
3  0    0.875088
   1    1.441261
   2   -0.500300
   3   -0.884654
4  0   -0.335705
   1   -0.862674
   2   -2.054561
   3    0.071912
5  0   -0.315846
   1    0.207461
   2   -0.754125
   3   -1.907456
6  0    1.036129
   1    1.845841
   2    1.015150
   3   -0.423537
7  0   -0.385867
   1    0.380777
   2    0.125247
   3    0.361655
8  0   -0.795357
   1   -0.275441
   2    1.213855
   3   -1.184538
9  0    1.107389
   1   -0.949443
   2    0.224924
   3   -0.689817
dtype: float64

In [42]:
stacked.unstack()

          0         1         2         3
0  0.631062 -0.528054 -0.470573  1.823920
1 -0.092035 -1.886617 -0.951518 -1.378333
2  0.339931  0.392467  0.667496 -0.050798
3  0.875088  1.441261 -0.500300 -0.884654
4 -0.335705 -0.862674 -2.054561  0.071912
5 -0.315846  0.207461 -0.754125 -1.907456
6  1.036129  1.845841  1.015150 -0.423537
7 -0.385867  0.380777  0.125247  0.361655
8 -0.795357 -0.275441  1.213855 -1.184538
9  1.107389 -0.949443  0.224924 -0.689817

**Sorting**

In [49]:
df.sort_values

<bound method DataFrame.sort_values of           0         1         2         3
0  0.631062 -0.528054 -0.470573  1.823920
1 -0.092035 -1.886617 -0.951518 -1.378333
2  0.339931  0.392467  0.667496 -0.050798
3  0.875088  1.441261 -0.500300 -0.884654
4 -0.335705 -0.862674 -2.054561  0.071912
5 -0.315846  0.207461 -0.754125 -1.907456
6  1.036129  1.845841  1.015150 -0.423537
7 -0.385867  0.380777  0.125247  0.361655
8 -0.795357 -0.275441  1.213855 -1.184538
9  1.107389 -0.949443  0.224924 -0.689817>