In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\dit\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dit\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dit\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dit\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dit\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\dit\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install numpy

Requirement already satisfied: numpy in c:\users\dit\appdata\local\programs\python\python312\lib\site-packages (2.1.1)
Note: you may need to restart the kernel to use updated packages.

Name: Aqsa Tufail<br>
Email: aqsatufail29@gmail.com

In [3]:
import pandas as pd
import numpy as np

In [4]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\dit\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dit\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
# 1. DataFrame
df1 = pd.read_excel("Dataset.xlsx")
df1

        Name  Salary Department
0       Aqsa   56788         IT
1      Laiba   56788    Physics
2     Maryam   67899  Chemistry
3     Ayesha   80000         CS
4    Rimsha    67788     Botony
..       ...     ...        ...
194     Remi   33345    Physics
195  Charlie   46678         AI
196  Adalynn   45567         ML
197   Ashley   45677    Physics
198  Georgia   46778  Chemistry

[199 rows x 3 columns]

In [6]:
df = pd.DataFrame(df1)
print ("Original DataFrame")
print(df)

Original DataFrame
        Name  Salary Department
0       Aqsa   56788         IT
1      Laiba   56788    Physics
2     Maryam   67899  Chemistry
3     Ayesha   80000         CS
4    Rimsha    67788     Botony
..       ...     ...        ...
194     Remi   33345    Physics
195  Charlie   46678         AI
196  Adalynn   45567         ML
197   Ashley   45677    Physics
198  Georgia   46778  Chemistry

[199 rows x 3 columns]

In [7]:
# 2. Basic Dataframe Info:
print("\n DataFrame Info:")
print(df.info())
print("\n Statistics Summary:")
print(df.describe())

 DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        199 non-null    object
 1   Salary      199 non-null    int64
 2   Department  199 non-null    object
dtypes: int64(1), object(2)
memory usage: 4.8+ KB
None

 Statistics Summary:
              Salary
count     199.000000
mean    63546.663317
std     61503.623245
min     26788.000000
25%     45677.000000
50%     58062.000000
75%     67899.000000
max    789766.000000

In [8]:
# 3. Sorting:
sorted_df = df.sort_values(by = 'Salary')
print("\n Dataframe sorted by Salary:")
print(sorted_df)

 Dataframe sorted by Salary:
          Name  Salary Department
106     Eloise   26788    Zoology
15      Amelia   27908  Chemistry
50     Delilah   27908    Physics
8      Mahnoor   27908         DL
55      Oakley   27908  Chemistry
..         ...     ...        ...
188      Lilah   88888         IT
148     Aubrey   88888    Physics
129  Katherine   88888  Chemistry
111      Alana  456779         DL
107       Myla  789766         AI

[199 rows x 3 columns]

In [10]:
# 4. Filtering Data (e.g; Salary > 60000)
filtered_df = df[df['Salary']>60000]
print("\n Filtered DataFrame(Salary > 60000):")
print(filtered_df)

 Filtered DataFrame(Salary > 60000):
        Name  Salary Department
2     Maryam   67899  Chemistry
3     Ayesha   80000         CS
4    Rimsha    67788     Botony
5      Maria   68888    Zoology
10    Olivia   88888  Chemistry
..       ...     ...        ...
179    Rylee   67899    Physics
182   Aliyah   67899         ML
185    Alaia   66777  Chemistry
188    Lilah   88888         IT
191    Amara   67899         CS

[70 rows x 3 columns]

In [11]:
# 5. Adding a new column ( bonus as 10% of Saray)
df['Bonus'] = df ['Salary'] * 0.5
print("\n Dataframe wih Bonus column added:")
print(df)

 Dataframe wih Bonus column added:
        Name  Salary Department    Bonus
0       Aqsa   56788         IT  28394.0
1      Laiba   56788    Physics  28394.0
2     Maryam   67899  Chemistry  33949.5
3     Ayesha   80000         CS  40000.0
4    Rimsha    67788     Botony  33894.0
..       ...     ...        ...      ...
194     Remi   33345    Physics  16672.5
195  Charlie   46678         AI  23339.0
196  Adalynn   45567         ML  22783.5
197   Ashley   45677    Physics  22838.5
198  Georgia   46778  Chemistry  23389.0

[199 rows x 4 columns]

In [12]:
# 6. Grouping Data by Department and Calculating the Average Salary
grouped_df = df.groupby('Department')['Salary'].mean().reset_index()
print(grouped_df)

  Department         Salary
0         AI  109488.750000
1     Botony   59798.833333
2         CS   62114.200000
3  Chemistry   58914.142857
4         DL   67401.962963
5         IT   54489.461538
6         ML   59614.628571
7    Physics   55602.487805
8    Zoology   58386.750000

In [13]:
df.to_numpy()

array([['Aqsa', 56788, 'IT', 28394.0],
       ['Laiba', 56788, 'Physics', 28394.0],
       ['Maryam', 67899, 'Chemistry', 33949.5],
       ['Ayesha', 80000, 'CS', 40000.0],
       ['Rimsha ', 67788, 'Botony', 33894.0],
       ['Maria', 68888, 'Zoology', 34444.0],
       ['Neha', 45566, 'AI', 22783.0],
       ['Hira', 45578, 'ML', 22789.0],
       ['Mahnoor', 27908, 'DL', 13954.0],
       ['Saba', 58062, 'Physics', 29031.0],
       ['Olivia', 88888, 'Chemistry', 44444.0],
       ['Emma', 67788, 'AI', 33894.0],
       [' Luna', 68888, 'ML', 34444.0],
       ['Charlotte', 45566, 'IT', 22783.0],
       ['Evelyn', 45578, 'Physics', 22789.0],
       ['Amelia', 27908, 'Chemistry', 13954.0],
       ['Ava', 58062, 'CS', 29031.0],
       ['Sophia', 88888, 'ML', 44444.0],
       ['Mia', 56788, 'Botony', 28394.0],
       ['Isabella', 67899, 'Zoology', 33949.5],
       ['Lia', 80000, 'AI', 40000.0],
       ['Melanie', 67788, 'ML', 33894.0],
       ['Ivy', 68888, 'DL', 34444.0],
       ['Amira', 58062, 'Botony', 29031.0],
       ['Grace', 88888, 'Zoology', 44444.0],
       ['Margaret', 67788, 'AI', 33894.0],
       ['Lucy', 68888, 'ML', 34444.0],
       ['Piper', 45566, 'DL', 22783.0],
       ['Willow', 58062, 'ML', 29031.0],
       ['Brielle', 88888, 'Botony', 44444.0],
       ['Emilia', 56788, 'Zoology', 28394.0],
       ['Mary', 67899, 'AI', 33949.5],
       ['Riley', 80000, 'ML', 40000.0],
       ['Freya', 45566, 'DL', 22783.0],
       ['Naomi', 58062, 'Physics', 29031.0],
       ['Cecilia', 88888, 'Chemistry', 44444.0],
       ['Victoria', 56788, 'Physics', 28394.0],
       ['Esther', 45566, 'Chemistry', 22783.0],
       ['Stella', 58062, 'IT', 29031.0],
       ['Arya', 88888, 'Physics', 44444.0],
       ['Elena', 56788, 'Chemistry', 28394.0],
       ['Sage', 45566, 'CS', 22783.0],
       ['Hannah', 58062, 'Chemistry', 29031.0],
       ['Sienna', 88888, 'Physics', 44444.0],
       ['Valentina', 56788, 'Physics', 28394.0],
       ['Summer', 27908, 'Chemistry', 13954.0],
       ['Maya', 58062, 'Physics', 29031.0],
       ['Peyton', 88888, 'Chemistry', 44444.0],
       ['Zoey', 56788, 'Physics', 28394.0],
       ['Sloane', 67899, 'IT', 33949.5],
       ['Delilah', 27908, 'Physics', 13954.0],
       ['Valeria', 58062, 'Chemistry', 29031.0],
       ['Leah', 88888, 'CS', 44444.0],
       ['Brianna', 56788, 'IT', 28394.0],
       ['Lainey', 67899, 'Physics', 33949.5],
       ['Oakley', 27908, 'Chemistry', 13954.0],
       ['Lillian', 58062, 'CS', 29031.0],
       ['Blakely', 88888, 'Botony', 44444.0],
       ['Paisley', 56788, 'Zoology', 28394.0],
       ['Kehlani', 67899, 'AI', 33949.5],
       ['Genesis', 56788, 'ML', 28394.0],
       ['Valerie', 67899, 'DL', 33949.5],
       ['Madelyn', 80000, 'ML', 40000.0],
       ['Magnolia', 45566, 'Botony', 22783.0],
       ['Sadie', 45566, 'Zoology', 22783.0],
       ['Emersyn', 58062, 'AI', 29031.0],
       ['Sophie', 88888, 'ML', 44444.0],
       ['Everly', 56788, 'DL', 28394.0],
       ['Leilani', 67899, 'IT', 33949.5],
       ['Catalina', 27908, 'Physics', 13954.0],
       ['Addison', 58062, 'Chemistry', 29031.0],
       ['Margot', 88888, 'CS', 44444.0],
       ['Natalie', 56788, 'IT', 28394.0],
       ['Everleigh', 67899, 'Physics', 33949.5],
       ['Josephine', 88888, 'Chemistry', 44444.0],
       ['Alina', 56788, 'CS', 28394.0],
       ['Alice', 27908, 'IT', 13954.0],
       ['Oaklynn', 58062, 'Physics', 29031.0],
       ['Ruby', 88888, 'Chemistry', 44444.0],
       ['ximena', 56788, 'CS', 28394.0],
       ['Claire', 67899, 'Physics', 33949.5],
       ['Elsie', 27908, 'Chemistry', 13954.0],
       ['Kinsley', 58062, 'Physics', 29031.0],
       ['Ruth', 88888, 'Chemistry', 44444.0],
       ['Sara', 80000, 'Physics', 40000.0],
       ['Isabelle', 45566, 'Chemistry', 22783.0],
       ['Emery', 45566, 'Botony', 22783.0],
       ['Jasmine', 58062, 'Zoology', 29031.0],
       ['Adeline', 88888, 'AI', 44444.0],
       ['Juliette', 56788, 'ML', 28394.0],
       ['Kennedy', 56788, 'DL', 28394.0],
       ['Emerson', 67899, 'Chemistry', 33949.5],
       ['Maeve', 27908, 'Physics', 13954.0],
       ['Phoebe', 58062, 'Chemistry', 29031.0],
       ['Audrey', 88888, 'ML', 44444.0],
       ['Adaline', 56788, 'DL', 28394.0],
       ['Autumn', 67899, 'Physics', 33949.5],
       ['River', 45677, 'DL', 22838.5],
       ['Athena', 46778, 'Physics', 23389.0],
       ['Callie', 35678, 'ML', 17839.0],
       ['Eden', 58062, 'DL', 29031.0],
       ['Kaylee', 35678, 'Physics', 17839.0],
       ['Iris', 88888, 'AI', 44444.0],
       ['Olive', 56788, 'ML', 28394.0],
       ['Anna', 67899, 'DL', 33949.5],
       ['Rosalie', 77888, 'Botony', 38944.0],
       ['Eloise', 26788, 'Zoology', 13394.0],
       ['Myla', 789766, 'AI', 394883.0],
       ['Jade', 88888, 'ML', 44444.0],
       ['Ariella', 56788, 'DL', 28394.0],
       ['Maria', 67899, 'ML', 33949.5],
       ['Alana', 456779, 'DL', 228389.5],
       ['Caroline', 45677, 'Physics', 22838.5],
       ['Kaia', 46778, 'DL', 23389.0],
       ['Brooklyn', 35678, 'Botony', 17839.0],
       ['Amaya', 58062, 'Zoology', 29031.0],
       ['Quinn', 35678, 'AI', 17839.0],
       ['sIsabel', 67777, 'ML', 33888.5],
       ['Aaliyah', 34557, 'DL', 17278.5],
       ['Hallie', 58062, 'ML', 29031.0],
       ['Vivian', 88888, 'DL', 44444.0],
       ['Mackenzie', 56788, 'Physics', 28394.0],
       ['Liliana', 67899, 'ML', 33949.5],
       ['Genevieve', 56788, 'DL', 28394.0],
       ['Gabriella', 67899, 'Physics', 33949.5],
       ['Anastasia', 80000, 'Physics', 40000.0],
       ['Hailey', 45566, 'Chemistry', 22783.0],
       ['Reagan', 67899, 'IT', 33949.5],
       ['Sarah', 56788, 'Physics', 28394.0],
       ['Katherine', 88888, 'Chemistry', 44444.0],
       ['Savannah', 56788, 'CS', 28394.0],
       ['Ember', 67899, 'ML', 33949.5],
       ['Cora', 27908, 'DL', 13954.0],
       ['June', 58062, 'Physics', 29031.0],
       ['Madeline', 88888, 'Botony', 44444.0],
       ['Bailey', 56788, 'Zoology', 28394.0],
       ['Natalia', 67899, 'AI', 33949.5],
       ['Andrea', 56788, 'ML', 28394.0],
       ['Ariana', 66778, 'DL', 33389.0],
       ['Adalyn', 56788, 'AI', 28394.0],
       ['Lydia', 67899, 'ML', 33949.5],
       ['Presley', 27908, 'Botony', 13954.0],
       ['Lyla', 58062, 'Zoology', 29031.0],
       ['Reese', 88888, 'AI', 44444.0],
       ['Clara', 56788, 'ML', 28394.0],
       ['Wrenley', 67899, 'DL', 33949.5],
       ['Allison', 27908, 'ML', 13954.0],
       ['Gemma', 58062, 'DL', 29031.0],
       ['Aubrey', 88888, 'Physics', 44444.0],
       ['Millie', 56788, 'Physics', 28394.0],
       ['Ada', 35678, 'Botony', 17839.0],
       ['Melody', 58062, 'Zoology', 29031.0],
       ['Alani', 33345, 'AI', 16672.5],
       ['Ayla', 46678, 'ML', 23339.0],
       ['Zuri', 27908, 'DL', 13954.0],
       ['Serenity', 33345, 'Physics', 16672.5],
       ['Alexandra', 46678, 'ML', 23339.0],
       ['Bella', 27908, 'IT', 13954.0],
       ['Alora', 35678, 'Physics', 17839.0],
       ['Skylar', 58062, 'Chemistry', 29031.0],
       ['Sutton', 56788, 'CS', 28394.0],
       ['Josie', 56788, 'ML', 28394.0],
       ['Noelle', 67899, 'DL', 33949.5],
       ['Lucia', 27908, 'Physics', 13954.0],
       ['Kylie', 58062, 'ML', 29031.0],
       ['Daisy', 33345, 'DL', 16672.5],
       ['Molly', 46678, 'Physics', 23339.0],
       ['Raelynn', 27908, 'ML', 13954.0],
       ['Lia', 27908, 'IT', 13954.0],
       ['Eva', 58062, 'Physics', 29031.0],
       ['Wren', 33345, 'Chemistry', 16672.5],
       ['Juniper', 46678, 'CS', 23339.0],
       ['Leia', 45567, 'ML', 22783.5],
       ['Samantha', 45677, 'DL', 22838.5],
       ['Evangeline', 46778, 'Physics', 23389.0],
       ['Elliana', 35678, 'Chemistry', 17839.0],
       ['Lila', 58062, 'CS', 29031.0],
       ['Eliza', 35678, 'ML', 17839.0],
       ['Aspen', 58062, 'IT', 29031.0],
       ['Rylee', 67899, 'Physics', 33949.5],
       ['Journee', 56788, 'Chemistry', 28394.0],
       ['Nevaeh', 56788, 'CS', 28394.0],
       ['Aliyah', 67899, 'ML', 33949.5],
       ['Blake', 27908, 'DL', 13954.0],
       ['Kimberly', 58062, 'Physics', 29031.0],
       ['Alaia', 66777, 'Chemistry', 33388.5],
       ['Vera', 55668, 'CS', 27834.0],
       ['Parker', 58062, 'ML', 29031.0],
       ['Lilah', 88888, 'IT', 44444.0],
       ['Julia', 56788, 'Physics', 28394.0],
       ['Amy', 56788, 'Chemistry', 28394.0],
       ['Amara', 67899, 'CS', 33949.5],
       ['Norah', 27908, 'ML', 13954.0],
       ['Rose', 58062, 'DL', 29031.0],
       ['Remi', 33345, 'Physics', 16672.5],
       ['Charlie', 46678, 'AI', 23339.0],
       ['Adalynn', 45567, 'ML', 22783.5],
       ['Ashley', 45677, 'Physics', 22838.5],
       ['Georgia', 46778, 'Chemistry', 23389.0]], dtype=object)

In [14]:
df

        Name  Salary Department    Bonus
0       Aqsa   56788         IT  28394.0
1      Laiba   56788    Physics  28394.0
2     Maryam   67899  Chemistry  33949.5
3     Ayesha   80000         CS  40000.0
4    Rimsha    67788     Botony  33894.0
..       ...     ...        ...      ...
194     Remi   33345    Physics  16672.5
195  Charlie   46678         AI  23339.0
196  Adalynn   45567         ML  22783.5
197   Ashley   45677    Physics  22838.5
198  Georgia   46778  Chemistry  23389.0

[199 rows x 4 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        199 non-null    object
 1   Salary      199 non-null    int64
 2   Department  199 non-null    object
 3   Bonus       199 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 6.3+ KB

In [16]:
df.head(10)

      Name  Salary Department    Bonus
0     Aqsa   56788         IT  28394.0
1    Laiba   56788    Physics  28394.0
2   Maryam   67899  Chemistry  33949.5
3   Ayesha   80000         CS  40000.0
4  Rimsha    67788     Botony  33894.0
5    Maria   68888    Zoology  34444.0
6     Neha   45566         AI  22783.0
7     Hira   45578         ML  22789.0
8  Mahnoor   27908         DL  13954.0
9     Saba   58062    Physics  29031.0

In [17]:
df.tail(10)

        Name  Salary Department    Bonus
189    Julia   56788    Physics  28394.0
190      Amy   56788  Chemistry  28394.0
191    Amara   67899         CS  33949.5
192    Norah   27908         ML  13954.0
193     Rose   58062         DL  29031.0
194     Remi   33345    Physics  16672.5
195  Charlie   46678         AI  23339.0
196  Adalynn   45567         ML  22783.5
197   Ashley   45677    Physics  22838.5
198  Georgia   46778  Chemistry  23389.0

In [18]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,189,190,191,192,193,194,195,196,197,198
Name,Aqsa,Laiba,Maryam,Ayesha,Rimsha,Maria,Neha,Hira,Mahnoor,Saba,...,Julia,Amy,Amara,Norah,Rose,Remi,Charlie,Adalynn,Ashley,Georgia
Salary,56788,56788,67899,80000,67788,68888,45566,45578,27908,58062,...,56788,56788,67899,27908,58062,33345,46678,45567,45677,46778
Department,IT,Physics,Chemistry,CS,Botony,Zoology,AI,ML,DL,Physics,...,Physics,Chemistry,CS,ML,DL,Physics,AI,ML,Physics,Chemistry
Bonus,28394.0,28394.0,33949.5,40000.0,33894.0,34444.0,22783.0,22789.0,13954.0,29031.0,...,28394.0,28394.0,33949.5,13954.0,29031.0,16672.5,23339.0,22783.5,22838.5,23389.0

In [19]:
df.dtypes

Name           object
Salary          int64
Department     object
Bonus         float64
dtype: object

In [20]:
df.describe()

              Salary          Bonus
count     199.000000     199.000000
mean    63546.663317   31773.331658
std     61503.623245   30751.811623
min     26788.000000   13394.000000
25%     45677.000000   22838.500000
50%     58062.000000   29031.000000
75%     67899.000000   33949.500000
max    789766.000000  394883.000000

In [21]:
df[0:15]

         Name  Salary Department    Bonus
0        Aqsa   56788         IT  28394.0
1       Laiba   56788    Physics  28394.0
2      Maryam   67899  Chemistry  33949.5
3      Ayesha   80000         CS  40000.0
4     Rimsha    67788     Botony  33894.0
5       Maria   68888    Zoology  34444.0
6        Neha   45566         AI  22783.0
7        Hira   45578         ML  22789.0
8     Mahnoor   27908         DL  13954.0
9        Saba   58062    Physics  29031.0
10     Olivia   88888  Chemistry  44444.0
11       Emma   67788         AI  33894.0
12       Luna   68888         ML  34444.0
13  Charlotte   45566         IT  22783.0
14     Evelyn   45578    Physics  22789.0

In [22]:
df["Name"]

0         Aqsa
1        Laiba
2       Maryam
3       Ayesha
4      Rimsha
        ...
194       Remi
195    Charlie
196    Adalynn
197     Ashley
198    Georgia
Name: Name, Length: 199, dtype: object

In [23]:
df.sort_index(axis=1, ascending=False)

     Salary     Name Department    Bonus
0     56788     Aqsa         IT  28394.0
1     56788    Laiba    Physics  28394.0
2     67899   Maryam  Chemistry  33949.5
3     80000   Ayesha         CS  40000.0
4     67788  Rimsha      Botony  33894.0
..      ...      ...        ...      ...
194   33345     Remi    Physics  16672.5
195   46678  Charlie         AI  23339.0
196   45567  Adalynn         ML  22783.5
197   45677   Ashley    Physics  22838.5
198   46778  Georgia  Chemistry  23389.0

[199 rows x 4 columns]

In [24]:
df.iloc[4]

Name          Rimsha
Salary          67788
Department     Botony
Bonus         33894.0
Name: 4, dtype: object

In [25]:
df.iloc[3:20, 0:1]

         Name
3      Ayesha
4     Rimsha
5       Maria
6        Neha
7        Hira
8     Mahnoor
9        Saba
10     Olivia
11       Emma
12       Luna
13  Charlotte
14     Evelyn
15     Amelia
16        Ava
17     Sophia
18        Mia
19   Isabella

In [26]:
df.iloc[57, 2]

'Botony'

In [27]:
df.iat[57, 2]

'Botony'

In [28]:
df["Name"][4]

'Rimsha '

In [29]:
df["Name"][4] = 'laiba'

C:\Users\DIT\AppData\Local\Temp\ipykernel_2468\24188655.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Name"][4] = 'laiba'

In [30]:
df

        Name  Salary Department    Bonus
0       Aqsa   56788         IT  28394.0
1      Laiba   56788    Physics  28394.0
2     Maryam   67899  Chemistry  33949.5
3     Ayesha   80000         CS  40000.0
4      laiba   67788     Botony  33894.0
..       ...     ...        ...      ...
194     Remi   33345    Physics  16672.5
195  Charlie   46678         AI  23339.0
196  Adalynn   45567         ML  22783.5
197   Ashley   45677    Physics  22838.5
198  Georgia   46778  Chemistry  23389.0

[199 rows x 4 columns]

In [31]:
df["Name"][4]

'laiba'

In [32]:
df.drop([0])

        Name  Salary Department    Bonus
1      Laiba   56788    Physics  28394.0
2     Maryam   67899  Chemistry  33949.5
3     Ayesha   80000         CS  40000.0
4      laiba   67788     Botony  33894.0
5      Maria   68888    Zoology  34444.0
..       ...     ...        ...      ...
194     Remi   33345    Physics  16672.5
195  Charlie   46678         AI  23339.0
196  Adalynn   45567         ML  22783.5
197   Ashley   45677    Physics  22838.5
198  Georgia   46778  Chemistry  23389.0

[198 rows x 4 columns]

In [33]:
df["Name"].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
194    False
195    False
196    False
197    False
198    False
Name: Name, Length: 199, dtype: bool

In [34]:
df['Name'] = None

In [35]:
df

     Name  Salary Department    Bonus
0    None   56788         IT  28394.0
1    None   56788    Physics  28394.0
2    None   67899  Chemistry  33949.5
3    None   80000         CS  40000.0
4    None   67788     Botony  33894.0
..    ...     ...        ...      ...
194  None   33345    Physics  16672.5
195  None   46678         AI  23339.0
196  None   45567         ML  22783.5
197  None   45677    Physics  22838.5
198  None   46778  Chemistry  23389.0

[199 rows x 4 columns]

In [36]:
df["Name"].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
194    True
195    True
196    True
197    True
198    True
Name: Name, Length: 199, dtype: bool

In [37]:
df['Name'][4] = 'maryam'

C:\Users\DIT\AppData\Local\Temp\ipykernel_2468\772901382.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Name'][4] = 'maryam'
C:\Users\DIT\AppData\Local\Temp\ipykernel_2468\772901382.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Name'][4] = 'maryam'

In [38]:
df

       Name  Salary Department    Bonus
0      None   56788         IT  28394.0
1      None   56788    Physics  28394.0
2      None   67899  Chemistry  33949.5
3      None   80000         CS  40000.0
4    maryam   67788     Botony  33894.0
..      ...     ...        ...      ...
194    None   33345    Physics  16672.5
195    None   46678         AI  23339.0
196    None   45567         ML  22783.5
197    None   45677    Physics  22838.5
198    None   46778  Chemistry  23389.0

[199 rows x 4 columns]

In [39]:
df.isnull()

      Name  Salary  Department  Bonus
0     True   False       False  False
1     True   False       False  False
2     True   False       False  False
3     True   False       False  False
4    False   False       False  False
..     ...     ...         ...    ...
194   True   False       False  False
195   True   False       False  False
196   True   False       False  False
197   True   False       False  False
198   True   False       False  False

[199 rows x 4 columns]

In [40]:
df.dropna()

     Name  Salary Department    Bonus
4  maryam   67788     Botony  33894.0

In [41]:
df.drop_duplicates(subset=('Department'), keep='last')

     Name  Salary Department    Bonus
150  None   35678     Botony  17839.0
151  None   58062    Zoology  29031.0
188  None   88888         IT  44444.0
191  None   67899         CS  33949.5
193  None   58062         DL  29031.0
195  None   46678         AI  23339.0
196  None   45567         ML  22783.5
197  None   45677    Physics  22838.5
198  None   46778  Chemistry  23389.0

In [42]:
df['Name'].value_counts(dropna=False)

Name
None      198
maryam      1
Name: count, dtype: int64

In [43]:
df.notnull()

      Name  Salary  Department  Bonus
0    False    True        True   True
1    False    True        True   True
2    False    True        True   True
3    False    True        True   True
4     True    True        True   True
..     ...     ...         ...    ...
194  False    True        True   True
195  False    True        True   True
196  False    True        True   True
197  False    True        True   True
198  False    True        True   True

[199 rows x 4 columns]

In [44]:
df.describe()

              Salary          Bonus
count     199.000000     199.000000
mean    63546.663317   31773.331658
std     61503.623245   30751.811623
min     26788.000000   13394.000000
25%     45677.000000   22838.500000
50%     58062.000000   29031.000000
75%     67899.000000   33949.500000
max    789766.000000  394883.000000

In [45]:
df

       Name  Salary Department    Bonus
0      None   56788         IT  28394.0
1      None   56788    Physics  28394.0
2      None   67899  Chemistry  33949.5
3      None   80000         CS  40000.0
4    maryam   67788     Botony  33894.0
..      ...     ...        ...      ...
194    None   33345    Physics  16672.5
195    None   46678         AI  23339.0
196    None   45567         ML  22783.5
197    None   45677    Physics  22838.5
198    None   46778  Chemistry  23389.0

[199 rows x 4 columns]