### Title: Pandas Practice

**Name: Ayesha**

**Import libraries pandas and numpy**

In [1]:
import pandas as pd
import numpy as np

**Object Creation**

**Creating Series**

In [2]:
s = pd.Series([1,2, 3,4, 5, np.nan, 6,7, 8])

s

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
6    6.0
7    7.0
8    8.0
dtype: float64

**date_range() function**

In [3]:
dates = pd.date_range("20240922", periods=6)

dates

DatetimeIndex(['2024-09-22', '2024-09-23', '2024-09-24', '2024-09-25',
               '2024-09-26', '2024-09-27'],
              dtype='datetime64[ns]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6, 8), index=dates, columns=list("ABCDEFGH"))

df

,A,B,C,D,E,F,G,H
2024-09-22,-2.587580,-0.866165,-0.091086,1.417251,1.265756,-0.326515,-0.915992,0.478045
2024-09-23,0.720657,-0.308635,-0.418017,0.053495,1.979844,-1.004369,-1.913845,0.985929
2024-09-24,0.665081,-0.823307,0.218447,-1.422248,-0.948106,-1.693340,-1.454448,0.377178
2024-09-25,2.159851,-0.215044,2.579014,-0.303183,2.213305,-0.289394,1.641497,-0.594250
2024-09-26,1.042749,0.358631,1.260724,0.130947,0.343089,1.965752,0.464438,0.118920
2024-09-27,1.397781,0.952864,0.776305,-1.761009,-0.063594,0.642864,-0.048990,-1.092804

**Creating DataFrame**

In [6]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20240922"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "validate", "learn"]),
        "F": "vscode",
    }
)


df2

     A          B    C  D         E       F
0  1.0 2024-09-22  1.0  3      test  vscode
1  1.0 2024-09-22  1.0  3     train  vscode
2  1.0 2024-09-22  1.0  3  validate  vscode
3  1.0 2024-09-22  1.0  3     learn  vscode

**dtypes function**

In [7]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

**Viewing Data**

**DataFrame.head() and DataFrame.tail() functions**

In [8]:
df.head()

,A,B,C,D,E,F,G,H
2024-09-22,-2.587580,-0.866165,-0.091086,1.417251,1.265756,-0.326515,-0.915992,0.478045
2024-09-23,0.720657,-0.308635,-0.418017,0.053495,1.979844,-1.004369,-1.913845,0.985929
2024-09-24,0.665081,-0.823307,0.218447,-1.422248,-0.948106,-1.693340,-1.454448,0.377178
2024-09-25,2.159851,-0.215044,2.579014,-0.303183,2.213305,-0.289394,1.641497,-0.594250
2024-09-26,1.042749,0.358631,1.260724,0.130947,0.343089,1.965752,0.464438,0.118920

In [9]:
df.tail(2)

,A,B,C,D,E,F,G,H
2024-09-26,1.042749,0.358631,1.260724,0.130947,0.343089,1.965752,0.464438,0.118920
2024-09-27,1.397781,0.952864,0.776305,-1.761009,-0.063594,0.642864,-0.048990,-1.092804

**DataFrame.index and DataFrame.columns functions**

In [10]:
df.index

DatetimeIndex(['2024-09-22', '2024-09-23', '2024-09-24', '2024-09-25',
               '2024-09-26', '2024-09-27'],
              dtype='datetime64[ns]', freq='D')

In [11]:
df.columns

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'], dtype='object')

**DataFrame.to_numpy() return a NumPy representation of data**

In [12]:
df.to_numpy()

array([[-2.58758028, -0.86616546, -0.09108619,  1.41725135,  1.26575619,
        -0.3265147 , -0.91599243,  0.47804454],
       [ 0.720657  , -0.3086351 , -0.41801683,  0.05349498,  1.9798438 ,
        -1.0043687 , -1.91384549,  0.98592881],
       [ 0.6650815 , -0.82330668,  0.21844651, -1.42224819, -0.94810595,
        -1.69334007, -1.45444818,  0.37717817],
       [ 2.15985133, -0.21504367,  2.57901402, -0.30318321,  2.21330498,
        -0.2893943 ,  1.64149732, -0.59424962],
       [ 1.04274856,  0.35863118,  1.2607241 ,  0.130947  ,  0.34308927,
         1.96575167,  0.46443775,  0.11891967],
       [ 1.39778133,  0.95286395,  0.77630516, -1.7610091 , -0.06359381,
         0.6428645 , -0.04898964, -1.09280354]])

**describe() shows statistic summary of the data**

In [14]:
df.describe()

,A,B,C,D,E,F,G,H
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
mean,0.566423,-0.150276,0.720898,-0.314125,0.798382,-0.117500,-0.371223,0.045503
std,1.639409,0.702943,1.091419,1.153467,1.234246,1.285390,1.319321,0.760515
min,-2.587580,-0.866165,-0.418017,-1.761009,-0.948106,-1.693340,-1.913845,-1.092804
25%,0.678975,-0.694639,-0.013703,-1.142482,0.038077,-0.834905,-1.319834,-0.415957
50%,0.881703,-0.261839,0.497376,-0.124844,0.804423,-0.307955,-0.482491,0.248049
75%,1.309023,0.215212,1.139619,0.111584,1.801322,0.409800,0.336081,0.452828
max,2.159851,0.952864,2.579014,1.417251,2.213305,1.965752,1.641497,0.985929

**df.T shows transpose of data**

In [15]:
df.T

   2024-09-22  2024-09-23  2024-09-24  2024-09-25  2024-09-26  2024-09-27
A   -2.587580    0.720657    0.665081    2.159851    1.042749    1.397781
B   -0.866165   -0.308635   -0.823307   -0.215044    0.358631    0.952864
C   -0.091086   -0.418017    0.218447    2.579014    1.260724    0.776305
D    1.417251    0.053495   -1.422248   -0.303183    0.130947   -1.761009
E    1.265756    1.979844   -0.948106    2.213305    0.343089   -0.063594
F   -0.326515   -1.004369   -1.693340   -0.289394    1.965752    0.642864
G   -0.915992   -1.913845   -1.454448    1.641497    0.464438   -0.048990
H    0.478045    0.985929    0.377178   -0.594250    0.118920   -1.092804

**DataFrame.sort_index() sorts by an axis**

In [16]:
df.sort_index(axis=1, ascending=False)

,H,G,F,E,D,C,B,A
2024-09-22,0.478045,-0.915992,-0.326515,1.265756,1.417251,-0.091086,-0.866165,-2.587580
2024-09-23,0.985929,-1.913845,-1.004369,1.979844,0.053495,-0.418017,-0.308635,0.720657
2024-09-24,0.377178,-1.454448,-1.693340,-0.948106,-1.422248,0.218447,-0.823307,0.665081
2024-09-25,-0.594250,1.641497,-0.289394,2.213305,-0.303183,2.579014,-0.215044,2.159851
2024-09-26,0.118920,0.464438,1.965752,0.343089,0.130947,1.260724,0.358631,1.042749
2024-09-27,-1.092804,-0.048990,0.642864,-0.063594,-1.761009,0.776305,0.952864,1.397781

**DataFrame.sort_values() sorts by values**

In [17]:
df.sort_values(by="G")

,A,B,C,D,E,F,G,H
2024-09-23,0.720657,-0.308635,-0.418017,0.053495,1.979844,-1.004369,-1.913845,0.985929
2024-09-24,0.665081,-0.823307,0.218447,-1.422248,-0.948106,-1.693340,-1.454448,0.377178
2024-09-22,-2.587580,-0.866165,-0.091086,1.417251,1.265756,-0.326515,-0.915992,0.478045
2024-09-27,1.397781,0.952864,0.776305,-1.761009,-0.063594,0.642864,-0.048990,-1.092804
2024-09-26,1.042749,0.358631,1.260724,0.130947,0.343089,1.965752,0.464438,0.118920
2024-09-25,2.159851,-0.215044,2.579014,-0.303183,2.213305,-0.289394,1.641497,-0.594250

**Getitem ([])**

In [18]:
df["A"]

2024-09-22   -2.587580
2024-09-23    0.720657
2024-09-24    0.665081
2024-09-25    2.159851
2024-09-26    1.042749
2024-09-27    1.397781
Freq: D, Name: A, dtype: float64

**slice :**

In [19]:
df[0:2]

,A,B,C,D,E,F,G,H
2024-09-22,-2.587580,-0.866165,-0.091086,1.417251,1.265756,-0.326515,-0.915992,0.478045
2024-09-23,0.720657,-0.308635,-0.418017,0.053495,1.979844,-1.004369,-1.913845,0.985929

**Selection by label**

**DataFrame.loc() or DataFrame.at()**

In [20]:
df.loc[dates[0]]

A   -2.587580
B   -0.866165
C   -0.091086
D    1.417251
E    1.265756
F   -0.326515
G   -0.915992
H    0.478045
Name: 2024-09-22 00:00:00, dtype: float64

In [21]:
df.loc[:, ["A", "B"]]

                   A         B
2024-09-22 -2.587580 -0.866165
2024-09-23  0.720657 -0.308635
2024-09-24  0.665081 -0.823307
2024-09-25  2.159851 -0.215044
2024-09-26  1.042749  0.358631
2024-09-27  1.397781  0.952864

In [22]:
df.loc["20240923":"20240925", ["A", "B"]]

                   A         B
2024-09-23  0.720657 -0.308635
2024-09-24  0.665081 -0.823307
2024-09-25  2.159851 -0.215044

In [23]:
df.loc["20240921":"20240926", ["A", "B"]]

                   A         B
2024-09-22 -2.587580 -0.866165
2024-09-23  0.720657 -0.308635
2024-09-24  0.665081 -0.823307
2024-09-25  2.159851 -0.215044
2024-09-26  1.042749  0.358631

In [24]:
df.loc[dates[0], "G"]

-0.9159924346778767

In [25]:
df.at[dates[0], "H"]

0.47804453712523326

**Selection by position**

**Select via the position of the passed integers**

In [28]:
df.iloc[2]

A    0.665081
B   -0.823307
C    0.218447
D   -1.422248
E   -0.948106
F   -1.693340
G   -1.454448
H    0.377178
Name: 2024-09-24 00:00:00, dtype: float64

In [29]:
df.iloc[3:5, 0:2]

                   A         B
2024-09-25  2.159851 -0.215044
2024-09-26  1.042749  0.358631

In [30]:
df.iloc[[1, 2, 4], [0, 2]]

                   A         C
2024-09-23  0.720657 -0.418017
2024-09-24  0.665081  0.218447
2024-09-26  1.042749  1.260724

**For slicing rows and columns explicitly**

In [31]:
df.iloc[1:3, :]

,A,B,C,D,E,F,G,H
2024-09-23,0.720657,-0.308635,-0.418017,0.053495,1.979844,-1.004369,-1.913845,0.985929
2024-09-24,0.665081,-0.823307,0.218447,-1.422248,-0.948106,-1.693340,-1.454448,0.377178

In [32]:
df.iloc[:, 1:3]

                   B         C
2024-09-22 -0.866165 -0.091086
2024-09-23 -0.308635 -0.418017
2024-09-24 -0.823307  0.218447
2024-09-25 -0.215044  2.579014
2024-09-26  0.358631  1.260724
2024-09-27  0.952864  0.776305

In [33]:
df.iloc[1, 1]

-0.3086351021216343

In [34]:
df.iat[1, 1]

-0.3086351021216343

**Boolean indexing**

In [36]:
df[df["H"] > 0]

,A,B,C,D,E,F,G,H
2024-09-22,-2.587580,-0.866165,-0.091086,1.417251,1.265756,-0.326515,-0.915992,0.478045
2024-09-23,0.720657,-0.308635,-0.418017,0.053495,1.979844,-1.004369,-1.913845,0.985929
2024-09-24,0.665081,-0.823307,0.218447,-1.422248,-0.948106,-1.693340,-1.454448,0.377178
2024-09-26,1.042749,0.358631,1.260724,0.130947,0.343089,1.965752,0.464438,0.118920

In [37]:
df[df > 0]

,A,B,C,D,E,F,G,H
2024-09-22,NaN,NaN,NaN,1.417251,1.265756,NaN,NaN,0.478045
2024-09-23,0.720657,NaN,NaN,0.053495,1.979844,NaN,NaN,0.985929
2024-09-24,0.665081,NaN,0.218447,NaN,NaN,NaN,NaN,0.377178
2024-09-25,2.159851,NaN,2.579014,NaN,2.213305,NaN,1.641497,NaN
2024-09-26,1.042749,0.358631,1.260724,0.130947,0.343089,1.965752,0.464438,0.118920
2024-09-27,1.397781,0.952864,0.776305,NaN,NaN,0.642864,NaN,NaN

**Using isin() method for filtering:**

In [38]:
df2 = df.copy()

df2["E"] = ["one", "one", "two", "three", "four", "three"]

df2

,A,B,C,D,E,F,G,H
2024-09-22,-2.587580,-0.866165,-0.091086,1.417251,one,-0.326515,-0.915992,0.478045
2024-09-23,0.720657,-0.308635,-0.418017,0.053495,one,-1.004369,-1.913845,0.985929
2024-09-24,0.665081,-0.823307,0.218447,-1.422248,two,-1.693340,-1.454448,0.377178
2024-09-25,2.159851,-0.215044,2.579014,-0.303183,three,-0.289394,1.641497,-0.594250
2024-09-26,1.042749,0.358631,1.260724,0.130947,four,1.965752,0.464438,0.118920
2024-09-27,1.397781,0.952864,0.776305,-1.761009,three,0.642864,-0.048990,-1.092804

In [39]:

df2[df2["E"].isin(["one", "four"])]

,A,B,C,D,E,F,G,H
2024-09-22,-2.587580,-0.866165,-0.091086,1.417251,one,-0.326515,-0.915992,0.478045
2024-09-23,0.720657,-0.308635,-0.418017,0.053495,one,-1.004369,-1.913845,0.985929
2024-09-26,1.042749,0.358631,1.260724,0.130947,four,1.965752,0.464438,0.118920

**Setting**

In [45]:
s1 = pd.Series([1, 2, 3, 4, 5, 6,7,8], index=pd.date_range("20240922", periods=8))

s1

2024-09-22    1
2024-09-23    2
2024-09-24    3
2024-09-25    4
2024-09-26    5
2024-09-27    6
2024-09-28    7
2024-09-29    8
Freq: D, dtype: int64

In [46]:
df.at[dates[0], "A"] = 0

In [47]:
df.iat[0, 1] = 0

In [48]:
df.loc[:, "D"] = np.array([5] * len(df))

In [49]:
df

,A,B,C,D,E,F,G,H
2024-09-22,0.000000,0.000000,-0.091086,5.0,1.265756,-0.326515,-0.915992,0.478045
2024-09-23,0.720657,-0.308635,-0.418017,5.0,1.979844,-1.004369,-1.913845,0.985929
2024-09-24,0.665081,-0.823307,0.218447,5.0,-0.948106,-1.693340,-1.454448,0.377178
2024-09-25,2.159851,-0.215044,2.579014,5.0,2.213305,-0.289394,1.641497,-0.594250
2024-09-26,1.042749,0.358631,1.260724,5.0,0.343089,1.965752,0.464438,0.118920
2024-09-27,1.397781,0.952864,0.776305,5.0,-0.063594,0.642864,-0.048990,-1.092804

In [50]:
df2 = df.copy()

df2[df2 > 0] = -df2

df2

,A,B,C,D,E,F,G,H
2024-09-22,0.000000,0.000000,-0.091086,-5.0,-1.265756,-0.326515,-0.915992,-0.478045
2024-09-23,-0.720657,-0.308635,-0.418017,-5.0,-1.979844,-1.004369,-1.913845,-0.985929
2024-09-24,-0.665081,-0.823307,-0.218447,-5.0,-0.948106,-1.693340,-1.454448,-0.377178
2024-09-25,-2.159851,-0.215044,-2.579014,-5.0,-2.213305,-0.289394,-1.641497,-0.594250
2024-09-26,-1.042749,-0.358631,-1.260724,-5.0,-0.343089,-1.965752,-0.464438,-0.118920
2024-09-27,-1.397781,-0.952864,-0.776305,-5.0,-0.063594,-0.642864,-0.048990,-1.092804

**Missing data**

**Reindexing allows you to change/add/delete the index on a specified axis. This returns a copy of the data:**

In [51]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])

df1.loc[dates[0] : dates[1], "E"] = 1

df1

,A,B,C,D,E,F,G,H,E
2024-09-22,0.000000,0.000000,-0.091086,5.0,1.000000,-0.326515,-0.915992,0.478045,1.000000
2024-09-23,0.720657,-0.308635,-0.418017,5.0,1.000000,-1.004369,-1.913845,0.985929,1.000000
2024-09-24,0.665081,-0.823307,0.218447,5.0,-0.948106,-1.693340,-1.454448,0.377178,-0.948106
2024-09-25,2.159851,-0.215044,2.579014,5.0,2.213305,-0.289394,1.641497,-0.594250,2.213305

**DataFrame.dropna() drops any rows that have missing data:**

In [52]:
df1.dropna(how="any")

,A,B,C,D,E,F,G,H,E
2024-09-22,0.000000,0.000000,-0.091086,5.0,1.000000,-0.326515,-0.915992,0.478045,1.000000
2024-09-23,0.720657,-0.308635,-0.418017,5.0,1.000000,-1.004369,-1.913845,0.985929,1.000000
2024-09-24,0.665081,-0.823307,0.218447,5.0,-0.948106,-1.693340,-1.454448,0.377178,-0.948106
2024-09-25,2.159851,-0.215044,2.579014,5.0,2.213305,-0.289394,1.641497,-0.594250,2.213305

**DataFrame.fillna() fills missing data:**

In [53]:
df1.fillna(value=5)

,A,B,C,D,E,F,G,H,E
2024-09-22,0.000000,0.000000,-0.091086,5.0,1.000000,-0.326515,-0.915992,0.478045,1.000000
2024-09-23,0.720657,-0.308635,-0.418017,5.0,1.000000,-1.004369,-1.913845,0.985929,1.000000
2024-09-24,0.665081,-0.823307,0.218447,5.0,-0.948106,-1.693340,-1.454448,0.377178,-0.948106
2024-09-25,2.159851,-0.215044,2.579014,5.0,2.213305,-0.289394,1.641497,-0.594250,2.213305

**isna() gets the boolean mask where values are nan**

In [54]:
pd.isna(df1)

                A      B      C      D      E      F      G      H      E
2024-09-22  False  False  False  False  False  False  False  False  False
2024-09-23  False  False  False  False  False  False  False  False  False
2024-09-24  False  False  False  False  False  False  False  False  False
2024-09-25  False  False  False  False  False  False  False  False  False

**Operations**

**Stats**

In [55]:
df.mean()

A    0.997687
B   -0.005915
C    0.720898
D    5.000000
E    0.798382
F   -0.117500
G   -0.371223
H    0.045503
dtype: float64

**mean value for each row**

In [57]:
df.mean(axis=1)

2024-09-22    0.676276
2024-09-23    0.630195
2024-09-24    0.167688
2024-09-25    1.561873
2024-09-26    1.319288
2024-09-27    0.945553
Freq: D, dtype: float64

In [58]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(2)

s

2024-09-22    NaN
2024-09-23    NaN
2024-09-24    1.0
2024-09-25    3.0
2024-09-26    5.0
2024-09-27    NaN
Freq: D, dtype: float64

In [59]:
df.sub(s, axis="index")

,A,B,C,D,E,F,G,H
2024-09-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09-24,-0.334919,-1.823307,-0.781553,4.0,-1.948106,-2.693340,-2.454448,-0.622822
2024-09-25,-0.840149,-3.215044,-0.420986,2.0,-0.786695,-3.289394,-1.358503,-3.594250
2024-09-26,-3.957251,-4.641369,-3.739276,0.0,-4.656911,-3.034248,-4.535562,-4.881080
2024-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**User defined functions**

In [60]:
df.agg(lambda x: np.mean(x) * 5.6)

A     5.587045
B    -0.033124
C     4.037028
D    28.000000
E     4.470942
F    -0.658002
G    -2.078851
H     0.254817
dtype: float64

In [61]:
df.transform(lambda x: x * 101.2)

,A,B,C,D,E,F,G,H
2024-09-22,0.000000,0.000000,-9.217922,506.0,128.094527,-33.043288,-92.698434,48.378107
2024-09-23,72.930489,-31.233872,-42.303303,506.0,200.360193,-101.642112,-193.681164,99.775995
2024-09-24,67.306248,-83.318636,22.106786,506.0,-95.948322,-171.366015,-147.190155,38.170431
2024-09-25,218.576954,-21.762420,260.996219,506.0,223.986464,-29.286703,166.119529,-60.138061
2024-09-26,105.526154,36.293475,127.585278,506.0,34.720634,198.934069,47.001100,12.034670
2024-09-27,141.455471,96.429832,78.562083,506.0,-6.435694,65.057887,-4.957752,-110.591718

**Value Counts**

In [62]:
s = pd.Series(np.random.randint(0, 7, size=10))

s

0    5
1    4
2    3
3    0
4    4
5    4
6    4
7    6
8    0
9    2
dtype: int32

In [63]:
s.value_counts()

4    4
0    2
5    1
3    1
6    1
2    1
Name: count, dtype: int64

**String Methods**

In [64]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])

s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

**Merge & Concat**

In [65]:
df = pd.DataFrame(np.random.randn(10, 4))

df

          0         1         2         3
0 -0.770725 -1.238230 -0.196997 -0.016436
1  1.158753 -0.481247 -0.004599 -1.406593
2 -0.475438  0.835971  0.213976 -0.086096
3  1.077574 -1.672812  0.942742 -1.754009
4 -1.736180  0.496556  1.654513  1.197242
5 -1.628297  0.916818 -1.602364  1.444602
6 -0.067920  2.435181 -1.183597 -1.721171
7  0.601469  2.178759  0.069097  0.236265
8  0.046575 -0.116815 -3.038570  0.167898
9  0.053628 -0.499503  1.100086 -1.427785

In [66]:
pieces = [df[:3], df[3:7], df[7:]]

pd.concat(pieces)

          0         1         2         3
0 -0.770725 -1.238230 -0.196997 -0.016436
1  1.158753 -0.481247 -0.004599 -1.406593
2 -0.475438  0.835971  0.213976 -0.086096
3  1.077574 -1.672812  0.942742 -1.754009
4 -1.736180  0.496556  1.654513  1.197242
5 -1.628297  0.916818 -1.602364  1.444602
6 -0.067920  2.435181 -1.183597 -1.721171
7  0.601469  2.178759  0.069097  0.236265
8  0.046575 -0.116815 -3.038570  0.167898
9  0.053628 -0.499503  1.100086 -1.427785

**Join**

In [68]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})

right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})

left

   key  lval
0  foo     1
1  foo     2

In [69]:
right

   key  rval
0  foo     4
1  foo     5

In [70]:
pd.merge(left, right, on="key")

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [71]:
left = pd.DataFrame({"key": ["foo", "bar"], "lval": [1, 2]})

right = pd.DataFrame({"key": ["foo", "bar"], "rval": [4, 5]})

left

   key  lval
0  foo     1
1  bar     2

In [72]:
pd.merge(left, right, on="key")

   key  lval  rval
0  foo     1     4
1  bar     2     5

**Grouping**

**By “group by” we are referring to a process involving one or more of the steps**

In [73]:
df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)


df

     A      B         C         D
0  foo    one  2.022595  0.296864
1  bar    one -0.486775 -1.688209
2  foo    two  1.745907 -1.506983
3  bar  three  1.723114 -1.328455
4  foo    two  0.255083 -2.234914
5  bar    two -1.438541  1.333447
6  foo    one  0.517092 -1.394673
7  foo  three -1.410233  0.893571

In [75]:
df.groupby("A")[["C", "D"]].sum()

            C         D
A
bar -0.202201 -1.683217
foo  3.130444 -3.946134

In [76]:
df.groupby(["A", "B"]).sum()

                  C         D
A   B
bar one   -0.486775 -1.688209
    three  1.723114 -1.328455
    two   -1.438541  1.333447
foo one    2.539687 -1.097809
    three -1.410233  0.893571
    two    2.000990 -3.741896

**Reshaping**

**Stack**

In [77]:
arrays = [
   ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
   ["one", "two", "one", "two", "one", "two", "one", "two"],
]


index = pd.MultiIndex.from_arrays(arrays, names=["first", "second"])

df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=["A", "B"])

df2 = df[:4]

df2

                     A         B
first second
bar   one    -0.083248  0.093120
      two     0.624937 -0.669245
baz   one    -0.235723  1.408812
      two     0.848367 -1.185225

In [78]:
stacked = df2.stack(future_stack=True)

stacked

first  second
bar    one     A   -0.083248
               B    0.093120
       two     A    0.624937
               B   -0.669245
baz    one     A   -0.235723
               B    1.408812
       two     A    0.848367
               B   -1.185225
dtype: float64

In [79]:
stacked.unstack()

                     A         B
first second
bar   one    -0.083248  0.093120
      two     0.624937 -0.669245
baz   one    -0.235723  1.408812
      two     0.848367 -1.185225

**Pivot tables**

In [80]:
df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
    }
)


df

        A  B    C         D         E
0     one  A  foo -0.119389  0.242053
1     one  B  foo  0.131907 -0.741443
2     two  C  foo -0.594507  1.020484
3   three  A  bar  0.029448 -0.757808
4     one  B  bar -1.338517  1.018810
5     one  C  bar -0.572102  0.150183
6     two  A  foo  0.555468 -1.223824
7   three  B  foo  0.114432  1.744572
8     one  C  foo -1.870355  0.446763
9     one  A  bar -0.773705  0.318060
10    two  B  bar  1.246318 -1.222795
11  three  C  bar  0.777738  0.446484

**Time series**

In [81]:
rng = pd.date_range("1/1/2012", periods=100, freq="s")

ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

ts.resample("5Min").sum()

2012-01-01    23769
Freq: 5T, dtype: int32

**Categorical**

In [82]:
df = pd.DataFrame(
    {"id": [1, 2, 3, 4, 5, 6], "raw_grade": ["a", "b", "b", "a", "a", "e"]}
)

In [83]:
df["grade"] = df["raw_grade"].astype("category")

df["grade"]

0    a
1    b
2    b
3    a
4    a
5    e
Name: grade, dtype: category
Categories (3, object): ['a', 'b', 'e']

In [84]:
df["grade"] = df["grade"].cat.set_categories(
    ["very bad", "bad", "medium", "good", "very good"]
)


df["grade"]

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
Name: grade, dtype: category
Categories (5, object): ['very bad', 'bad', 'medium', 'good', 'very good']

In [85]:
df.sort_values(by="grade")

   id raw_grade grade
0   1         a   NaN
1   2         b   NaN
2   3         b   NaN
3   4         a   NaN
4   5         a   NaN
5   6         e   NaN

In [86]:
df.groupby("grade", observed=False).size()

grade
very bad     0
bad          0
medium       0
good         0
very good    0
dtype: int64