### Name: Neha Izhar
#### Email: nehaizhar123@gmail.com

### Importing libraries

In [4]:
import pandas as pd

In [5]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

### 1. Importing Dataframe

In [6]:
t=pd.read_excel("employee.xlsx")
t

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
0,Amna,36,Master,5 years,12365879,abc@gmail.com,23548972,abc,45000
1,Ayesha,25,BS,2 years,3654897,vhzg@gmail.com,69874236,efg,25000
2,Komal,45,PHD,10 years,12551225,nsj@gmail.com,69842369,hij,60000
3,Kainat,32,BS,6 years,36589712,mjhg@gmail.com,55845522,klm,30000
4,Isma,22,BS,0 years,365426855,vgh@gmail.com,98723654,nop,20000
5,Sawera,41,MS,8 years,9842568,ksj@gmail.com,87456321,qrs,50000
6,Zahra,26,Master,1 years,514789,lsk@gmail.com,35478921,tuv,33000
7,Noor Fatima,33,MS,5 years,3654897,mns@gamil.com,3654789,wxy,40000
8,Kanwal,27,BS,2 years,7456695,lsk@gmail.com,9874563,zab,28000
9,Shaista,42,PHD,12 years,3654789,ksk@gmail.com,2589631,cde,36000
10,Saira,36,Master,4 years,87453216,oia@gmail.com,7412589,fgh,45000
11,Hoorain,28,Master,2.7 years,254987,bhsh@gmail.com,85214796,ijk,22000
12,Nabila,39,BS,7 years,4569873,qwer@gamil.com,564123987,lmn,33000
13,Nazia,44,PHD,11 years,32147895,fisa@gmail.com,13698752,opq,20000
14,Aneeqa,32,Master,1 years,77789546,mjd@gmail.com,36987333,rst,31000
15,Asifa,25,BS,3 years,36547888,lak@gmail.com,966654782,uvw,44000
16,Nabiha,36,BS,6 years,98741222,djn@gmail.com,7852235,xyz,55000
17,Neelam,45,BS,15 years,369874521,kaj@gmail.com,36987222,abh,23000
18,Hibba,30,Master,1.5 years,235478,nlm@gmail.com,789214666,opl,34000
19,Hania,24,Master,0 years,333222555,yui@gmail.com,25899963,mny,35000
20,Umaima,23,BS,0.5 years,4782415,mno@gmail.com,14788547,kji,26000

### 2. Datatype Function

In [8]:
t.dtypes

Name of Employee    object
Age                  int64
Qulification        object
Experience          object
Phone No             int64
E-mail              object
CNIC No              int64
Address             object
Salary               int64
dtype: object

### 3. Access specific Column Function

In [10]:
t.Age

0     36
1     25
2     45
3     32
4     22
5     41
6     26
7     33
8     27
9     42
10    36
11    28
12    39
13    44
14    32
15    25
16    36
17    45
18    30
19    24
20    23
Name: Age, dtype: int64

### 4. Bool Function

In [13]:
t.bool

<bound method NDFrame.bool of    Name of Employee  Age Qulification Experience   Phone No          E-mail  \
0              Amna   36       Master    5 years   12365879   abc@gmail.com
1            Ayesha   25           BS    2 years    3654897  vhzg@gmail.com
2             Komal   45          PHD   10 years   12551225   nsj@gmail.com
3            Kainat   32           BS    6 years   36589712  mjhg@gmail.com
4              Isma   22           BS    0 years  365426855   vgh@gmail.com
5            Sawera   41           MS    8 years    9842568   ksj@gmail.com
6             Zahra   26       Master    1 years     514789   lsk@gmail.com
7       Noor Fatima   33           MS    5 years    3654897   mns@gamil.com
8            Kanwal   27           BS    2 years    7456695   lsk@gmail.com
9           Shaista   42          PHD   12 years    3654789   ksk@gmail.com
10            Saira   36       Master    4 years   87453216   oia@gmail.com
11          Hoorain   28       Master  2.7 years     254987  bhsh@gmail.com
12           Nabila   39           BS    7 years    4569873  qwer@gamil.com
13            Nazia   44          PHD   11 years   32147895  fisa@gmail.com
14           Aneeqa   32       Master    1 years   77789546   mjd@gmail.com
15            Asifa   25           BS    3 years   36547888   lak@gmail.com
16           Nabiha   36           BS    6 years   98741222   djn@gmail.com
17           Neelam   45           BS   15 years  369874521   kaj@gmail.com
18            Hibba   30       Master  1.5 years     235478   nlm@gmail.com
19            Hania   24       Master    0 years  333222555   yui@gmail.com
20           Umaima   23           BS  0.5 years    4782415   mno@gmail.com

      CNIC No Address  Salary
0    23548972     abc   45000
1    69874236     efg   25000
2    69842369     hij   60000
3    55845522     klm   30000
4    98723654     nop   20000
5    87456321     qrs   50000
6    35478921     tuv   33000
7     3654789     wxy   40000
8     9874563     zab   28000
9     2589631     cde   36000
10    7412589     fgh   45000
11   85214796     ijk   22000
12  564123987     lmn   33000
13   13698752     opq   20000
14   36987333     rst   31000
15  966654782     uvw   44000
16    7852235     xyz   55000
17   36987222     abh   23000
18  789214666     opl   34000
19   25899963     mny   35000
20   14788547     kji   26000  >

### 5. Absolute Function

In [15]:
t.abs

<bound method NDFrame.abs of    Name of Employee  Age Qulification Experience   Phone No          E-mail  \
0              Amna   36       Master    5 years   12365879   abc@gmail.com
1            Ayesha   25           BS    2 years    3654897  vhzg@gmail.com
2             Komal   45          PHD   10 years   12551225   nsj@gmail.com
3            Kainat   32           BS    6 years   36589712  mjhg@gmail.com
4              Isma   22           BS    0 years  365426855   vgh@gmail.com
5            Sawera   41           MS    8 years    9842568   ksj@gmail.com
6             Zahra   26       Master    1 years     514789   lsk@gmail.com
7       Noor Fatima   33           MS    5 years    3654897   mns@gamil.com
8            Kanwal   27           BS    2 years    7456695   lsk@gmail.com
9           Shaista   42          PHD   12 years    3654789   ksk@gmail.com
10            Saira   36       Master    4 years   87453216   oia@gmail.com
11          Hoorain   28       Master  2.7 years     254987  bhsh@gmail.com
12           Nabila   39           BS    7 years    4569873  qwer@gamil.com
13            Nazia   44          PHD   11 years   32147895  fisa@gmail.com
14           Aneeqa   32       Master    1 years   77789546   mjd@gmail.com
15            Asifa   25           BS    3 years   36547888   lak@gmail.com
16           Nabiha   36           BS    6 years   98741222   djn@gmail.com
17           Neelam   45           BS   15 years  369874521   kaj@gmail.com
18            Hibba   30       Master  1.5 years     235478   nlm@gmail.com
19            Hania   24       Master    0 years  333222555   yui@gmail.com
20           Umaima   23           BS  0.5 years    4782415   mno@gmail.com

      CNIC No Address  Salary
0    23548972     abc   45000
1    69874236     efg   25000
2    69842369     hij   60000
3    55845522     klm   30000
4    98723654     nop   20000
5    87456321     qrs   50000
6    35478921     tuv   33000
7     3654789     wxy   40000
8     9874563     zab   28000
9     2589631     cde   36000
10    7412589     fgh   45000
11   85214796     ijk   22000
12  564123987     lmn   33000
13   13698752     opq   20000
14   36987333     rst   31000
15  966654782     uvw   44000
16    7852235     xyz   55000
17   36987222     abh   23000
18  789214666     opl   34000
19   25899963     mny   35000
20   14788547     kji   26000  >

### 6. Boxplot Function

In [16]:
t.boxplot

<bound method boxplot_frame of    Name of Employee  Age Qulification Experience   Phone No          E-mail  \
0              Amna   36       Master    5 years   12365879   abc@gmail.com
1            Ayesha   25           BS    2 years    3654897  vhzg@gmail.com
2             Komal   45          PHD   10 years   12551225   nsj@gmail.com
3            Kainat   32           BS    6 years   36589712  mjhg@gmail.com
4              Isma   22           BS    0 years  365426855   vgh@gmail.com
5            Sawera   41           MS    8 years    9842568   ksj@gmail.com
6             Zahra   26       Master    1 years     514789   lsk@gmail.com
7       Noor Fatima   33           MS    5 years    3654897   mns@gamil.com
8            Kanwal   27           BS    2 years    7456695   lsk@gmail.com
9           Shaista   42          PHD   12 years    3654789   ksk@gmail.com
10            Saira   36       Master    4 years   87453216   oia@gmail.com
11          Hoorain   28       Master  2.7 years     254987  bhsh@gmail.com
12           Nabila   39           BS    7 years    4569873  qwer@gamil.com
13            Nazia   44          PHD   11 years   32147895  fisa@gmail.com
14           Aneeqa   32       Master    1 years   77789546   mjd@gmail.com
15            Asifa   25           BS    3 years   36547888   lak@gmail.com
16           Nabiha   36           BS    6 years   98741222   djn@gmail.com
17           Neelam   45           BS   15 years  369874521   kaj@gmail.com
18            Hibba   30       Master  1.5 years     235478   nlm@gmail.com
19            Hania   24       Master    0 years  333222555   yui@gmail.com
20           Umaima   23           BS  0.5 years    4782415   mno@gmail.com

      CNIC No Address  Salary
0    23548972     abc   45000
1    69874236     efg   25000
2    69842369     hij   60000
3    55845522     klm   30000
4    98723654     nop   20000
5    87456321     qrs   50000
6    35478921     tuv   33000
7     3654789     wxy   40000
8     9874563     zab   28000
9     2589631     cde   36000
10    7412589     fgh   45000
11   85214796     ijk   22000
12  564123987     lmn   33000
13   13698752     opq   20000
14   36987333     rst   31000
15  966654782     uvw   44000
16    7852235     xyz   55000
17   36987222     abh   23000
18  789214666     opl   34000
19   25899963     mny   35000
20   14788547     kji   26000  >

### 7. Add Function

In [18]:
t.add

<bound method DataFrame.add of    Name of Employee  Age Qulification Experience   Phone No          E-mail  \
0              Amna   36       Master    5 years   12365879   abc@gmail.com
1            Ayesha   25           BS    2 years    3654897  vhzg@gmail.com
2             Komal   45          PHD   10 years   12551225   nsj@gmail.com
3            Kainat   32           BS    6 years   36589712  mjhg@gmail.com
4              Isma   22           BS    0 years  365426855   vgh@gmail.com
5            Sawera   41           MS    8 years    9842568   ksj@gmail.com
6             Zahra   26       Master    1 years     514789   lsk@gmail.com
7       Noor Fatima   33           MS    5 years    3654897   mns@gamil.com
8            Kanwal   27           BS    2 years    7456695   lsk@gmail.com
9           Shaista   42          PHD   12 years    3654789   ksk@gmail.com
10            Saira   36       Master    4 years   87453216   oia@gmail.com
11          Hoorain   28       Master  2.7 years     254987  bhsh@gmail.com
12           Nabila   39           BS    7 years    4569873  qwer@gamil.com
13            Nazia   44          PHD   11 years   32147895  fisa@gmail.com
14           Aneeqa   32       Master    1 years   77789546   mjd@gmail.com
15            Asifa   25           BS    3 years   36547888   lak@gmail.com
16           Nabiha   36           BS    6 years   98741222   djn@gmail.com
17           Neelam   45           BS   15 years  369874521   kaj@gmail.com
18            Hibba   30       Master  1.5 years     235478   nlm@gmail.com
19            Hania   24       Master    0 years  333222555   yui@gmail.com
20           Umaima   23           BS  0.5 years    4782415   mno@gmail.com

      CNIC No Address  Salary
0    23548972     abc   45000
1    69874236     efg   25000
2    69842369     hij   60000
3    55845522     klm   30000
4    98723654     nop   20000
5    87456321     qrs   50000
6    35478921     tuv   33000
7     3654789     wxy   40000
8     9874563     zab   28000
9     2589631     cde   36000
10    7412589     fgh   45000
11   85214796     ijk   22000
12  564123987     lmn   33000
13   13698752     opq   20000
14   36987333     rst   31000
15  966654782     uvw   44000
16    7852235     xyz   55000
17   36987222     abh   23000
18  789214666     opl   34000
19   25899963     mny   35000
20   14788547     kji   26000  >

### 8. Column Accesser Function

In [20]:
t.Salary

0     45000
1     25000
2     60000
3     30000
4     20000
5     50000
6     33000
7     40000
8     28000
9     36000
10    45000
11    22000
12    33000
13    20000
14    31000
15    44000
16    55000
17    23000
18    34000
19    35000
20    26000
Name: Salary, dtype: int64

### 9. Add_Prefix Function

In [21]:
t.add_prefix("range_")

,range_Name of Employee,range_Age,range_Qulification,range_Experience,range_Phone No,range_E-mail,range_CNIC No,range_Address,range_Salary
0,Amna,36,Master,5 years,12365879,abc@gmail.com,23548972,abc,45000
1,Ayesha,25,BS,2 years,3654897,vhzg@gmail.com,69874236,efg,25000
2,Komal,45,PHD,10 years,12551225,nsj@gmail.com,69842369,hij,60000
3,Kainat,32,BS,6 years,36589712,mjhg@gmail.com,55845522,klm,30000
4,Isma,22,BS,0 years,365426855,vgh@gmail.com,98723654,nop,20000
5,Sawera,41,MS,8 years,9842568,ksj@gmail.com,87456321,qrs,50000
6,Zahra,26,Master,1 years,514789,lsk@gmail.com,35478921,tuv,33000
7,Noor Fatima,33,MS,5 years,3654897,mns@gamil.com,3654789,wxy,40000
8,Kanwal,27,BS,2 years,7456695,lsk@gmail.com,9874563,zab,28000
9,Shaista,42,PHD,12 years,3654789,ksk@gmail.com,2589631,cde,36000
10,Saira,36,Master,4 years,87453216,oia@gmail.com,7412589,fgh,45000
11,Hoorain,28,Master,2.7 years,254987,bhsh@gmail.com,85214796,ijk,22000
12,Nabila,39,BS,7 years,4569873,qwer@gamil.com,564123987,lmn,33000
13,Nazia,44,PHD,11 years,32147895,fisa@gmail.com,13698752,opq,20000
14,Aneeqa,32,Master,1 years,77789546,mjd@gmail.com,36987333,rst,31000
15,Asifa,25,BS,3 years,36547888,lak@gmail.com,966654782,uvw,44000
16,Nabiha,36,BS,6 years,98741222,djn@gmail.com,7852235,xyz,55000
17,Neelam,45,BS,15 years,369874521,kaj@gmail.com,36987222,abh,23000
18,Hibba,30,Master,1.5 years,235478,nlm@gmail.com,789214666,opl,34000
19,Hania,24,Master,0 years,333222555,yui@gmail.com,25899963,mny,35000
20,Umaima,23,BS,0.5 years,4782415,mno@gmail.com,14788547,kji,26000

### 10. Add_Suffix Function

In [22]:
t.add_suffix("_range")

,Name of Employee_range,Age_range,Qulification_range,Experience_range,Phone No_range,E-mail_range,CNIC No_range,Address_range,Salary_range
0,Amna,36,Master,5 years,12365879,abc@gmail.com,23548972,abc,45000
1,Ayesha,25,BS,2 years,3654897,vhzg@gmail.com,69874236,efg,25000
2,Komal,45,PHD,10 years,12551225,nsj@gmail.com,69842369,hij,60000
3,Kainat,32,BS,6 years,36589712,mjhg@gmail.com,55845522,klm,30000
4,Isma,22,BS,0 years,365426855,vgh@gmail.com,98723654,nop,20000
5,Sawera,41,MS,8 years,9842568,ksj@gmail.com,87456321,qrs,50000
6,Zahra,26,Master,1 years,514789,lsk@gmail.com,35478921,tuv,33000
7,Noor Fatima,33,MS,5 years,3654897,mns@gamil.com,3654789,wxy,40000
8,Kanwal,27,BS,2 years,7456695,lsk@gmail.com,9874563,zab,28000
9,Shaista,42,PHD,12 years,3654789,ksk@gmail.com,2589631,cde,36000
10,Saira,36,Master,4 years,87453216,oia@gmail.com,7412589,fgh,45000
11,Hoorain,28,Master,2.7 years,254987,bhsh@gmail.com,85214796,ijk,22000
12,Nabila,39,BS,7 years,4569873,qwer@gamil.com,564123987,lmn,33000
13,Nazia,44,PHD,11 years,32147895,fisa@gmail.com,13698752,opq,20000
14,Aneeqa,32,Master,1 years,77789546,mjd@gmail.com,36987333,rst,31000
15,Asifa,25,BS,3 years,36547888,lak@gmail.com,966654782,uvw,44000
16,Nabiha,36,BS,6 years,98741222,djn@gmail.com,7852235,xyz,55000
17,Neelam,45,BS,15 years,369874521,kaj@gmail.com,36987222,abh,23000
18,Hibba,30,Master,1.5 years,235478,nlm@gmail.com,789214666,opl,34000
19,Hania,24,Master,0 years,333222555,yui@gmail.com,25899963,mny,35000
20,Umaima,23,BS,0.5 years,4782415,mno@gmail.com,14788547,kji,26000

### 11. Clip Function

In [25]:
t.clip(22000,26)

TypeError: '>=' not supported between instances of 'str' and 'int'

### 12. Column Function

In [27]:
t.columns

Index(['Name of Employee', 'Age', 'Qulification', 'Experience', 'Phone No',
       'E-mail', 'CNIC No', 'Address', 'Salary'],
      dtype='object')

### 13. Align Function

In [29]:
t.align

<bound method NDFrame.align of    Name of Employee  Age Qulification Experience   Phone No          E-mail  \
0              Amna   36       Master    5 years   12365879   abc@gmail.com
1            Ayesha   25           BS    2 years    3654897  vhzg@gmail.com
2             Komal   45          PHD   10 years   12551225   nsj@gmail.com
3            Kainat   32           BS    6 years   36589712  mjhg@gmail.com
4              Isma   22           BS    0 years  365426855   vgh@gmail.com
5            Sawera   41           MS    8 years    9842568   ksj@gmail.com
6             Zahra   26       Master    1 years     514789   lsk@gmail.com
7       Noor Fatima   33           MS    5 years    3654897   mns@gamil.com
8            Kanwal   27           BS    2 years    7456695   lsk@gmail.com
9           Shaista   42          PHD   12 years    3654789   ksk@gmail.com
10            Saira   36       Master    4 years   87453216   oia@gmail.com
11          Hoorain   28       Master  2.7 years     254987  bhsh@gmail.com
12           Nabila   39           BS    7 years    4569873  qwer@gamil.com
13            Nazia   44          PHD   11 years   32147895  fisa@gmail.com
14           Aneeqa   32       Master    1 years   77789546   mjd@gmail.com
15            Asifa   25           BS    3 years   36547888   lak@gmail.com
16           Nabiha   36           BS    6 years   98741222   djn@gmail.com
17           Neelam   45           BS   15 years  369874521   kaj@gmail.com
18            Hibba   30       Master  1.5 years     235478   nlm@gmail.com
19            Hania   24       Master    0 years  333222555   yui@gmail.com
20           Umaima   23           BS  0.5 years    4782415   mno@gmail.com

      CNIC No Address  Salary
0    23548972     abc   45000
1    69874236     efg   25000
2    69842369     hij   60000
3    55845522     klm   30000
4    98723654     nop   20000
5    87456321     qrs   50000
6    35478921     tuv   33000
7     3654789     wxy   40000
8     9874563     zab   28000
9     2589631     cde   36000
10    7412589     fgh   45000
11   85214796     ijk   22000
12  564123987     lmn   33000
13   13698752     opq   20000
14   36987333     rst   31000
15  966654782     uvw   44000
16    7852235     xyz   55000
17   36987222     abh   23000
18  789214666     opl   34000
19   25899963     mny   35000
20   14788547     kji   26000  >

### 14. Copy Function

In [31]:
s=t.copy()
s

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
0,Amna,36,Master,5 years,12365879,abc@gmail.com,23548972,abc,45000
1,Ayesha,25,BS,2 years,3654897,vhzg@gmail.com,69874236,efg,25000
2,Komal,45,PHD,10 years,12551225,nsj@gmail.com,69842369,hij,60000
3,Kainat,32,BS,6 years,36589712,mjhg@gmail.com,55845522,klm,30000
4,Isma,22,BS,0 years,365426855,vgh@gmail.com,98723654,nop,20000
5,Sawera,41,MS,8 years,9842568,ksj@gmail.com,87456321,qrs,50000
6,Zahra,26,Master,1 years,514789,lsk@gmail.com,35478921,tuv,33000
7,Noor Fatima,33,MS,5 years,3654897,mns@gamil.com,3654789,wxy,40000
8,Kanwal,27,BS,2 years,7456695,lsk@gmail.com,9874563,zab,28000
9,Shaista,42,PHD,12 years,3654789,ksk@gmail.com,2589631,cde,36000
10,Saira,36,Master,4 years,87453216,oia@gmail.com,7412589,fgh,45000
11,Hoorain,28,Master,2.7 years,254987,bhsh@gmail.com,85214796,ijk,22000
12,Nabila,39,BS,7 years,4569873,qwer@gamil.com,564123987,lmn,33000
13,Nazia,44,PHD,11 years,32147895,fisa@gmail.com,13698752,opq,20000
14,Aneeqa,32,Master,1 years,77789546,mjd@gmail.com,36987333,rst,31000
15,Asifa,25,BS,3 years,36547888,lak@gmail.com,966654782,uvw,44000
16,Nabiha,36,BS,6 years,98741222,djn@gmail.com,7852235,xyz,55000
17,Neelam,45,BS,15 years,369874521,kaj@gmail.com,36987222,abh,23000
18,Hibba,30,Master,1.5 years,235478,nlm@gmail.com,789214666,opl,34000
19,Hania,24,Master,0 years,333222555,yui@gmail.com,25899963,mny,35000
20,Umaima,23,BS,0.5 years,4782415,mno@gmail.com,14788547,kji,26000

### 15. All Function

In [33]:
t.all()

Name of Employee    True
Age                 True
Qulification        True
Experience          True
Phone No            True
E-mail              True
CNIC No             True
Address             True
Salary              True
dtype: bool

###  16. Count Function

In [34]:
t.count()

Name of Employee    21
Age                 21
Qulification        21
Experience          21
Phone No            21
E-mail              21
CNIC No             21
Address             21
Salary              21
dtype: int64

### 17. Any Function

In [35]:
t.any()

Name of Employee    True
Age                 True
Qulification        True
Experience          True
Phone No            True
E-mail              True
CNIC No             True
Address             True
Salary              True
dtype: bool

### 18. Combine Function

In [37]:
t.combine

<bound method DataFrame.combine of    Name of Employee  Age Qulification Experience   Phone No          E-mail  \
0              Amna   36       Master    5 years   12365879   abc@gmail.com
1            Ayesha   25           BS    2 years    3654897  vhzg@gmail.com
2             Komal   45          PHD   10 years   12551225   nsj@gmail.com
3            Kainat   32           BS    6 years   36589712  mjhg@gmail.com
4              Isma   22           BS    0 years  365426855   vgh@gmail.com
5            Sawera   41           MS    8 years    9842568   ksj@gmail.com
6             Zahra   26       Master    1 years     514789   lsk@gmail.com
7       Noor Fatima   33           MS    5 years    3654897   mns@gamil.com
8            Kanwal   27           BS    2 years    7456695   lsk@gmail.com
9           Shaista   42          PHD   12 years    3654789   ksk@gmail.com
10            Saira   36       Master    4 years   87453216   oia@gmail.com
11          Hoorain   28       Master  2.7 years     254987  bhsh@gmail.com
12           Nabila   39           BS    7 years    4569873  qwer@gamil.com
13            Nazia   44          PHD   11 years   32147895  fisa@gmail.com
14           Aneeqa   32       Master    1 years   77789546   mjd@gmail.com
15            Asifa   25           BS    3 years   36547888   lak@gmail.com
16           Nabiha   36           BS    6 years   98741222   djn@gmail.com
17           Neelam   45           BS   15 years  369874521   kaj@gmail.com
18            Hibba   30       Master  1.5 years     235478   nlm@gmail.com
19            Hania   24       Master    0 years  333222555   yui@gmail.com
20           Umaima   23           BS  0.5 years    4782415   mno@gmail.com

      CNIC No Address  Salary
0    23548972     abc   45000
1    69874236     efg   25000
2    69842369     hij   60000
3    55845522     klm   30000
4    98723654     nop   20000
5    87456321     qrs   50000
6    35478921     tuv   33000
7     3654789     wxy   40000
8     9874563     zab   28000
9     2589631     cde   36000
10    7412589     fgh   45000
11   85214796     ijk   22000
12  564123987     lmn   33000
13   13698752     opq   20000
14   36987333     rst   31000
15  966654782     uvw   44000
16    7852235     xyz   55000
17   36987222     abh   23000
18  789214666     opl   34000
19   25899963     mny   35000
20   14788547     kji   26000  >

### 19. Apply Function

In [40]:
t.apply

<bound method DataFrame.apply of    Name of Employee  Age Qulification Experience   Phone No          E-mail  \
0              Amna   36       Master    5 years   12365879   abc@gmail.com
1            Ayesha   25           BS    2 years    3654897  vhzg@gmail.com
2             Komal   45          PHD   10 years   12551225   nsj@gmail.com
3            Kainat   32           BS    6 years   36589712  mjhg@gmail.com
4              Isma   22           BS    0 years  365426855   vgh@gmail.com
5            Sawera   41           MS    8 years    9842568   ksj@gmail.com
6             Zahra   26       Master    1 years     514789   lsk@gmail.com
7       Noor Fatima   33           MS    5 years    3654897   mns@gamil.com
8            Kanwal   27           BS    2 years    7456695   lsk@gmail.com
9           Shaista   42          PHD   12 years    3654789   ksk@gmail.com
10            Saira   36       Master    4 years   87453216   oia@gmail.com
11          Hoorain   28       Master  2.7 years     254987  bhsh@gmail.com
12           Nabila   39           BS    7 years    4569873  qwer@gamil.com
13            Nazia   44          PHD   11 years   32147895  fisa@gmail.com
14           Aneeqa   32       Master    1 years   77789546   mjd@gmail.com
15            Asifa   25           BS    3 years   36547888   lak@gmail.com
16           Nabiha   36           BS    6 years   98741222   djn@gmail.com
17           Neelam   45           BS   15 years  369874521   kaj@gmail.com
18            Hibba   30       Master  1.5 years     235478   nlm@gmail.com
19            Hania   24       Master    0 years  333222555   yui@gmail.com
20           Umaima   23           BS  0.5 years    4782415   mno@gmail.com

      CNIC No Address  Salary
0    23548972     abc   45000
1    69874236     efg   25000
2    69842369     hij   60000
3    55845522     klm   30000
4    98723654     nop   20000
5    87456321     qrs   50000
6    35478921     tuv   33000
7     3654789     wxy   40000
8     9874563     zab   28000
9     2589631     cde   36000
10    7412589     fgh   45000
11   85214796     ijk   22000
12  564123987     lmn   33000
13   13698752     opq   20000
14   36987333     rst   31000
15  966654782     uvw   44000
16    7852235     xyz   55000
17   36987222     abh   23000
18  789214666     opl   34000
19   25899963     mny   35000
20   14788547     kji   26000  >

### 20. Describe Function

In [41]:
t.describe()

             Age      Phone No       CNIC No        Salary
count  21.000000  2.100000e+01  2.100000e+01     21.000000
mean   32.904762  7.149200e+07  1.431297e+08  35000.000000
std     7.641366  1.228317e+08  2.728283e+08  11401.754251
min    22.000000  2.354780e+05  2.589631e+06  20000.000000
25%    26.000000  3.654897e+06  1.369875e+07  26000.000000
50%    32.000000  1.236588e+07  3.698722e+07  33000.000000
75%    39.000000  7.778955e+07  8.521480e+07  44000.000000
max    45.000000  3.698745e+08  9.666548e+08  60000.000000

### 21. Applymap Function

In [43]:
t.applymap

<bound method DataFrame.applymap of    Name of Employee  Age Qulification Experience   Phone No          E-mail  \
0              Amna   36       Master    5 years   12365879   abc@gmail.com
1            Ayesha   25           BS    2 years    3654897  vhzg@gmail.com
2             Komal   45          PHD   10 years   12551225   nsj@gmail.com
3            Kainat   32           BS    6 years   36589712  mjhg@gmail.com
4              Isma   22           BS    0 years  365426855   vgh@gmail.com
5            Sawera   41           MS    8 years    9842568   ksj@gmail.com
6             Zahra   26       Master    1 years     514789   lsk@gmail.com
7       Noor Fatima   33           MS    5 years    3654897   mns@gamil.com
8            Kanwal   27           BS    2 years    7456695   lsk@gmail.com
9           Shaista   42          PHD   12 years    3654789   ksk@gmail.com
10            Saira   36       Master    4 years   87453216   oia@gmail.com
11          Hoorain   28       Master  2.7 years     254987  bhsh@gmail.com
12           Nabila   39           BS    7 years    4569873  qwer@gamil.com
13            Nazia   44          PHD   11 years   32147895  fisa@gmail.com
14           Aneeqa   32       Master    1 years   77789546   mjd@gmail.com
15            Asifa   25           BS    3 years   36547888   lak@gmail.com
16           Nabiha   36           BS    6 years   98741222   djn@gmail.com
17           Neelam   45           BS   15 years  369874521   kaj@gmail.com
18            Hibba   30       Master  1.5 years     235478   nlm@gmail.com
19            Hania   24       Master    0 years  333222555   yui@gmail.com
20           Umaima   23           BS  0.5 years    4782415   mno@gmail.com

      CNIC No Address  Salary
0    23548972     abc   45000
1    69874236     efg   25000
2    69842369     hij   60000
3    55845522     klm   30000
4    98723654     nop   20000
5    87456321     qrs   50000
6    35478921     tuv   33000
7     3654789     wxy   40000
8     9874563     zab   28000
9     2589631     cde   36000
10    7412589     fgh   45000
11   85214796     ijk   22000
12  564123987     lmn   33000
13   13698752     opq   20000
14   36987333     rst   31000
15  966654782     uvw   44000
16    7852235     xyz   55000
17   36987222     abh   23000
18  789214666     opl   34000
19   25899963     mny   35000
20   14788547     kji   26000  >

### 22. Diference Function

In [44]:
t.diff()

TypeError: unsupported operand type(s) for -: 'str' and 'str'

### 23. Duplicate Function

In [46]:
t.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
dtype: bool

### 24. Head Function

In [47]:
t.head()

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
0,Amna,36,Master,5 years,12365879,abc@gmail.com,23548972,abc,45000
1,Ayesha,25,BS,2 years,3654897,vhzg@gmail.com,69874236,efg,25000
2,Komal,45,PHD,10 years,12551225,nsj@gmail.com,69842369,hij,60000
3,Kainat,32,BS,6 years,36589712,mjhg@gmail.com,55845522,klm,30000
4,Isma,22,BS,0 years,365426855,vgh@gmail.com,98723654,nop,20000

### 25. Tail Function

In [48]:
t.tail()

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
16,Nabiha,36,BS,6 years,98741222,djn@gmail.com,7852235,xyz,55000
17,Neelam,45,BS,15 years,369874521,kaj@gmail.com,36987222,abh,23000
18,Hibba,30,Master,1.5 years,235478,nlm@gmail.com,789214666,opl,34000
19,Hania,24,Master,0 years,333222555,yui@gmail.com,25899963,mny,35000
20,Umaima,23,BS,0.5 years,4782415,mno@gmail.com,14788547,kji,26000

### 26. Index Function

In [50]:
t.index

RangeIndex(start=0, stop=21, step=1)

### 27. Transporting Function

In [51]:
t.T

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
Name of Employee,Amna,Ayesha,Komal,Kainat,Isma,Sawera,Zahra,Noor Fatima,Kanwal,Shaista,...,Hoorain,Nabila,Nazia,Aneeqa,Asifa,Nabiha,Neelam,Hibba,Hania,Umaima
Age,36,25,45,32,22,41,26,33,27,42,...,28,39,44,32,25,36,45,30,24,23
Qulification,Master,BS,PHD,BS,BS,MS,Master,MS,BS,PHD,...,Master,BS,PHD,Master,BS,BS,BS,Master,Master,BS
Experience,5 years,2 years,10 years,6 years,0 years,8 years,1 years,5 years,2 years,12 years,...,2.7 years,7 years,11 years,1 years,3 years,6 years,15 years,1.5 years,0 years,0.5 years
Phone No,12365879,3654897,12551225,36589712,365426855,9842568,514789,3654897,7456695,3654789,...,254987,4569873,32147895,77789546,36547888,98741222,369874521,235478,333222555,4782415
E-mail,abc@gmail.com,vhzg@gmail.com,nsj@gmail.com,mjhg@gmail.com,vgh@gmail.com,ksj@gmail.com,lsk@gmail.com,mns@gamil.com,lsk@gmail.com,ksk@gmail.com,...,bhsh@gmail.com,qwer@gamil.com,fisa@gmail.com,mjd@gmail.com,lak@gmail.com,djn@gmail.com,kaj@gmail.com,nlm@gmail.com,yui@gmail.com,mno@gmail.com
CNIC No,23548972,69874236,69842369,55845522,98723654,87456321,35478921,3654789,9874563,2589631,...,85214796,564123987,13698752,36987333,966654782,7852235,36987222,789214666,25899963,14788547
Address,abc,efg,hij,klm,nop,qrs,tuv,wxy,zab,cde,...,ijk,lmn,opq,rst,uvw,xyz,abh,opl,mny,kji
Salary,45000,25000,60000,30000,20000,50000,33000,40000,28000,36000,...,22000,33000,20000,31000,44000,55000,23000,34000,35000,26000

### 28. Sort By Index Function

In [55]:
t.sort_index(axis=1,ascending=False)

,Salary,Qulification,Phone No,Name of Employee,Experience,E-mail,CNIC No,Age,Address
0,45000,Master,12365879,Amna,5 years,abc@gmail.com,23548972,36,abc
1,25000,BS,3654897,Ayesha,2 years,vhzg@gmail.com,69874236,25,efg
2,60000,PHD,12551225,Komal,10 years,nsj@gmail.com,69842369,45,hij
3,30000,BS,36589712,Kainat,6 years,mjhg@gmail.com,55845522,32,klm
4,20000,BS,365426855,Isma,0 years,vgh@gmail.com,98723654,22,nop
5,50000,MS,9842568,Sawera,8 years,ksj@gmail.com,87456321,41,qrs
6,33000,Master,514789,Zahra,1 years,lsk@gmail.com,35478921,26,tuv
7,40000,MS,3654897,Noor Fatima,5 years,mns@gamil.com,3654789,33,wxy
8,28000,BS,7456695,Kanwal,2 years,lsk@gmail.com,9874563,27,zab
9,36000,PHD,3654789,Shaista,12 years,ksk@gmail.com,2589631,42,cde
10,45000,Master,87453216,Saira,4 years,oia@gmail.com,7412589,36,fgh
11,22000,Master,254987,Hoorain,2.7 years,bhsh@gmail.com,85214796,28,ijk
12,33000,BS,4569873,Nabila,7 years,qwer@gamil.com,564123987,39,lmn
13,20000,PHD,32147895,Nazia,11 years,fisa@gmail.com,13698752,44,opq
14,31000,Master,77789546,Aneeqa,1 years,mjd@gmail.com,36987333,32,rst
15,44000,BS,36547888,Asifa,3 years,lak@gmail.com,966654782,25,uvw
16,55000,BS,98741222,Nabiha,6 years,djn@gmail.com,7852235,36,xyz
17,23000,BS,369874521,Neelam,15 years,kaj@gmail.com,36987222,45,abh
18,34000,Master,235478,Hibba,1.5 years,nlm@gmail.com,789214666,30,opl
19,35000,Master,333222555,Hania,0 years,yui@gmail.com,25899963,24,mny
20,26000,BS,4782415,Umaima,0.5 years,mno@gmail.com,14788547,23,kji

### 29. Sort By Value Function

In [56]:
t.sort_values(by="Qulification")

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
20,Umaima,23,BS,0.5 years,4782415,mno@gmail.com,14788547,kji,26000
1,Ayesha,25,BS,2 years,3654897,vhzg@gmail.com,69874236,efg,25000
3,Kainat,32,BS,6 years,36589712,mjhg@gmail.com,55845522,klm,30000
4,Isma,22,BS,0 years,365426855,vgh@gmail.com,98723654,nop,20000
17,Neelam,45,BS,15 years,369874521,kaj@gmail.com,36987222,abh,23000
8,Kanwal,27,BS,2 years,7456695,lsk@gmail.com,9874563,zab,28000
16,Nabiha,36,BS,6 years,98741222,djn@gmail.com,7852235,xyz,55000
15,Asifa,25,BS,3 years,36547888,lak@gmail.com,966654782,uvw,44000
12,Nabila,39,BS,7 years,4569873,qwer@gamil.com,564123987,lmn,33000
5,Sawera,41,MS,8 years,9842568,ksj@gmail.com,87456321,qrs,50000
7,Noor Fatima,33,MS,5 years,3654897,mns@gamil.com,3654789,wxy,40000
18,Hibba,30,Master,1.5 years,235478,nlm@gmail.com,789214666,opl,34000
14,Aneeqa,32,Master,1 years,77789546,mjd@gmail.com,36987333,rst,31000
0,Amna,36,Master,5 years,12365879,abc@gmail.com,23548972,abc,45000
11,Hoorain,28,Master,2.7 years,254987,bhsh@gmail.com,85214796,ijk,22000
19,Hania,24,Master,0 years,333222555,yui@gmail.com,25899963,mny,35000
6,Zahra,26,Master,1 years,514789,lsk@gmail.com,35478921,tuv,33000
10,Saira,36,Master,4 years,87453216,oia@gmail.com,7412589,fgh,45000
9,Shaista,42,PHD,12 years,3654789,ksk@gmail.com,2589631,cde,36000
2,Komal,45,PHD,10 years,12551225,nsj@gmail.com,69842369,hij,60000
13,Nazia,44,PHD,11 years,32147895,fisa@gmail.com,13698752,opq,20000

### 30. Getitem Function

In [60]:
t["Phone No"]

0      12365879
1       3654897
2      12551225
3      36589712
4     365426855
5       9842568
6        514789
7       3654897
8       7456695
9       3654789
10     87453216
11       254987
12      4569873
13     32147895
14     77789546
15     36547888
16     98741222
17    369874521
18       235478
19    333222555
20      4782415
Name: Phone No, dtype: int64

### 31. Slicing Function

In [61]:
t[4:9]

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
4,Isma,22,BS,0 years,365426855,vgh@gmail.com,98723654,nop,20000
5,Sawera,41,MS,8 years,9842568,ksj@gmail.com,87456321,qrs,50000
6,Zahra,26,Master,1 years,514789,lsk@gmail.com,35478921,tuv,33000
7,Noor Fatima,33,MS,5 years,3654897,mns@gamil.com,3654789,wxy,40000
8,Kanwal,27,BS,2 years,7456695,lsk@gmail.com,9874563,zab,28000

### 32. Loc Function

In [97]:
t.loc['Isma']

KeyError: 'Isma'

### 33. LOc Function By Slicing

In [71]:
t.loc[:, ["Age", "E-mail"]]

    Age          E-mail
0    36   abc@gmail.com
1    25  vhzg@gmail.com
2    45   nsj@gmail.com
3    32  mjhg@gmail.com
4    22   vgh@gmail.com
5    41   ksj@gmail.com
6    26   lsk@gmail.com
7    33   mns@gamil.com
8    27   lsk@gmail.com
9    42   ksk@gmail.com
10   36   oia@gmail.com
11   28  bhsh@gmail.com
12   39  qwer@gamil.com
13   44  fisa@gmail.com
14   32   mjd@gmail.com
15   25   lak@gmail.com
16   36   djn@gmail.com
17   45   kaj@gmail.com
18   30   nlm@gmail.com
19   24   yui@gmail.com
20   23   mno@gmail.com

### 34. Loc Function by index

In [74]:
t.loc[8]

Name of Employee           Kanwal
Age                            27
Qulification                   BS
Experience                2 years
Phone No                  7456695
E-mail              lsk@gmail.com
CNIC No                   9874563
Address                       zab
Salary                      28000
Name: 8, dtype: object

### 35. Iloc function by slicing

In [75]:
t.iloc[2:8,4:6]

    Phone No          E-mail
2   12551225   nsj@gmail.com
3   36589712  mjhg@gmail.com
4  365426855   vgh@gmail.com
5    9842568   ksj@gmail.com
6     514789   lsk@gmail.com
7    3654897   mns@gamil.com

### 36. Boolean Greater Than Function

In [79]:
t[t["Salary"]>30000]

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
0,Amna,36,Master,5 years,12365879,abc@gmail.com,23548972,abc,45000
2,Komal,45,PHD,10 years,12551225,nsj@gmail.com,69842369,hij,60000
5,Sawera,41,MS,8 years,9842568,ksj@gmail.com,87456321,qrs,50000
6,Zahra,26,Master,1 years,514789,lsk@gmail.com,35478921,tuv,33000
7,Noor Fatima,33,MS,5 years,3654897,mns@gamil.com,3654789,wxy,40000
9,Shaista,42,PHD,12 years,3654789,ksk@gmail.com,2589631,cde,36000
10,Saira,36,Master,4 years,87453216,oia@gmail.com,7412589,fgh,45000
12,Nabila,39,BS,7 years,4569873,qwer@gamil.com,564123987,lmn,33000
14,Aneeqa,32,Master,1 years,77789546,mjd@gmail.com,36987333,rst,31000
15,Asifa,25,BS,3 years,36547888,lak@gmail.com,966654782,uvw,44000
16,Nabiha,36,BS,6 years,98741222,djn@gmail.com,7852235,xyz,55000
18,Hibba,30,Master,1.5 years,235478,nlm@gmail.com,789214666,opl,34000
19,Hania,24,Master,0 years,333222555,yui@gmail.com,25899963,mny,35000

### 37. Isin Function

In [83]:
t[t["Qulification"].isin(["Master","PHD"])]

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
0,Amna,36,Master,5 years,12365879,abc@gmail.com,23548972,abc,45000
2,Komal,45,PHD,10 years,12551225,nsj@gmail.com,69842369,hij,60000
6,Zahra,26,Master,1 years,514789,lsk@gmail.com,35478921,tuv,33000
9,Shaista,42,PHD,12 years,3654789,ksk@gmail.com,2589631,cde,36000
10,Saira,36,Master,4 years,87453216,oia@gmail.com,7412589,fgh,45000
11,Hoorain,28,Master,2.7 years,254987,bhsh@gmail.com,85214796,ijk,22000
13,Nazia,44,PHD,11 years,32147895,fisa@gmail.com,13698752,opq,20000
14,Aneeqa,32,Master,1 years,77789546,mjd@gmail.com,36987333,rst,31000
18,Hibba,30,Master,1.5 years,235478,nlm@gmail.com,789214666,opl,34000
19,Hania,24,Master,0 years,333222555,yui@gmail.com,25899963,mny,35000

### 38. Setting value by label

In [94]:
t.at["Age"[0], "Age"] = 0
t

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
0,Amna,36.0,Master,5 years,12365879.0,abc@gmail.com,23548972.0,abc,45000.0
1,Ayesha,25.0,BS,2 years,3654897.0,vhzg@gmail.com,69874236.0,efg,25000.0
2,Komal,45.0,PHD,10 years,12551225.0,nsj@gmail.com,69842369.0,hij,60000.0
3,Kainat,32.0,BS,6 years,36589712.0,mjhg@gmail.com,55845522.0,klm,30000.0
4,Isma,22.0,BS,0 years,365426855.0,vgh@gmail.com,98723654.0,nop,20000.0
5,Sawera,41.0,MS,8 years,9842568.0,ksj@gmail.com,87456321.0,qrs,50000.0
6,Zahra,26.0,Master,1 years,514789.0,lsk@gmail.com,35478921.0,tuv,33000.0
7,Noor Fatima,33.0,MS,5 years,3654897.0,mns@gamil.com,3654789.0,wxy,40000.0
8,Kanwal,27.0,BS,2 years,7456695.0,lsk@gmail.com,9874563.0,zab,28000.0
9,Shaista,42.0,PHD,12 years,3654789.0,ksk@gmail.com,2589631.0,cde,36000.0
10,Saira,36.0,Master,4 years,87453216.0,oia@gmail.com,7412589.0,fgh,45000.0
11,Hoorain,28.0,Master,2.7 years,254987.0,bhsh@gmail.com,85214796.0,ijk,22000.0
12,Nabila,39.0,BS,7 years,4569873.0,qwer@gamil.com,564123987.0,lmn,33000.0
13,Nazia,44.0,PHD,11 years,32147895.0,fisa@gmail.com,13698752.0,opq,20000.0
14,Aneeqa,32.0,Master,1 years,77789546.0,mjd@gmail.com,36987333.0,rst,31000.0
15,Asifa,25.0,BS,3 years,36547888.0,lak@gmail.com,966654782.0,uvw,44000.0
16,Nabiha,36.0,BS,6 years,98741222.0,djn@gmail.com,7852235.0,xyz,55000.0
17,Neelam,45.0,BS,15 years,369874521.0,kaj@gmail.com,36987222.0,abh,23000.0
18,Hibba,30.0,Master,1.5 years,235478.0,nlm@gmail.com,789214666.0,opl,34000.0
19,Hania,24.0,Master,0 years,333222555.0,yui@gmail.com,25899963.0,mny,35000.0
20,Umaima,23.0,BS,0.5 years,4782415.0,mno@gmail.com,14788547.0,kji,26000.0
N,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 39. Setting value by position

In [101]:
t.iat[11,4]

np.float64(0.0)

### 40. Reindex Function

In [102]:
t = t.reindex(index="Hania"[0:4], columns=list(t.columns) + ["Elgibility"])
t.loc["Hania"[0] : "Hania"[1], "Eligibility"] = 1

t

TypeError: Index(...) must be called with a collection of some kind, 'Hani' was passed

### 41. Dropna Function

In [103]:
t.dropna(how="any")

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
0,Amna,36.0,Master,5 years,12365879.0,abc@gmail.com,23548972.0,abc,45000.0
1,Ayesha,25.0,BS,2 years,3654897.0,vhzg@gmail.com,69874236.0,efg,25000.0
2,Komal,45.0,PHD,10 years,12551225.0,nsj@gmail.com,69842369.0,hij,60000.0
3,Kainat,32.0,BS,6 years,36589712.0,mjhg@gmail.com,55845522.0,klm,30000.0
4,Isma,22.0,BS,0 years,365426855.0,vgh@gmail.com,98723654.0,nop,20000.0
5,Sawera,41.0,MS,8 years,9842568.0,ksj@gmail.com,87456321.0,qrs,50000.0
6,Zahra,26.0,Master,1 years,514789.0,lsk@gmail.com,35478921.0,tuv,33000.0
7,Noor Fatima,33.0,MS,5 years,3654897.0,mns@gamil.com,3654789.0,wxy,40000.0
8,Kanwal,27.0,BS,2 years,7456695.0,lsk@gmail.com,9874563.0,zab,28000.0
9,Shaista,42.0,PHD,12 years,3654789.0,ksk@gmail.com,2589631.0,cde,36000.0
10,Saira,36.0,Master,4 years,87453216.0,oia@gmail.com,7412589.0,fgh,45000.0
11,Hoorain,28.0,Master,2.7 years,0.0,bhsh@gmail.com,85214796.0,ijk,22000.0
12,Nabila,39.0,BS,7 years,4569873.0,qwer@gamil.com,564123987.0,lmn,33000.0
13,Nazia,44.0,PHD,11 years,32147895.0,fisa@gmail.com,13698752.0,opq,20000.0
14,Aneeqa,32.0,Master,1 years,77789546.0,mjd@gmail.com,36987333.0,rst,31000.0
15,Asifa,25.0,BS,3 years,36547888.0,lak@gmail.com,966654782.0,uvw,44000.0
16,Nabiha,36.0,BS,6 years,98741222.0,djn@gmail.com,7852235.0,xyz,55000.0
17,Neelam,45.0,BS,15 years,369874521.0,kaj@gmail.com,36987222.0,abh,23000.0
18,Hibba,30.0,Master,1.5 years,235478.0,nlm@gmail.com,789214666.0,opl,34000.0
19,Hania,24.0,Master,0 years,333222555.0,yui@gmail.com,25899963.0,mny,35000.0
20,Umaima,23.0,BS,0.5 years,4782415.0,mno@gmail.com,14788547.0,kji,26000.0

### 42. Fillna Function

In [104]:
t.fillna(value=10)

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
0,Amna,36.0,Master,5 years,12365879.0,abc@gmail.com,23548972.0,abc,45000.0
1,Ayesha,25.0,BS,2 years,3654897.0,vhzg@gmail.com,69874236.0,efg,25000.0
2,Komal,45.0,PHD,10 years,12551225.0,nsj@gmail.com,69842369.0,hij,60000.0
3,Kainat,32.0,BS,6 years,36589712.0,mjhg@gmail.com,55845522.0,klm,30000.0
4,Isma,22.0,BS,0 years,365426855.0,vgh@gmail.com,98723654.0,nop,20000.0
5,Sawera,41.0,MS,8 years,9842568.0,ksj@gmail.com,87456321.0,qrs,50000.0
6,Zahra,26.0,Master,1 years,514789.0,lsk@gmail.com,35478921.0,tuv,33000.0
7,Noor Fatima,33.0,MS,5 years,3654897.0,mns@gamil.com,3654789.0,wxy,40000.0
8,Kanwal,27.0,BS,2 years,7456695.0,lsk@gmail.com,9874563.0,zab,28000.0
9,Shaista,42.0,PHD,12 years,3654789.0,ksk@gmail.com,2589631.0,cde,36000.0
10,Saira,36.0,Master,4 years,87453216.0,oia@gmail.com,7412589.0,fgh,45000.0
11,Hoorain,28.0,Master,2.7 years,0.0,bhsh@gmail.com,85214796.0,ijk,22000.0
12,Nabila,39.0,BS,7 years,4569873.0,qwer@gamil.com,564123987.0,lmn,33000.0
13,Nazia,44.0,PHD,11 years,32147895.0,fisa@gmail.com,13698752.0,opq,20000.0
14,Aneeqa,32.0,Master,1 years,77789546.0,mjd@gmail.com,36987333.0,rst,31000.0
15,Asifa,25.0,BS,3 years,36547888.0,lak@gmail.com,966654782.0,uvw,44000.0
16,Nabiha,36.0,BS,6 years,98741222.0,djn@gmail.com,7852235.0,xyz,55000.0
17,Neelam,45.0,BS,15 years,369874521.0,kaj@gmail.com,36987222.0,abh,23000.0
18,Hibba,30.0,Master,1.5 years,235478.0,nlm@gmail.com,789214666.0,opl,34000.0
19,Hania,24.0,Master,0 years,333222555.0,yui@gmail.com,25899963.0,mny,35000.0
20,Umaima,23.0,BS,0.5 years,4782415.0,mno@gmail.com,14788547.0,kji,26000.0
N,10,0.0,10,10,10.0,10,10.0,10,10.0
A,10,0.0,10,10,10.0,10,10.0,10,10.0

### 43. Isna Function

In [105]:
pd.isna(t)

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
N,True,False,True,True,True,True,True,True,True
A,True,False,True,True,True,True,True,True,True

### 44. Mean Function

In [113]:
t.mean()

TypeError: can only concatenate str (not "int") to str

### 45. Median function

In [114]:
t.median()

TypeError: Cannot convert [['Amna' 'Ayesha' 'Komal' 'Kainat' 'Isma' 'Sawera' 'Zahra' 'Noor Fatima'
  'Kanwal' 'Shaista' 'Saira' 'Hoorain' 'Nabila' 'Nazia' 'Aneeqa' 'Asifa'
  'Nabiha' 'Neelam' 'Hibba' 'Hania' 'Umaima' nan nan]
 ['Master' 'BS' 'PHD' 'BS' 'BS' 'MS' 'Master' 'MS' 'BS' 'PHD' 'Master'
  'Master' 'BS' 'PHD' 'Master' 'BS' 'BS' 'BS' 'Master' 'Master' 'BS' nan
  nan]
 ['5 years' '2 years' '10 years' '6 years' '0 years' '8 years' '1 years'
  '5 years' '2 years' '12 years' '4 years' '2.7 years' '7 years'
  '11 years' '1 years' '3 years' '6 years' '15 years' '1.5 years'
  '0 years' '0.5 years' nan nan]
 ['abc@gmail.com' 'vhzg@gmail.com' 'nsj@gmail.com' 'mjhg@gmail.com'
  'vgh@gmail.com' 'ksj@gmail.com' 'lsk@gmail.com' 'mns@gamil.com'
  'lsk@gmail.com' 'ksk@gmail.com' 'oia@gmail.com' 'bhsh@gmail.com'
  'qwer@gamil.com' 'fisa@gmail.com' 'mjd@gmail.com' 'lak@gmail.com'
  'djn@gmail.com' 'kaj@gmail.com' 'nlm@gmail.com' 'yui@gmail.com'
  'mno@gmail.com' nan nan]
 ['abc' 'efg' 'hij' 'klm' 'nop' 'qrs' 'tuv' 'wxy' 'zab' 'cde' 'fgh' 'ijk'
  'lmn' 'opq' 'rst' 'uvw' 'xyz' 'abh' 'opl' 'mny' 'kji' nan nan]] to numeric

### 46. Mode Function

In [115]:
t.mode()

,Name of Employee,Age,Qulification,Experience,Phone No,E-mail,CNIC No,Address,Salary
0,Amna,36.0,BS,0 years,3654897.0,lsk@gmail.com,2589631.0,abc,20000.0
1,Aneeqa,NaN,NaN,1 years,NaN,NaN,3654789.0,abh,33000.0
2,Asifa,NaN,NaN,2 years,NaN,NaN,7412589.0,cde,45000.0
3,Ayesha,NaN,NaN,5 years,NaN,NaN,7852235.0,efg,NaN
4,Hania,NaN,NaN,6 years,NaN,NaN,9874563.0,fgh,NaN
5,Hibba,NaN,NaN,NaN,NaN,NaN,13698752.0,hij,NaN
6,Hoorain,NaN,NaN,NaN,NaN,NaN,14788547.0,ijk,NaN
7,Isma,NaN,NaN,NaN,NaN,NaN,23548972.0,kji,NaN
8,Kainat,NaN,NaN,NaN,NaN,NaN,25899963.0,klm,NaN
9,Kanwal,NaN,NaN,NaN,NaN,NaN,35478921.0,lmn,NaN
10,Komal,NaN,NaN,NaN,NaN,NaN,36987222.0,mny,NaN
11,Nabiha,NaN,NaN,NaN,NaN,NaN,36987333.0,nop,NaN
12,Nabila,NaN,NaN,NaN,NaN,NaN,55845522.0,opl,NaN
13,Nazia,NaN,NaN,NaN,NaN,NaN,69842369.0,opq,NaN
14,Neelam,NaN,NaN,NaN,NaN,NaN,69874236.0,qrs,NaN
15,Noor Fatima,NaN,NaN,NaN,NaN,NaN,85214796.0,rst,NaN
16,Saira,NaN,NaN,NaN,NaN,NaN,87456321.0,tuv,NaN
17,Sawera,NaN,NaN,NaN,NaN,NaN,98723654.0,uvw,NaN
18,Shaista,NaN,NaN,NaN,NaN,NaN,564123987.0,wxy,NaN
19,Umaima,NaN,NaN,NaN,NaN,NaN,789214666.0,xyz,NaN
20,Zahra,NaN,NaN,NaN,NaN,NaN,966654782.0,zab,NaN

### 47. str.lower Function

In [122]:
t.lower("Name of Employee")

AttributeError: 'DataFrame' object has no attribute 'lower'