# Rimsha Saleem
shrimsha110@gmail.com

### importing

In [3]:
import pandas as pd

In [2]:
import numpy as np

### install excel extention

In [4]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\dit\appdata\local\programs\python\python312\lib\site-packages (3.1.5)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: et-xmlfile in c:\users\dit\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (1.1.0)

###Data analysis  (retrive data from excel file)

In [69]:
r = pd.read_excel("Book1.xlsx")         
print("Dataframe")
r

Dataframe

  Unnamed: 0  Islamiyat   English      Urdu      Math      Stat  pakstudy
0     1 hour   0.015021  0.597957  0.393486  0.041745  0.152037  0.557229
1     2 hour   0.804788  0.189076  0.962615  0.816262  0.477432  0.084729
2     3 hour   0.643693  0.734196  0.299738  0.093527  0.772283  0.058246
3     4 hour   0.209171  0.718367  0.495380  0.816083  0.942286  0.295342
4     5 hour   0.975376  0.593259  0.974276  0.960929  0.017125  0.538454
5     6 hour   0.858752  0.554169  0.799520  0.943395  0.867872  0.912334
6     7 hour   0.165278  0.114283  0.529515  0.629199  0.183185  0.957302
7     8 hour   0.164629  0.666324  0.314646  0.132304  0.841783  0.650054
8     9 hour   0.756329  0.280145  0.662411  0.231109  0.519359  0.015335
9    10 hour   0.216455  0.921214  0.068994  0.384327  0.567193  0.154987

#### specfic column based on their integer indice

In [13]:
r["Math"].iloc[2]

np.float64(0.093526735301795)

#### one dimensional data

In [14]:
r = pd.Series([1, 3, 5, np.nan, 5, 6])
r

0    1.0
1    3.0
2    5.0
3    NaN
4    5.0
5    6.0
dtype: float64

#### sort in ascending order

In [15]:
sorted_r = r.sort_values()
print(sorted_r)

0    1.0
1    3.0
2    5.0
4    5.0
5    6.0
3    NaN
dtype: float64

#### descripted statistice

In [16]:
r.describe()

count    5.0
mean     4.0
std      2.0
min      1.0
25%      3.0
50%      5.0
75%      5.0
max      6.0
dtype: float64

#### return the first row obj on position

In [17]:
r. head()

0    1.0
1    3.0
2    5.0
3    NaN
4    5.0
dtype: float64

#### specfied num of last row

In [18]:
r. tail()

1    3.0
2    5.0
3    NaN
4    5.0
5    6.0
dtype: float64

#### primaly used to array

In [19]:
r. to_numpy()

array([ 1.,  3.,  5., nan,  5.,  6.])

#### return the datatype

In [20]:
r. dtypes

dtype('float64')

#### transpose index and column  (rows ko col or col ko rows)

In [21]:
r. T

0    1.0
1    3.0
2    5.0
3    NaN
4    5.0
5    6.0
dtype: float64

#### for rows

In [22]:
r. index

RangeIndex(start=0, stop=6, step=1)

#### check the dataframe contains specfied values

In [23]:
r = pd.Series([1, 3, 5, np.nan, 5, 6,])
result = r.isin([3,5])
print(result)

0    False
1     True
2     True
3    False
4     True
5    False
dtype: bool

#### slicing

In [24]:
r[0:3]

0    1.0
1    3.0
2    5.0
dtype: float64

#### mean

In [26]:
r.mean()

np.float64(4.0)

#### median

In [27]:
r.median()

np.float64(5.0)

#### drop values

In [31]:
r.drop([2])

0    1.0
1    3.0
3    NaN
4    5.0
5    6.0
dtype: float64

#### info  dataframe k structure or dtype btane k ley

In [30]:
r.info()

<class 'pandas.core.series.Series'>
RangeIndex: 6 entries, 0 to 5
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      float64
dtypes: float64(1)
memory usage: 180.0 bytes

#### missing value ko fill krvane k ley

In [33]:
r.fillna(value=2)

0    1.0
1    3.0
2    5.0
3    2.0
4    5.0
5    6.0
dtype: float64

#### check specfied values

In [40]:
pd.isna(r)

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

In [54]:
r = pd.Series([100, 255, 300, 120])
r

0    100
1    255
2    300
3    120
dtype: int64

#### col ko acess krne k ley

In [57]:
r.sort_values(axis=0)

0    100
3    120
1    255
2    300
dtype: int64

In [60]:
r

0    100
1    255
2    300
3    120
dtype: int64

#### single value ko select k ley

In [64]:
r.iat[5, 2]

np.float64(0.5541690827629885)

#### sizeing

In [67]:
Series = pd.Series([1, 2, 3, 4])
print(Series.size)

4

In [71]:
r.dropna()

  Unnamed: 0  Islamiyat   English      Urdu      Math      Stat  pakstudy
0     1 hour   0.015021  0.597957  0.393486  0.041745  0.152037  0.557229
1     2 hour   0.804788  0.189076  0.962615  0.816262  0.477432  0.084729
2     3 hour   0.643693  0.734196  0.299738  0.093527  0.772283  0.058246
3     4 hour   0.209171  0.718367  0.495380  0.816083  0.942286  0.295342
4     5 hour   0.975376  0.593259  0.974276  0.960929  0.017125  0.538454
5     6 hour   0.858752  0.554169  0.799520  0.943395  0.867872  0.912334
6     7 hour   0.165278  0.114283  0.529515  0.629199  0.183185  0.957302
7     8 hour   0.164629  0.666324  0.314646  0.132304  0.841783  0.650054
8     9 hour   0.756329  0.280145  0.662411  0.231109  0.519359  0.015335
9    10 hour   0.216455  0.921214  0.068994  0.384327  0.567193  0.154987

In [72]:

r.isna()

   Unnamed: 0  Islamiyat  English   Urdu   Math   Stat  pakstudy
0       False      False    False  False  False  False     False
1       False      False    False  False  False  False     False
2       False      False    False  False  False  False     False
3       False      False    False  False  False  False     False
4       False      False    False  False  False  False     False
5       False      False    False  False  False  False     False
6       False      False    False  False  False  False     False
7       False      False    False  False  False  False     False
8       False      False    False  False  False  False     False
9       False      False    False  False  False  False     False

In [74]:
r.fillna

<bound method NDFrame.fillna of   Unnamed: 0  Islamiyat   English      Urdu      Math      Stat  pakstudy
0     1 hour   0.015021  0.597957  0.393486  0.041745  0.152037  0.557229
1     2 hour   0.804788  0.189076  0.962615  0.816262  0.477432  0.084729
2     3 hour   0.643693  0.734196  0.299738  0.093527  0.772283  0.058246
3     4 hour   0.209171  0.718367  0.495380  0.816083  0.942286  0.295342
4     5 hour   0.975376  0.593259  0.974276  0.960929  0.017125  0.538454
5     6 hour   0.858752  0.554169  0.799520  0.943395  0.867872  0.912334
6     7 hour   0.165278  0.114283  0.529515  0.629199  0.183185  0.957302
7     8 hour   0.164629  0.666324  0.314646  0.132304  0.841783  0.650054
8     9 hour   0.756329  0.280145  0.662411  0.231109  0.519359  0.015335
9    10 hour   0.216455  0.921214  0.068994  0.384327  0.567193  0.154987>

In [75]:
r

  Unnamed: 0  Islamiyat   English      Urdu      Math      Stat  pakstudy
0     1 hour   0.015021  0.597957  0.393486  0.041745  0.152037  0.557229
1     2 hour   0.804788  0.189076  0.962615  0.816262  0.477432  0.084729
2     3 hour   0.643693  0.734196  0.299738  0.093527  0.772283  0.058246
3     4 hour   0.209171  0.718367  0.495380  0.816083  0.942286  0.295342
4     5 hour   0.975376  0.593259  0.974276  0.960929  0.017125  0.538454
5     6 hour   0.858752  0.554169  0.799520  0.943395  0.867872  0.912334
6     7 hour   0.165278  0.114283  0.529515  0.629199  0.183185  0.957302
7     8 hour   0.164629  0.666324  0.314646  0.132304  0.841783  0.650054
8     9 hour   0.756329  0.280145  0.662411  0.231109  0.519359  0.015335
9    10 hour   0.216455  0.921214  0.068994  0.384327  0.567193  0.154987