### Name:   Ambreen
### E-Mail: Ambreenkhan57ak@gmail.com
### Topic : Pandas functions implementation

***

#### importing pandas and numpy and installing excel library

In [37]:
import pandas as pd
import numpy as np
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

# Read Excel file

In [38]:
df=pd.read_excel("data.xlsx")
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,English,Urdu,Maths,Physics,Chemistry,Bio,PSt,Islamiat
0,0.119474,0.239085,0.012440,0.571416,0.403083,0.738606,0.276011,0.882746,0.371731,0.982237,0.384592,0.320944,0.087402,0.309585,0.260879,0.667411
1,0.430905,0.383681,0.082613,0.209430,0.358533,0.770771,0.924578,0.855662,0.115478,0.066545,0.581165,0.780201,0.048451,0.500337,0.620652,0.473355
2,0.242997,0.570807,0.778336,0.806507,0.533121,0.648477,0.275912,0.660557,0.585514,0.758866,0.095574,0.782417,0.366413,0.774236,0.707355,0.252295
3,0.501628,0.034464,0.395550,0.523063,0.225245,0.361950,0.982694,0.596087,0.783518,0.803192,0.957146,0.571894,0.107210,0.362442,0.585707,0.055925
4,0.344307,0.601175,0.918672,0.585692,0.115941,0.004124,0.405912,0.366132,0.411279,0.550334,0.855713,0.065382,0.784871,0.460713,0.326616,0.396151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,0.276460,0.619686,0.732752,0.941922,0.179101,0.533068,0.449423,0.359416,0.750122,0.295945,0.629010,0.424472,0.869598,0.968629,0.263696,0.836866
195,0.599194,0.429428,0.230312,0.117274,0.978755,0.912314,0.280604,0.476602,0.016388,0.452468,0.587608,0.576335,0.773289,0.157547,0.511317,0.529795
196,0.735800,0.628053,0.406362,0.270686,0.856782,0.097980,0.091743,0.601370,0.193138,0.523941,0.306541,0.840965,0.278975,0.985553,0.040555,0.892293
197,0.533521,0.653583,0.490876,0.993591,0.201744,0.692654,0.150761,0.227123,0.885846,0.066748,0.403141,0.289215,0.809245,0.138043,0.789561,0.757916
198,0.364735,0.033739,0.266301,0.854474,0.307739,0.472611,0.267519,0.042142,0.459191,0.363029,0.120381,0.733721,0.379377,0.121244,0.245184,0.910713

# display data types

In [39]:
df.dtypes

Unnamed: 0    float64
Unnamed: 1    float64
Unnamed: 2    float64
Unnamed: 3    float64
Unnamed: 4    float64
Unnamed: 5    float64
Unnamed: 6    float64
Unnamed: 7    float64
English       float64
Urdu          float64
Maths         float64
Physics       float64
Chemistry     float64
Bio           float64
PSt           float64
Islamiat      float64
dtype: object

#  view the top rows of the frame

In [40]:
df.head

<bound method NDFrame.head of      Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0      0.119474    0.239085    0.012440    0.571416    0.403083    0.738606
1      0.430905    0.383681    0.082613    0.209430    0.358533    0.770771
2      0.242997    0.570807    0.778336    0.806507    0.533121    0.648477
3      0.501628    0.034464    0.395550    0.523063    0.225245    0.361950
4      0.344307    0.601175    0.918672    0.585692    0.115941    0.004124
..          ...         ...         ...         ...         ...         ...
194    0.276460    0.619686    0.732752    0.941922    0.179101    0.533068
195    0.599194    0.429428    0.230312    0.117274    0.978755    0.912314
196    0.735800    0.628053    0.406362    0.270686    0.856782    0.097980
197    0.533521    0.653583    0.490876    0.993591    0.201744    0.692654
198    0.364735    0.033739    0.266301    0.854474    0.307739    0.472611

     Unnamed: 6  Unnamed: 7   English      Urdu     Maths   Physics  \
0      0.276011    0.882746  0.371731  0.982237  0.384592  0.320944
1      0.924578    0.855662  0.115478  0.066545  0.581165  0.780201
2      0.275912    0.660557  0.585514  0.758866  0.095574  0.782417
3      0.982694    0.596087  0.783518  0.803192  0.957146  0.571894
4      0.405912    0.366132  0.411279  0.550334  0.855713  0.065382
..          ...         ...       ...       ...       ...       ...
194    0.449423    0.359416  0.750122  0.295945  0.629010  0.424472
195    0.280604    0.476602  0.016388  0.452468  0.587608  0.576335
196    0.091743    0.601370  0.193138  0.523941  0.306541  0.840965
197    0.150761    0.227123  0.885846  0.066748  0.403141  0.289215
198    0.267519    0.042142  0.459191  0.363029  0.120381  0.733721

     Chemistry       Bio       PSt  Islamiat
0     0.087402  0.309585  0.260879  0.667411
1     0.048451  0.500337  0.620652  0.473355
2     0.366413  0.774236  0.707355  0.252295
3     0.107210  0.362442  0.585707  0.055925
4     0.784871  0.460713  0.326616  0.396151
..         ...       ...       ...       ...
194   0.869598  0.968629  0.263696  0.836866
195   0.773289  0.157547  0.511317  0.529795
196   0.278975  0.985553  0.040555  0.892293
197   0.809245  0.138043  0.789561  0.757916
198   0.379377  0.121244  0.245184  0.910713

[199 rows x 16 columns]>

#  view the  bottom rows of the frame

In [41]:
df.tail

<bound method NDFrame.tail of      Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0      0.119474    0.239085    0.012440    0.571416    0.403083    0.738606
1      0.430905    0.383681    0.082613    0.209430    0.358533    0.770771
2      0.242997    0.570807    0.778336    0.806507    0.533121    0.648477
3      0.501628    0.034464    0.395550    0.523063    0.225245    0.361950
4      0.344307    0.601175    0.918672    0.585692    0.115941    0.004124
..          ...         ...         ...         ...         ...         ...
194    0.276460    0.619686    0.732752    0.941922    0.179101    0.533068
195    0.599194    0.429428    0.230312    0.117274    0.978755    0.912314
196    0.735800    0.628053    0.406362    0.270686    0.856782    0.097980
197    0.533521    0.653583    0.490876    0.993591    0.201744    0.692654
198    0.364735    0.033739    0.266301    0.854474    0.307739    0.472611

     Unnamed: 6  Unnamed: 7   English      Urdu     Maths   Physics  \
0      0.276011    0.882746  0.371731  0.982237  0.384592  0.320944
1      0.924578    0.855662  0.115478  0.066545  0.581165  0.780201
2      0.275912    0.660557  0.585514  0.758866  0.095574  0.782417
3      0.982694    0.596087  0.783518  0.803192  0.957146  0.571894
4      0.405912    0.366132  0.411279  0.550334  0.855713  0.065382
..          ...         ...       ...       ...       ...       ...
194    0.449423    0.359416  0.750122  0.295945  0.629010  0.424472
195    0.280604    0.476602  0.016388  0.452468  0.587608  0.576335
196    0.091743    0.601370  0.193138  0.523941  0.306541  0.840965
197    0.150761    0.227123  0.885846  0.066748  0.403141  0.289215
198    0.267519    0.042142  0.459191  0.363029  0.120381  0.733721

     Chemistry       Bio       PSt  Islamiat
0     0.087402  0.309585  0.260879  0.667411
1     0.048451  0.500337  0.620652  0.473355
2     0.366413  0.774236  0.707355  0.252295
3     0.107210  0.362442  0.585707  0.055925
4     0.784871  0.460713  0.326616  0.396151
..         ...       ...       ...       ...
194   0.869598  0.968629  0.263696  0.836866
195   0.773289  0.157547  0.511317  0.529795
196   0.278975  0.985553  0.040555  0.892293
197   0.809245  0.138043  0.789561  0.757916
198   0.379377  0.121244  0.245184  0.910713

[199 rows x 16 columns]>

# Display the DataFrame.index

In [42]:
df.index

RangeIndex(start=0, stop=199, step=1)

# Return a NumPy representation of the underlying data

In [43]:
df.to_numpy()

array([[0.11947429, 0.23908534, 0.01243992, ..., 0.30958534, 0.26087863,
        0.66741091],
       [0.43090536, 0.38368075, 0.0826132 , ..., 0.50033728, 0.6206524 ,
        0.4733549 ],
       [0.2429972 , 0.5708073 , 0.77833637, ..., 0.77423584, 0.70735494,
        0.25229538],
       ...,
       [0.73580017, 0.62805303, 0.40636229, ..., 0.9855525 , 0.04055542,
        0.89229307],
       [0.53352082, 0.65358287, 0.49087563, ..., 0.13804325, 0.78956053,
        0.7579162 ],
       [0.36473521, 0.03373949, 0.26630086, ..., 0.12124406, 0.24518436,
        0.91071303]])

#  shows a quick statistic summary of your data:

In [44]:
df.describe

<bound method NDFrame.describe of      Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0      0.119474    0.239085    0.012440    0.571416    0.403083    0.738606
1      0.430905    0.383681    0.082613    0.209430    0.358533    0.770771
2      0.242997    0.570807    0.778336    0.806507    0.533121    0.648477
3      0.501628    0.034464    0.395550    0.523063    0.225245    0.361950
4      0.344307    0.601175    0.918672    0.585692    0.115941    0.004124
..          ...         ...         ...         ...         ...         ...
194    0.276460    0.619686    0.732752    0.941922    0.179101    0.533068
195    0.599194    0.429428    0.230312    0.117274    0.978755    0.912314
196    0.735800    0.628053    0.406362    0.270686    0.856782    0.097980
197    0.533521    0.653583    0.490876    0.993591    0.201744    0.692654
198    0.364735    0.033739    0.266301    0.854474    0.307739    0.472611

     Unnamed: 6  Unnamed: 7   English      Urdu     Maths   Physics  \
0      0.276011    0.882746  0.371731  0.982237  0.384592  0.320944
1      0.924578    0.855662  0.115478  0.066545  0.581165  0.780201
2      0.275912    0.660557  0.585514  0.758866  0.095574  0.782417
3      0.982694    0.596087  0.783518  0.803192  0.957146  0.571894
4      0.405912    0.366132  0.411279  0.550334  0.855713  0.065382
..          ...         ...       ...       ...       ...       ...
194    0.449423    0.359416  0.750122  0.295945  0.629010  0.424472
195    0.280604    0.476602  0.016388  0.452468  0.587608  0.576335
196    0.091743    0.601370  0.193138  0.523941  0.306541  0.840965
197    0.150761    0.227123  0.885846  0.066748  0.403141  0.289215
198    0.267519    0.042142  0.459191  0.363029  0.120381  0.733721

     Chemistry       Bio       PSt  Islamiat
0     0.087402  0.309585  0.260879  0.667411
1     0.048451  0.500337  0.620652  0.473355
2     0.366413  0.774236  0.707355  0.252295
3     0.107210  0.362442  0.585707  0.055925
4     0.784871  0.460713  0.326616  0.396151
..         ...       ...       ...       ...
194   0.869598  0.968629  0.263696  0.836866
195   0.773289  0.157547  0.511317  0.529795
196   0.278975  0.985553  0.040555  0.892293
197   0.809245  0.138043  0.789561  0.757916
198   0.379377  0.121244  0.245184  0.910713

[199 rows x 16 columns]>

# Transposing your data:

In [45]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,189,190,191,192,193,194,195,196,197,198
Unnamed: 0,0.119474,0.430905,0.242997,0.501628,0.344307,0.964187,0.821662,0.008212,0.331093,0.142101,...,0.370877,0.085573,0.313960,0.646031,0.721311,0.276460,0.599194,0.735800,0.533521,0.364735
Unnamed: 1,0.239085,0.383681,0.570807,0.034464,0.601175,0.677779,0.150356,0.295833,0.320974,0.670825,...,0.119035,0.344521,0.745904,0.822704,0.313806,0.619686,0.429428,0.628053,0.653583,0.033739
Unnamed: 2,0.012440,0.082613,0.778336,0.395550,0.918672,0.433837,0.275888,0.993586,0.887739,0.613590,...,0.695604,0.523816,0.496454,0.983880,0.844906,0.732752,0.230312,0.406362,0.490876,0.266301
Unnamed: 3,0.571416,0.209430,0.806507,0.523063,0.585692,0.772602,0.902729,0.444534,0.042158,0.229293,...,0.359286,0.295794,0.111207,0.529290,0.820212,0.941922,0.117274,0.270686,0.993591,0.854474
Unnamed: 4,0.403083,0.358533,0.533121,0.225245,0.115941,0.706721,0.655242,0.490564,0.965557,0.144571,...,0.754363,0.262439,0.253374,0.644976,0.724172,0.179101,0.978755,0.856782,0.201744,0.307739
Unnamed: 5,0.738606,0.770771,0.648477,0.361950,0.004124,0.938622,0.695251,0.677603,0.477693,0.004625,...,0.277526,0.149473,0.275735,0.183311,0.792752,0.533068,0.912314,0.097980,0.692654,0.472611
Unnamed: 6,0.276011,0.924578,0.275912,0.982694,0.405912,0.782732,0.253221,0.412899,0.915451,0.403827,...,0.314316,0.756730,0.046889,0.340234,0.606678,0.449423,0.280604,0.091743,0.150761,0.267519
Unnamed: 7,0.882746,0.855662,0.660557,0.596087,0.366132,0.657180,0.532274,0.038032,0.477296,0.912434,...,0.886154,0.748729,0.827893,0.367062,0.587866,0.359416,0.476602,0.601370,0.227123,0.042142
English,0.371731,0.115478,0.585514,0.783518,0.411279,0.374422,0.898136,0.046759,0.775195,0.748434,...,0.196922,0.859450,0.689164,0.434223,0.359133,0.750122,0.016388,0.193138,0.885846,0.459191
Urdu,0.982237,0.066545,0.758866,0.803192,0.550334,0.734718,0.168568,0.467686,0.642916,0.354455,...,0.335223,0.293027,0.361492,0.501810,0.793694,0.295945,0.452468,0.523941,0.066748,0.363029
Maths,0.384592,0.581165,0.095574,0.957146,0.855713,0.555575,0.663497,0.256182,0.759132,0.127016,...,0.996568,0.332653,0.046604,0.330770,0.531134,0.629010,0.587608,0.306541,0.403141,0.120381
Physics,0.320944,0.780201,0.782417,0.571894,0.065382,0.268494,0.286084,0.623216,0.315621,0.301750,...,0.904491,0.339095,0.725223,0.389187,0.504213,0.424472,0.576335,0.840965,0.289215,0.733721
Chemistry,0.087402,0.048451,0.366413,0.107210,0.784871,0.853117,0.339564,0.794574,0.517594,0.765338,...,0.504535,0.628054,0.797929,0.045227,0.244096,0.869598,0.773289,0.278975,0.809245,0.379377
Bio,0.309585,0.500337,0.774236,0.362442,0.460713,0.510372,0.420927,0.701966,0.922620,0.049634,...,0.906648,0.790811,0.908467,0.197929,0.349408,0.968629,0.157547,0.985553,0.138043,0.121244
PSt,0.260879,0.620652,0.707355,0.585707,0.326616,0.686902,0.498138,0.204275,0.625964,0.782753,...,0.008543,0.941182,0.228396,0.498889,0.362914,0.263696,0.511317,0.040555,0.789561,0.245184
Islamiat,0.667411,0.473355,0.252295,0.055925,0.396151,0.107564,0.306522,0.261180,0.320433,0.218586,...,0.358581,0.895032,0.507021,0.947375,0.833131,0.836866,0.529795,0.892293,0.757916,0.910713

# sorts by an axis:

In [46]:
df.sort_index(axis=1, ascending=False)

,Urdu,Unnamed: 7,Unnamed: 6,Unnamed: 5,Unnamed: 4,Unnamed: 3,Unnamed: 2,Unnamed: 1,Unnamed: 0,Physics,PSt,Maths,Islamiat,English,Chemistry,Bio
0,0.982237,0.882746,0.276011,0.738606,0.403083,0.571416,0.012440,0.239085,0.119474,0.320944,0.260879,0.384592,0.667411,0.371731,0.087402,0.309585
1,0.066545,0.855662,0.924578,0.770771,0.358533,0.209430,0.082613,0.383681,0.430905,0.780201,0.620652,0.581165,0.473355,0.115478,0.048451,0.500337
2,0.758866,0.660557,0.275912,0.648477,0.533121,0.806507,0.778336,0.570807,0.242997,0.782417,0.707355,0.095574,0.252295,0.585514,0.366413,0.774236
3,0.803192,0.596087,0.982694,0.361950,0.225245,0.523063,0.395550,0.034464,0.501628,0.571894,0.585707,0.957146,0.055925,0.783518,0.107210,0.362442
4,0.550334,0.366132,0.405912,0.004124,0.115941,0.585692,0.918672,0.601175,0.344307,0.065382,0.326616,0.855713,0.396151,0.411279,0.784871,0.460713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,0.295945,0.359416,0.449423,0.533068,0.179101,0.941922,0.732752,0.619686,0.276460,0.424472,0.263696,0.629010,0.836866,0.750122,0.869598,0.968629
195,0.452468,0.476602,0.280604,0.912314,0.978755,0.117274,0.230312,0.429428,0.599194,0.576335,0.511317,0.587608,0.529795,0.016388,0.773289,0.157547
196,0.523941,0.601370,0.091743,0.097980,0.856782,0.270686,0.406362,0.628053,0.735800,0.840965,0.040555,0.306541,0.892293,0.193138,0.278975,0.985553
197,0.066748,0.227123,0.150761,0.692654,0.201744,0.993591,0.490876,0.653583,0.533521,0.289215,0.789561,0.403141,0.757916,0.885846,0.809245,0.138043
198,0.363029,0.042142,0.267519,0.472611,0.307739,0.854474,0.266301,0.033739,0.364735,0.733721,0.245184,0.120381,0.910713,0.459191,0.379377,0.121244

# sorts by values:

In [47]:
df.sort_values(by="Physics")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,English,Urdu,Maths,Physics,Chemistry,Bio,PSt,Islamiat
160,0.358136,0.360902,0.008176,0.842074,0.008311,0.385117,0.834533,0.830947,0.038501,0.458193,0.118459,0.009349,0.870830,0.031195,0.337340,0.318736
121,0.540432,0.231598,0.009499,0.573772,0.666239,0.239909,0.269794,0.439733,0.282589,0.527604,0.397746,0.016170,0.315468,0.626276,0.975979,0.999254
46,0.261798,0.362582,0.892979,0.785321,0.651400,0.720331,0.190144,0.949201,0.684633,0.860202,0.997696,0.016272,0.076974,0.802977,0.462759,0.505138
169,0.179646,0.615969,0.788366,0.478412,0.679147,0.464329,0.014611,0.570863,0.483495,0.979830,0.147739,0.025838,0.824042,0.540539,0.297208,0.466284
11,0.831046,0.449718,0.521597,0.026773,0.678444,0.904666,0.723967,0.105207,0.464519,0.947333,0.990287,0.033334,0.544141,0.379942,0.150015,0.235042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,0.511038,0.004959,0.119052,0.910325,0.491001,0.752953,0.970934,0.748071,0.868714,0.415828,0.987819,0.961530,0.343529,0.693055,0.375505,0.265419
188,0.443226,0.251859,0.678660,0.900662,0.390349,0.720140,0.286965,0.005174,0.540627,0.673715,0.630080,0.974490,0.952957,0.604409,0.343867,0.508594
24,0.784440,0.982410,0.785201,0.982938,0.685725,0.863051,0.025884,0.685886,0.745526,0.418823,0.358064,0.992292,0.609018,0.435570,0.686483,0.439775
63,0.887467,0.570041,0.199356,0.591056,0.913262,0.904515,0.025590,0.685201,0.410545,0.556802,0.470857,0.993912,0.122036,0.809343,0.697013,0.619867
25,0.563647,0.656402,0.173696,0.331683,0.121638,0.075575,0.236072,0.402975,0.171281,0.037957,0.433449,0.999918,0.357198,0.732148,0.470222,0.040843

# passing a single label selects a columns

In [48]:
df["English"]

0      0.371731
1      0.115478
2      0.585514
3      0.783518
4      0.411279
         ...
194    0.750122
195    0.016388
196    0.193138
197    0.885846
198    0.459191
Name: English, Length: 199, dtype: float64

# passing a slice : selects matching rows:

In [49]:
df[3:7]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,English,Urdu,Maths,Physics,Chemistry,Bio,PSt,Islamiat
3,0.501628,0.034464,0.395550,0.523063,0.225245,0.361950,0.982694,0.596087,0.783518,0.803192,0.957146,0.571894,0.107210,0.362442,0.585707,0.055925
4,0.344307,0.601175,0.918672,0.585692,0.115941,0.004124,0.405912,0.366132,0.411279,0.550334,0.855713,0.065382,0.784871,0.460713,0.326616,0.396151
5,0.964187,0.677779,0.433837,0.772602,0.706721,0.938622,0.782732,0.657180,0.374422,0.734718,0.555575,0.268494,0.853117,0.510372,0.686902,0.107564
6,0.821662,0.150356,0.275888,0.902729,0.655242,0.695251,0.253221,0.532274,0.898136,0.168568,0.663497,0.286084,0.339564,0.420927,0.498138,0.306522

# Selecting all rows (:) with a select column labels:

In [50]:
df.loc[:, ["English", "Urdu"]]

      English      Urdu
0    0.371731  0.982237
1    0.115478  0.066545
2    0.585514  0.758866
3    0.783518  0.803192
4    0.411279  0.550334
..        ...       ...
194  0.750122  0.295945
195  0.016388  0.452468
196  0.193138  0.523941
197  0.885846  0.066748
198  0.459191  0.363029

[199 rows x 2 columns]

# For label slicing, both endpoints are included:

In [51]:
df.loc["0":"2", ["English", "Urdu"]]

     English      Urdu
0   0.371731  0.982237
1   0.115478  0.066545
2   0.585514  0.758866
3   0.783518  0.803192
4   0.411279  0.550334
5   0.374422  0.734718
6   0.898136  0.168568
7   0.046759  0.467686
8   0.775195  0.642916
9   0.748434  0.354455
10  0.801723  0.069191
11  0.464519  0.947333
12  0.088781  0.064190
13  0.457365  0.706675
14  0.164095  0.128379
15  0.375415  0.933771
16  0.963268  0.307038
17  0.819817  0.853415
18  0.966639  0.267908
19  0.487010  0.588435

# Select via the position of the passed integers:

In [52]:
df.iloc[3]

Unnamed: 0    0.501628
Unnamed: 1    0.034464
Unnamed: 2    0.395550
Unnamed: 3    0.523063
Unnamed: 4    0.225245
Unnamed: 5    0.361950
Unnamed: 6    0.982694
Unnamed: 7    0.596087
English       0.783518
Urdu          0.803192
Maths         0.957146
Physics       0.571894
Chemistry     0.107210
Bio           0.362442
PSt           0.585707
Islamiat      0.055925
Name: 3, dtype: float64

In [53]:
df.iloc[3:5, 0:2]

   Unnamed: 0  Unnamed: 1
3    0.501628    0.034464
4    0.344307    0.601175

# For slicing rows explicitly:

In [54]:
df.iloc[1:3, :]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,English,Urdu,Maths,Physics,Chemistry,Bio,PSt,Islamiat
1,0.430905,0.383681,0.082613,0.209430,0.358533,0.770771,0.924578,0.855662,0.115478,0.066545,0.581165,0.780201,0.048451,0.500337,0.620652,0.473355
2,0.242997,0.570807,0.778336,0.806507,0.533121,0.648477,0.275912,0.660557,0.585514,0.758866,0.095574,0.782417,0.366413,0.774236,0.707355,0.252295

# For slicing columns explicitly:

In [55]:
df.iloc[:, 1:3]

     Unnamed: 1  Unnamed: 2
0      0.239085    0.012440
1      0.383681    0.082613
2      0.570807    0.778336
3      0.034464    0.395550
4      0.601175    0.918672
..          ...         ...
194    0.619686    0.732752
195    0.429428    0.230312
196    0.628053    0.406362
197    0.653583    0.490876
198    0.033739    0.266301

[199 rows x 2 columns]

# For getting a value explicitly

In [56]:
df.iloc[1, 1]

np.float64(0.38368075357360454)

In [57]:
df.iat[1, 1]

np.float64(0.38368075357360454)

# Boolean Indexing

# Select rows where df.English is greater than 0.

In [58]:
df[df["English"] > 0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,English,Urdu,Maths,Physics,Chemistry,Bio,PSt,Islamiat
0,0.119474,0.239085,0.012440,0.571416,0.403083,0.738606,0.276011,0.882746,0.371731,0.982237,0.384592,0.320944,0.087402,0.309585,0.260879,0.667411
1,0.430905,0.383681,0.082613,0.209430,0.358533,0.770771,0.924578,0.855662,0.115478,0.066545,0.581165,0.780201,0.048451,0.500337,0.620652,0.473355
2,0.242997,0.570807,0.778336,0.806507,0.533121,0.648477,0.275912,0.660557,0.585514,0.758866,0.095574,0.782417,0.366413,0.774236,0.707355,0.252295
3,0.501628,0.034464,0.395550,0.523063,0.225245,0.361950,0.982694,0.596087,0.783518,0.803192,0.957146,0.571894,0.107210,0.362442,0.585707,0.055925
4,0.344307,0.601175,0.918672,0.585692,0.115941,0.004124,0.405912,0.366132,0.411279,0.550334,0.855713,0.065382,0.784871,0.460713,0.326616,0.396151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,0.276460,0.619686,0.732752,0.941922,0.179101,0.533068,0.449423,0.359416,0.750122,0.295945,0.629010,0.424472,0.869598,0.968629,0.263696,0.836866
195,0.599194,0.429428,0.230312,0.117274,0.978755,0.912314,0.280604,0.476602,0.016388,0.452468,0.587608,0.576335,0.773289,0.157547,0.511317,0.529795
196,0.735800,0.628053,0.406362,0.270686,0.856782,0.097980,0.091743,0.601370,0.193138,0.523941,0.306541,0.840965,0.278975,0.985553,0.040555,0.892293
197,0.533521,0.653583,0.490876,0.993591,0.201744,0.692654,0.150761,0.227123,0.885846,0.066748,0.403141,0.289215,0.809245,0.138043,0.789561,0.757916
198,0.364735,0.033739,0.266301,0.854474,0.307739,0.472611,0.267519,0.042142,0.459191,0.363029,0.120381,0.733721,0.379377,0.121244,0.245184,0.910713

In [59]:
df[df > 0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,English,Urdu,Maths,Physics,Chemistry,Bio,PSt,Islamiat
0,0.119474,0.239085,0.012440,0.571416,0.403083,0.738606,0.276011,0.882746,0.371731,0.982237,0.384592,0.320944,0.087402,0.309585,0.260879,0.667411
1,0.430905,0.383681,0.082613,0.209430,0.358533,0.770771,0.924578,0.855662,0.115478,0.066545,0.581165,0.780201,0.048451,0.500337,0.620652,0.473355
2,0.242997,0.570807,0.778336,0.806507,0.533121,0.648477,0.275912,0.660557,0.585514,0.758866,0.095574,0.782417,0.366413,0.774236,0.707355,0.252295
3,0.501628,0.034464,0.395550,0.523063,0.225245,0.361950,0.982694,0.596087,0.783518,0.803192,0.957146,0.571894,0.107210,0.362442,0.585707,0.055925
4,0.344307,0.601175,0.918672,0.585692,0.115941,0.004124,0.405912,0.366132,0.411279,0.550334,0.855713,0.065382,0.784871,0.460713,0.326616,0.396151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,0.276460,0.619686,0.732752,0.941922,0.179101,0.533068,0.449423,0.359416,0.750122,0.295945,0.629010,0.424472,0.869598,0.968629,0.263696,0.836866
195,0.599194,0.429428,0.230312,0.117274,0.978755,0.912314,0.280604,0.476602,0.016388,0.452468,0.587608,0.576335,0.773289,0.157547,0.511317,0.529795
196,0.735800,0.628053,0.406362,0.270686,0.856782,0.097980,0.091743,0.601370,0.193138,0.523941,0.306541,0.840965,0.278975,0.985553,0.040555,0.892293
197,0.533521,0.653583,0.490876,0.993591,0.201744,0.692654,0.150761,0.227123,0.885846,0.066748,0.403141,0.289215,0.809245,0.138043,0.789561,0.757916
198,0.364735,0.033739,0.266301,0.854474,0.307739,0.472611,0.267519,0.042142,0.459191,0.363029,0.120381,0.733721,0.379377,0.121244,0.245184,0.910713

# Setting values by position

In [60]:
df.iat[0, 1] = 0

# Setting by assigning with a NumPy array:

In [61]:
df.loc[:, "D"] = np.array([5] * len(df))

In [62]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,English,Urdu,Maths,Physics,Chemistry,Bio,PSt,Islamiat,D
0,0.119474,0.000000,0.012440,0.571416,0.403083,0.738606,0.276011,0.882746,0.371731,0.982237,0.384592,0.320944,0.087402,0.309585,0.260879,0.667411,5
1,0.430905,0.383681,0.082613,0.209430,0.358533,0.770771,0.924578,0.855662,0.115478,0.066545,0.581165,0.780201,0.048451,0.500337,0.620652,0.473355,5
2,0.242997,0.570807,0.778336,0.806507,0.533121,0.648477,0.275912,0.660557,0.585514,0.758866,0.095574,0.782417,0.366413,0.774236,0.707355,0.252295,5
3,0.501628,0.034464,0.395550,0.523063,0.225245,0.361950,0.982694,0.596087,0.783518,0.803192,0.957146,0.571894,0.107210,0.362442,0.585707,0.055925,5
4,0.344307,0.601175,0.918672,0.585692,0.115941,0.004124,0.405912,0.366132,0.411279,0.550334,0.855713,0.065382,0.784871,0.460713,0.326616,0.396151,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,0.276460,0.619686,0.732752,0.941922,0.179101,0.533068,0.449423,0.359416,0.750122,0.295945,0.629010,0.424472,0.869598,0.968629,0.263696,0.836866,5
195,0.599194,0.429428,0.230312,0.117274,0.978755,0.912314,0.280604,0.476602,0.016388,0.452468,0.587608,0.576335,0.773289,0.157547,0.511317,0.529795,5
196,0.735800,0.628053,0.406362,0.270686,0.856782,0.097980,0.091743,0.601370,0.193138,0.523941,0.306541,0.840965,0.278975,0.985553,0.040555,0.892293,5
197,0.533521,0.653583,0.490876,0.993591,0.201744,0.692654,0.150761,0.227123,0.885846,0.066748,0.403141,0.289215,0.809245,0.138043,0.789561,0.757916,5
198,0.364735,0.033739,0.266301,0.854474,0.307739,0.472611,0.267519,0.042142,0.459191,0.363029,0.120381,0.733721,0.379377,0.121244,0.245184,0.910713,5

# A where operation with setting:

In [63]:
df2 = df.copy()

df2[df2 > 0] = -df2

df2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,English,Urdu,Maths,Physics,Chemistry,Bio,PSt,Islamiat,D
0,-0.119474,0.000000,-0.012440,-0.571416,-0.403083,-0.738606,-0.276011,-0.882746,-0.371731,-0.982237,-0.384592,-0.320944,-0.087402,-0.309585,-0.260879,-0.667411,-5
1,-0.430905,-0.383681,-0.082613,-0.209430,-0.358533,-0.770771,-0.924578,-0.855662,-0.115478,-0.066545,-0.581165,-0.780201,-0.048451,-0.500337,-0.620652,-0.473355,-5
2,-0.242997,-0.570807,-0.778336,-0.806507,-0.533121,-0.648477,-0.275912,-0.660557,-0.585514,-0.758866,-0.095574,-0.782417,-0.366413,-0.774236,-0.707355,-0.252295,-5
3,-0.501628,-0.034464,-0.395550,-0.523063,-0.225245,-0.361950,-0.982694,-0.596087,-0.783518,-0.803192,-0.957146,-0.571894,-0.107210,-0.362442,-0.585707,-0.055925,-5
4,-0.344307,-0.601175,-0.918672,-0.585692,-0.115941,-0.004124,-0.405912,-0.366132,-0.411279,-0.550334,-0.855713,-0.065382,-0.784871,-0.460713,-0.326616,-0.396151,-5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,-0.276460,-0.619686,-0.732752,-0.941922,-0.179101,-0.533068,-0.449423,-0.359416,-0.750122,-0.295945,-0.629010,-0.424472,-0.869598,-0.968629,-0.263696,-0.836866,-5
195,-0.599194,-0.429428,-0.230312,-0.117274,-0.978755,-0.912314,-0.280604,-0.476602,-0.016388,-0.452468,-0.587608,-0.576335,-0.773289,-0.157547,-0.511317,-0.529795,-5
196,-0.735800,-0.628053,-0.406362,-0.270686,-0.856782,-0.097980,-0.091743,-0.601370,-0.193138,-0.523941,-0.306541,-0.840965,-0.278975,-0.985553,-0.040555,-0.892293,-5
197,-0.533521,-0.653583,-0.490876,-0.993591,-0.201744,-0.692654,-0.150761,-0.227123,-0.885846,-0.066748,-0.403141,-0.289215,-0.809245,-0.138043,-0.789561,-0.757916,-5
198,-0.364735,-0.033739,-0.266301,-0.854474,-0.307739,-0.472611,-0.267519,-0.042142,-0.459191,-0.363029,-0.120381,-0.733721,-0.379377,-0.121244,-0.245184,-0.910713,-5

# DataFrame.dropna() drops any rows that have missing data

In [64]:
df.dropna(how="any")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,English,Urdu,Maths,Physics,Chemistry,Bio,PSt,Islamiat,D
0,0.119474,0.000000,0.012440,0.571416,0.403083,0.738606,0.276011,0.882746,0.371731,0.982237,0.384592,0.320944,0.087402,0.309585,0.260879,0.667411,5
1,0.430905,0.383681,0.082613,0.209430,0.358533,0.770771,0.924578,0.855662,0.115478,0.066545,0.581165,0.780201,0.048451,0.500337,0.620652,0.473355,5
2,0.242997,0.570807,0.778336,0.806507,0.533121,0.648477,0.275912,0.660557,0.585514,0.758866,0.095574,0.782417,0.366413,0.774236,0.707355,0.252295,5
3,0.501628,0.034464,0.395550,0.523063,0.225245,0.361950,0.982694,0.596087,0.783518,0.803192,0.957146,0.571894,0.107210,0.362442,0.585707,0.055925,5
4,0.344307,0.601175,0.918672,0.585692,0.115941,0.004124,0.405912,0.366132,0.411279,0.550334,0.855713,0.065382,0.784871,0.460713,0.326616,0.396151,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,0.276460,0.619686,0.732752,0.941922,0.179101,0.533068,0.449423,0.359416,0.750122,0.295945,0.629010,0.424472,0.869598,0.968629,0.263696,0.836866,5
195,0.599194,0.429428,0.230312,0.117274,0.978755,0.912314,0.280604,0.476602,0.016388,0.452468,0.587608,0.576335,0.773289,0.157547,0.511317,0.529795,5
196,0.735800,0.628053,0.406362,0.270686,0.856782,0.097980,0.091743,0.601370,0.193138,0.523941,0.306541,0.840965,0.278975,0.985553,0.040555,0.892293,5
197,0.533521,0.653583,0.490876,0.993591,0.201744,0.692654,0.150761,0.227123,0.885846,0.066748,0.403141,0.289215,0.809245,0.138043,0.789561,0.757916,5
198,0.364735,0.033739,0.266301,0.854474,0.307739,0.472611,0.267519,0.042142,0.459191,0.363029,0.120381,0.733721,0.379377,0.121244,0.245184,0.910713,5

# DataFrame.fillna() fills missing data:

In [65]:
df.fillna(value=5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,English,Urdu,Maths,Physics,Chemistry,Bio,PSt,Islamiat,D
0,0.119474,0.000000,0.012440,0.571416,0.403083,0.738606,0.276011,0.882746,0.371731,0.982237,0.384592,0.320944,0.087402,0.309585,0.260879,0.667411,5
1,0.430905,0.383681,0.082613,0.209430,0.358533,0.770771,0.924578,0.855662,0.115478,0.066545,0.581165,0.780201,0.048451,0.500337,0.620652,0.473355,5
2,0.242997,0.570807,0.778336,0.806507,0.533121,0.648477,0.275912,0.660557,0.585514,0.758866,0.095574,0.782417,0.366413,0.774236,0.707355,0.252295,5
3,0.501628,0.034464,0.395550,0.523063,0.225245,0.361950,0.982694,0.596087,0.783518,0.803192,0.957146,0.571894,0.107210,0.362442,0.585707,0.055925,5
4,0.344307,0.601175,0.918672,0.585692,0.115941,0.004124,0.405912,0.366132,0.411279,0.550334,0.855713,0.065382,0.784871,0.460713,0.326616,0.396151,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,0.276460,0.619686,0.732752,0.941922,0.179101,0.533068,0.449423,0.359416,0.750122,0.295945,0.629010,0.424472,0.869598,0.968629,0.263696,0.836866,5
195,0.599194,0.429428,0.230312,0.117274,0.978755,0.912314,0.280604,0.476602,0.016388,0.452468,0.587608,0.576335,0.773289,0.157547,0.511317,0.529795,5
196,0.735800,0.628053,0.406362,0.270686,0.856782,0.097980,0.091743,0.601370,0.193138,0.523941,0.306541,0.840965,0.278975,0.985553,0.040555,0.892293,5
197,0.533521,0.653583,0.490876,0.993591,0.201744,0.692654,0.150761,0.227123,0.885846,0.066748,0.403141,0.289215,0.809245,0.138043,0.789561,0.757916,5
198,0.364735,0.033739,0.266301,0.854474,0.307739,0.472611,0.267519,0.042142,0.459191,0.363029,0.120381,0.733721,0.379377,0.121244,0.245184,0.910713,5

# isna() gets the boolean mask where values are nan

In [66]:
pd.isna(df)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,English,Urdu,Maths,Physics,Chemistry,Bio,PSt,Islamiat,D
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
195,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
196,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
197,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
198,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

# Calculate the mean value for each column:

In [67]:
df.mean

<bound method DataFrame.mean of      Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0      0.119474    0.000000    0.012440    0.571416    0.403083    0.738606
1      0.430905    0.383681    0.082613    0.209430    0.358533    0.770771
2      0.242997    0.570807    0.778336    0.806507    0.533121    0.648477
3      0.501628    0.034464    0.395550    0.523063    0.225245    0.361950
4      0.344307    0.601175    0.918672    0.585692    0.115941    0.004124
..          ...         ...         ...         ...         ...         ...
194    0.276460    0.619686    0.732752    0.941922    0.179101    0.533068
195    0.599194    0.429428    0.230312    0.117274    0.978755    0.912314
196    0.735800    0.628053    0.406362    0.270686    0.856782    0.097980
197    0.533521    0.653583    0.490876    0.993591    0.201744    0.692654
198    0.364735    0.033739    0.266301    0.854474    0.307739    0.472611

     Unnamed: 6  Unnamed: 7   English      Urdu     Maths   Physics  \
0      0.276011    0.882746  0.371731  0.982237  0.384592  0.320944
1      0.924578    0.855662  0.115478  0.066545  0.581165  0.780201
2      0.275912    0.660557  0.585514  0.758866  0.095574  0.782417
3      0.982694    0.596087  0.783518  0.803192  0.957146  0.571894
4      0.405912    0.366132  0.411279  0.550334  0.855713  0.065382
..          ...         ...       ...       ...       ...       ...
194    0.449423    0.359416  0.750122  0.295945  0.629010  0.424472
195    0.280604    0.476602  0.016388  0.452468  0.587608  0.576335
196    0.091743    0.601370  0.193138  0.523941  0.306541  0.840965
197    0.150761    0.227123  0.885846  0.066748  0.403141  0.289215
198    0.267519    0.042142  0.459191  0.363029  0.120381  0.733721

     Chemistry       Bio       PSt  Islamiat  D
0     0.087402  0.309585  0.260879  0.667411  5
1     0.048451  0.500337  0.620652  0.473355  5
2     0.366413  0.774236  0.707355  0.252295  5
3     0.107210  0.362442  0.585707  0.055925  5
4     0.784871  0.460713  0.326616  0.396151  5
..         ...       ...       ...       ... ..
194   0.869598  0.968629  0.263696  0.836866  5
195   0.773289  0.157547  0.511317  0.529795  5
196   0.278975  0.985553  0.040555  0.892293  5
197   0.809245  0.138043  0.789561  0.757916  5
198   0.379377  0.121244  0.245184  0.910713  5

[199 rows x 17 columns]>

# Calculate the mean value for each row:

In [68]:
df.mean(axis=1)

0      0.669915
1      0.717786
2      0.814082
3      0.755748
4      0.717236
         ...
194    0.831186
195    0.742896
196    0.750043
197    0.769622
198    0.643653
Length: 199, dtype: float64

# DataFrame.agg() and DataFrame.transform() applies a user defined function that reduces or broadcasts its result respectively.

In [69]:
df.agg(lambda x: np.mean(x) * 5.6)

Unnamed: 0     2.712762
Unnamed: 1     2.828743
Unnamed: 2     2.964626
Unnamed: 3     2.887867
Unnamed: 4     2.922258
Unnamed: 5     2.929552
Unnamed: 6     2.704311
Unnamed: 7     2.922288
English        2.922474
Urdu           2.641387
Maths          2.666532
Physics        2.875530
Chemistry      2.728628
Bio            2.815767
PSt            2.776693
Islamiat       2.823019
D             28.000000
dtype: float64

In [70]:
df.transform(lambda x: x * 101.2)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,English,Urdu,Maths,Physics,Chemistry,Bio,PSt,Islamiat,D
0,12.090798,0.000000,1.258920,57.827299,40.792003,74.746911,27.932349,89.333924,37.619200,99.402368,38.920713,32.479555,8.845072,31.330036,26.400917,67.541985,506.0
1,43.607622,38.828492,8.360456,21.194312,36.283527,78.002013,93.567266,86.592967,11.686405,6.734341,58.813878,78.956333,4.903241,50.634133,62.810023,47.903516,506.0
2,24.591316,57.765699,78.767641,81.618483,53.951799,65.625912,27.922301,66.848419,59.254048,76.797273,9.672085,79.180611,37.080997,78.352667,71.584319,25.532292,506.0
3,50.764737,3.487799,40.029610,52.933960,22.794765,36.629317,99.448663,60.323955,79.292015,81.283043,96.863212,57.875674,10.849688,36.679179,59.273582,5.659561,506.0
4,34.843882,60.838942,92.969635,59.272019,11.733246,0.417330,41.078296,37.052599,41.621405,55.693762,86.598189,6.616614,79.428936,46.624130,33.053540,40.090517,506.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,27.977721,62.712267,74.154470,95.322471,18.124973,53.946466,45.481629,36.372910,75.912345,29.949675,63.655823,42.956547,88.003364,98.025303,26.686074,84.690824,506.0
195,60.638434,43.458086,23.307566,11.868088,99.049974,92.326176,28.397091,48.232163,1.658434,45.789736,59.465915,58.325069,78.256887,15.943783,51.745308,53.615266,506.0
196,74.462978,63.558966,41.123864,27.393455,86.706326,9.915559,9.284420,60.858612,19.545599,53.022828,31.021972,85.105671,28.232233,99.737913,4.104208,90.300058,506.0
197,53.992307,66.142587,49.676614,100.551359,20.416499,70.096613,15.256972,22.984893,89.647600,6.754867,40.797843,29.268598,81.895575,13.969976,79.903526,76.701119,506.0
198,36.911203,3.414437,26.949647,86.472760,31.143209,47.828259,27.072962,4.264740,46.470158,36.738581,12.182529,74.252561,38.392910,12.269899,24.812658,92.164158,506.0

In [71]:
df.median

<bound method DataFrame.median of      Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0      0.119474    0.000000    0.012440    0.571416    0.403083    0.738606
1      0.430905    0.383681    0.082613    0.209430    0.358533    0.770771
2      0.242997    0.570807    0.778336    0.806507    0.533121    0.648477
3      0.501628    0.034464    0.395550    0.523063    0.225245    0.361950
4      0.344307    0.601175    0.918672    0.585692    0.115941    0.004124
..          ...         ...         ...         ...         ...         ...
194    0.276460    0.619686    0.732752    0.941922    0.179101    0.533068
195    0.599194    0.429428    0.230312    0.117274    0.978755    0.912314
196    0.735800    0.628053    0.406362    0.270686    0.856782    0.097980
197    0.533521    0.653583    0.490876    0.993591    0.201744    0.692654
198    0.364735    0.033739    0.266301    0.854474    0.307739    0.472611

     Unnamed: 6  Unnamed: 7   English      Urdu     Maths   Physics  \
0      0.276011    0.882746  0.371731  0.982237  0.384592  0.320944
1      0.924578    0.855662  0.115478  0.066545  0.581165  0.780201
2      0.275912    0.660557  0.585514  0.758866  0.095574  0.782417
3      0.982694    0.596087  0.783518  0.803192  0.957146  0.571894
4      0.405912    0.366132  0.411279  0.550334  0.855713  0.065382
..          ...         ...       ...       ...       ...       ...
194    0.449423    0.359416  0.750122  0.295945  0.629010  0.424472
195    0.280604    0.476602  0.016388  0.452468  0.587608  0.576335
196    0.091743    0.601370  0.193138  0.523941  0.306541  0.840965
197    0.150761    0.227123  0.885846  0.066748  0.403141  0.289215
198    0.267519    0.042142  0.459191  0.363029  0.120381  0.733721

     Chemistry       Bio       PSt  Islamiat  D
0     0.087402  0.309585  0.260879  0.667411  5
1     0.048451  0.500337  0.620652  0.473355  5
2     0.366413  0.774236  0.707355  0.252295  5
3     0.107210  0.362442  0.585707  0.055925  5
4     0.784871  0.460713  0.326616  0.396151  5
..         ...       ...       ...       ... ..
194   0.869598  0.968629  0.263696  0.836866  5
195   0.773289  0.157547  0.511317  0.529795  5
196   0.278975  0.985553  0.040555  0.892293  5
197   0.809245  0.138043  0.789561  0.757916  5
198   0.379377  0.121244  0.245184  0.910713  5

[199 rows x 17 columns]>

In [72]:
df.mode

<bound method DataFrame.mode of      Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0      0.119474    0.000000    0.012440    0.571416    0.403083    0.738606
1      0.430905    0.383681    0.082613    0.209430    0.358533    0.770771
2      0.242997    0.570807    0.778336    0.806507    0.533121    0.648477
3      0.501628    0.034464    0.395550    0.523063    0.225245    0.361950
4      0.344307    0.601175    0.918672    0.585692    0.115941    0.004124
..          ...         ...         ...         ...         ...         ...
194    0.276460    0.619686    0.732752    0.941922    0.179101    0.533068
195    0.599194    0.429428    0.230312    0.117274    0.978755    0.912314
196    0.735800    0.628053    0.406362    0.270686    0.856782    0.097980
197    0.533521    0.653583    0.490876    0.993591    0.201744    0.692654
198    0.364735    0.033739    0.266301    0.854474    0.307739    0.472611

     Unnamed: 6  Unnamed: 7   English      Urdu     Maths   Physics  \
0      0.276011    0.882746  0.371731  0.982237  0.384592  0.320944
1      0.924578    0.855662  0.115478  0.066545  0.581165  0.780201
2      0.275912    0.660557  0.585514  0.758866  0.095574  0.782417
3      0.982694    0.596087  0.783518  0.803192  0.957146  0.571894
4      0.405912    0.366132  0.411279  0.550334  0.855713  0.065382
..          ...         ...       ...       ...       ...       ...
194    0.449423    0.359416  0.750122  0.295945  0.629010  0.424472
195    0.280604    0.476602  0.016388  0.452468  0.587608  0.576335
196    0.091743    0.601370  0.193138  0.523941  0.306541  0.840965
197    0.150761    0.227123  0.885846  0.066748  0.403141  0.289215
198    0.267519    0.042142  0.459191  0.363029  0.120381  0.733721

     Chemistry       Bio       PSt  Islamiat  D
0     0.087402  0.309585  0.260879  0.667411  5
1     0.048451  0.500337  0.620652  0.473355  5
2     0.366413  0.774236  0.707355  0.252295  5
3     0.107210  0.362442  0.585707  0.055925  5
4     0.784871  0.460713  0.326616  0.396151  5
..         ...       ...       ...       ... ..
194   0.869598  0.968629  0.263696  0.836866  5
195   0.773289  0.157547  0.511317  0.529795  5
196   0.278975  0.985553  0.040555  0.892293  5
197   0.809245  0.138043  0.789561  0.757916  5
198   0.379377  0.121244  0.245184  0.910713  5

[199 rows x 17 columns]>

# Concatenating pandas objects together row-wise with concat():

In [74]:
df = pd.DataFrame(np.random.randn(10, 4))
df

          0         1         2         3
0 -2.584341  1.647171  0.797016  0.644898
1 -1.676099 -1.312164 -0.779453  0.669483
2 -1.490160  0.512368 -0.479858  1.756942
3  0.358882  1.003274  1.043870 -1.133735
4  0.666016 -0.279252  1.146745  0.502149
5  0.546438  1.082643  1.280902 -0.612302
6 -1.372233 -0.638160 -1.254429 -0.177401
7  1.771069 -0.190007 -1.274773 -0.128874
8  0.350400 -0.554932 -0.383457 -0.342560
9  0.286392 -1.365083 -1.104687  0.060574