In [9]:
import numpy as np

import pandas as pd

In [15]:
df=pd.read_csv("disney movie total gross.csv")

In [11]:
df.tail()

,Movie Title,Date Released,Genre,MPAA Rating,Total Gross,Inflation Adjusted Gross
574,The Light Between Oceans,02/09/2016,Drama,PG-13,12545979,12545979
575,Queen of Katwe,23/09/2016,Drama,PG,8874389,8874389
576,Doctor Strange,04/11/2016,Adventure,PG-13,232532923,232532923
577,Moana,23/11/2016,Adventure,PG,246082029,246082029
578,Rogue One: A Star Wars Story,16/12/2016,Adventure,PG-13,529483936,529483936

In [12]:
df.head()

,Movie Title,Date Released,Genre,MPAA Rating,Total Gross,Inflation Adjusted Gross
0,Snow White and the Seven Dwarfs,21/12/1937,Musical,G,184925485,5228953251
1,Pinocchio,09/02/1940,Adventure,G,84300000,2188229052
2,Fantasia,13/11/1940,Musical,G,83320000,2187090808
3,Song of the South,12/11/1946,Adventure,G,65000000,1078510579
4,Cinderella,15/02/1950,Drama,G,85000000,920608730

In [13]:
df = pd.Series([1, 3, 5, np.nan, 6, 8])

In [14]:
series

NameError: name 'series' is not defined

In [7]:
df= pd.Series([1, 3, 5])

In [8]:
dates = pd.date_range("19350101", periods=10)

In [9]:
dates

DatetimeIndex(['1935-01-01', '1935-01-02', '1935-01-03', '1935-01-04',
               '1935-01-05', '1935-01-06', '1935-01-07', '1935-01-08',
               '1935-01-09', '1935-01-10'],
              dtype='datetime64[ns]', freq='D')

In [21]:
df = pd.DataFrame(
    {
        "movietitle": "snow white","cinderalla"
        "B": pd.Timestamp("20130102"),
        "Genre": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["Musical", "Adventure", "Musical", "drama"]),
        "F": "film",
    }
)

In [22]:
df

   movietitle cinderallaB  Genre  D          E     F
0  snow white  2013-01-02    1.0  3    Musical  film
1  snow white  2013-01-02    1.0  3  Adventure  film
2  snow white  2013-01-02    1.0  3    Musical  film
3  snow white  2013-01-02    1.0  3      drama  film

In [20]:
df

   movietitle          B  Genre  D          E     F
0  snow white 2013-01-02    1.0  3    Musical  film
1  snow white 2013-01-02    1.0  3  Adventure  film
2  snow white 2013-01-02    1.0  3    Musical  film
3  snow white 2013-01-02    1.0  3      drama  film

In [11]:
dataframe

NameError: name 'dataframe' is not defined

In [12]:
df

   movietitle          B  Genre  D      E     F
0         1.0 2013-01-02    1.0  3   test  film
1         1.0 2013-01-02    1.0  3  train  film
2         1.0 2013-01-02    1.0  3   test  film
3         1.0 2013-01-02    1.0  3  train  film

In [13]:
df.index

Index([0, 1, 2, 3], dtype='int64')

In [14]:

df.columns

Index(['movietitle', 'B', 'Genre', 'D', 'E', 'F'], dtype='object')

In [15]:
df[0:39]

   movietitle          B  Genre  D      E     F
0         1.0 2013-01-02    1.0  3   test  film
1         1.0 2013-01-02    1.0  3  train  film
2         1.0 2013-01-02    1.0  3   test  film
3         1.0 2013-01-02    1.0  3  train  film

In [1]:
df.T

NameError: name 'df' is not defined

In [2]:
df

NameError: name 'df' is not defined

In [3]:
df=pd.read_csv("disney movie total gross.csv")

NameError: name 'pd' is not defined

In [4]:
import numpy as np

import pandas as pd

In [5]:
df=pd.read_csv("disney movie total gross.csv")

In [7]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,569,570,571,572,573,574,575,576,577,578
Movie Title,Snow White and the Seven Dwarfs,Pinocchio,Fantasia,Song of the South,Cinderella,"20,000 Leagues Under the Sea",Lady and the Tramp,Sleeping Beauty,101 Dalmatians,The Absent Minded Professor,...,Captain America: Civil War,Alice Through the Looking Glass,Finding Dory,The BFG,Pete’s Dragon,The Light Between Oceans,Queen of Katwe,Doctor Strange,Moana,Rogue One: A Star Wars Story
Date Released,21/12/1937,09/02/1940,13/11/1940,12/11/1946,15/02/1950,23/12/1954,22/06/1955,29/01/1959,25/01/1961,16/03/1961,...,06/05/2016,27/05/2016,17/06/2016,01/07/2016,12/08/2016,02/09/2016,23/09/2016,04/11/2016,23/11/2016,16/12/2016
Genre,Musical,Adventure,Musical,Adventure,Drama,Adventure,Drama,Drama,Comedy,Comedy,...,Action,Adventure,Adventure,Adventure,Adventure,Drama,Drama,Adventure,Adventure,Adventure
MPAA Rating,G,G,G,G,G,Unknown,G,Unknown,G,Unknown,...,PG-13,PG,PG,PG,PG,PG-13,PG,PG-13,PG,PG-13
Total Gross,184925485,84300000,83320000,65000000,85000000,28200000,93600000,9464608,153000000,25381407,...,408084349,77042381,486295561,55483770,76233151,12545979,8874389,232532923,246082029,529483936
Inflation Adjusted Gross,5228953251,2188229052,2187090808,1078510579,920608730,528279994,1236035515,21505832,1362870985,310094574,...,408084349,77042381,486295561,55483770,76233151,12545979,8874389,232532923,246082029,529483936

In [8]:
df.head

<bound method NDFrame.head of                          Movie Title Date Released      Genre MPAA Rating  \
0    Snow White and the Seven Dwarfs    21/12/1937    Musical           G
1                          Pinocchio    09/02/1940  Adventure           G
2                           Fantasia    13/11/1940    Musical           G
3                  Song of the South    12/11/1946  Adventure           G
4                         Cinderella    15/02/1950      Drama           G
..                               ...           ...        ...         ...
574         The Light Between Oceans    02/09/2016      Drama       PG-13
575                   Queen of Katwe    23/09/2016      Drama          PG
576                   Doctor Strange    04/11/2016  Adventure       PG-13
577                            Moana    23/11/2016  Adventure          PG
578     Rogue One: A Star Wars Story    16/12/2016  Adventure       PG-13

     Total Gross  Inflation Adjusted Gross
0      184925485                5228953251
1       84300000                2188229052
2       83320000                2187090808
3       65000000                1078510579
4       85000000                 920608730
..           ...                       ...
574     12545979                  12545979
575      8874389                   8874389
576    232532923                 232532923
577    246082029                 246082029
578    529483936                 529483936

[579 rows x 6 columns]>

In [9]:
df.tail

<bound method NDFrame.tail of                          Movie Title Date Released      Genre MPAA Rating  \
0    Snow White and the Seven Dwarfs    21/12/1937    Musical           G
1                          Pinocchio    09/02/1940  Adventure           G
2                           Fantasia    13/11/1940    Musical           G
3                  Song of the South    12/11/1946  Adventure           G
4                         Cinderella    15/02/1950      Drama           G
..                               ...           ...        ...         ...
574         The Light Between Oceans    02/09/2016      Drama       PG-13
575                   Queen of Katwe    23/09/2016      Drama          PG
576                   Doctor Strange    04/11/2016  Adventure       PG-13
577                            Moana    23/11/2016  Adventure          PG
578     Rogue One: A Star Wars Story    16/12/2016  Adventure       PG-13

     Total Gross  Inflation Adjusted Gross
0      184925485                5228953251
1       84300000                2188229052
2       83320000                2187090808
3       65000000                1078510579
4       85000000                 920608730
..           ...                       ...
574     12545979                  12545979
575      8874389                   8874389
576    232532923                 232532923
577    246082029                 246082029
578    529483936                 529483936

[579 rows x 6 columns]>

In [10]:
df.sort_index(axis=1, ascending=False)

,Total Gross,Movie Title,MPAA Rating,Inflation Adjusted Gross,Genre,Date Released
0,184925485,Snow White and the Seven Dwarfs,G,5228953251,Musical,21/12/1937
1,84300000,Pinocchio,G,2188229052,Adventure,09/02/1940
2,83320000,Fantasia,G,2187090808,Musical,13/11/1940
3,65000000,Song of the South,G,1078510579,Adventure,12/11/1946
4,85000000,Cinderella,G,920608730,Drama,15/02/1950
...,...,...,...,...,...,...
574,12545979,The Light Between Oceans,PG-13,12545979,Drama,02/09/2016
575,8874389,Queen of Katwe,PG,8874389,Drama,23/09/2016
576,232532923,Doctor Strange,PG-13,232532923,Adventure,04/11/2016
577,246082029,Moana,PG,246082029,Adventure,23/11/2016
578,529483936,Rogue One: A Star Wars Story,PG-13,529483936,Adventure,16/12/2016

In [13]:
df = pd.DataFrame(
    {
        "movietitle": "snow white","cinderalla"
        "B": pd.Timestamp("20130102"),
        "Genre": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["Musical", "Adventure", "Musical", "drama"]),
        "F": "film",
    }
)

In [14]:
df

   movietitle cinderallaB  Genre  D          E     F
0  snow white  2013-01-02    1.0  3    Musical  film
1  snow white  2013-01-02    1.0  3  Adventure  film
2  snow white  2013-01-02    1.0  3    Musical  film
3  snow white  2013-01-02    1.0  3      drama  film

In [15]:
df[0:3]

   movietitle cinderallaB  Genre  D          E     F
0  snow white  2013-01-02    1.0  3    Musical  film
1  snow white  2013-01-02    1.0  3  Adventure  film
2  snow white  2013-01-02    1.0  3    Musical  film

In [17]:
df.loc[:, ["movietitle", "D"]]

   movietitle  D
0  snow white  3
1  snow white  3
2  snow white  3
3  snow white  3

In [19]:
df.sort_index(axis=1, ascending=False)

   movietitle cinderallaB  Genre     F          E  D
0  snow white  2013-01-02    1.0  film    Musical  3
1  snow white  2013-01-02    1.0  film  Adventure  3
2  snow white  2013-01-02    1.0  film    Musical  3
3  snow white  2013-01-02    1.0  film      drama  3

In [20]:
df.T

,0,1,2,3
movietitle,snow white,snow white,snow white,snow white
cinderallaB,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00
Genre,1.0,1.0,1.0,1.0
D,3,3,3,3
E,Musical,Adventure,Musical,drama
F,film,film,film,film

In [23]:
pd.read_csv("disney movie total gross.csv")

,Movie Title,Date Released,Genre,MPAA Rating,Total Gross,Inflation Adjusted Gross
0,Snow White and the Seven Dwarfs,21/12/1937,Musical,G,184925485,5228953251
1,Pinocchio,09/02/1940,Adventure,G,84300000,2188229052
2,Fantasia,13/11/1940,Musical,G,83320000,2187090808
3,Song of the South,12/11/1946,Adventure,G,65000000,1078510579
4,Cinderella,15/02/1950,Drama,G,85000000,920608730
...,...,...,...,...,...,...
574,The Light Between Oceans,02/09/2016,Drama,PG-13,12545979,12545979
575,Queen of Katwe,23/09/2016,Drama,PG,8874389,8874389
576,Doctor Strange,04/11/2016,Adventure,PG-13,232532923,232532923
577,Moana,23/11/2016,Adventure,PG,246082029,246082029
578,Rogue One: A Star Wars Story,16/12/2016,Adventure,PG-13,529483936,529483936

In [25]:
df.to_excel("data.xlsx")

In [26]:
pd.read_excel("data.xlsx")

   Unnamed: 0  movietitle cinderallaB  Genre  D          E     F
0           0  snow white  2013-01-02      1  3    Musical  film
1           1  snow white  2013-01-02      1  3  Adventure  film
2           2  snow white  2013-01-02      1  3    Musical  film
3           3  snow white  2013-01-02      1  3      drama  film

In [27]:
dfnew = pd.read_csv("disney movie total gross.csv")

In [28]:
dfnew

,Movie Title,Date Released,Genre,MPAA Rating,Total Gross,Inflation Adjusted Gross
0,Snow White and the Seven Dwarfs,21/12/1937,Musical,G,184925485,5228953251
1,Pinocchio,09/02/1940,Adventure,G,84300000,2188229052
2,Fantasia,13/11/1940,Musical,G,83320000,2187090808
3,Song of the South,12/11/1946,Adventure,G,65000000,1078510579
4,Cinderella,15/02/1950,Drama,G,85000000,920608730
...,...,...,...,...,...,...
574,The Light Between Oceans,02/09/2016,Drama,PG-13,12545979,12545979
575,Queen of Katwe,23/09/2016,Drama,PG,8874389,8874389
576,Doctor Strange,04/11/2016,Adventure,PG-13,232532923,232532923
577,Moana,23/11/2016,Adventure,PG,246082029,246082029
578,Rogue One: A Star Wars Story,16/12/2016,Adventure,PG-13,529483936,529483936

In [17]:
df1 = pd.read_excel("data.xlsx")

   Unnamed: 0  movietitle cinderallaB  Genre  D          E     F
0           0  snow white  2013-01-02      1  3    Musical  film
1           1  snow white  2013-01-02      1  3  Adventure  film
2           2  snow white  2013-01-02      1  3    Musical  film
3           3  snow white  2013-01-02      1  3      drama  film

In [18]:
df.info

<bound method DataFrame.info of                          Movie Title Date Released      Genre MPAA Rating  \
0    Snow White and the Seven Dwarfs    21/12/1937    Musical           G
1                          Pinocchio    09/02/1940  Adventure           G
2                           Fantasia    13/11/1940    Musical           G
3                  Song of the South    12/11/1946  Adventure           G
4                         Cinderella    15/02/1950      Drama           G
..                               ...           ...        ...         ...
574         The Light Between Oceans    02/09/2016      Drama       PG-13
575                   Queen of Katwe    23/09/2016      Drama          PG
576                   Doctor Strange    04/11/2016  Adventure       PG-13
577                            Moana    23/11/2016  Adventure          PG
578     Rogue One: A Star Wars Story    16/12/2016  Adventure       PG-13

     Total Gross  Inflation Adjusted Gross
0      184925485                5228953251
1       84300000                2188229052
2       83320000                2187090808
3       65000000                1078510579
4       85000000                 920608730
..           ...                       ...
574     12545979                  12545979
575      8874389                   8874389
576    232532923                 232532923
577    246082029                 246082029
578    529483936                 529483936

[579 rows x 6 columns]>

In [19]:
df.sort_values("Total Gross", ascending=True)

,Movie Title,Date Released,Genre,MPAA Rating,Total Gross,Inflation Adjusted Gross
355,Frank McKlusky C.I.,01/01/2002,Unknown,Unknown,0,0
20,The Many Adventures of Winnie the Pooh,11/03/1977,Unknown,Unknown,0,0
29,Condorman,07/08/1981,Action,Unknown,0,0
27,Amy,20/03/1981,Drama,Unknown,0,0
511,Zokkomon,22/04/2011,Adventure,PG,2815,2984
...,...,...,...,...,...,...
558,Avengers: Age of Ultron,01/05/2015,Action,PG-13,459005868,459005868
571,Finding Dory,17/06/2016,Adventure,PG,486295561,486295561
578,Rogue One: A Star Wars Story,16/12/2016,Adventure,PG-13,529483936,529483936
524,The Avengers,04/05/2012,Action,PG-13,623279547,660081224
564,Star Wars Ep. VII: The Force Awakens,18/12/2015,Adventure,PG-13,936662225,936662225

In [20]:
df.sort_index(ascending=False)

,Movie Title,Date Released,Genre,MPAA Rating,Total Gross,Inflation Adjusted Gross
578,Rogue One: A Star Wars Story,16/12/2016,Adventure,PG-13,529483936,529483936
577,Moana,23/11/2016,Adventure,PG,246082029,246082029
576,Doctor Strange,04/11/2016,Adventure,PG-13,232532923,232532923
575,Queen of Katwe,23/09/2016,Drama,PG,8874389,8874389
574,The Light Between Oceans,02/09/2016,Drama,PG-13,12545979,12545979
...,...,...,...,...,...,...
4,Cinderella,15/02/1950,Drama,G,85000000,920608730
3,Song of the South,12/11/1946,Adventure,G,65000000,1078510579
2,Fantasia,13/11/1940,Musical,G,83320000,2187090808
1,Pinocchio,09/02/1940,Adventure,G,84300000,2188229052
0,Snow White and the Seven Dwarfs,21/12/1937,Musical,G,184925485,5228953251

In [22]:
df.rename(columns={"Movie Title":"MOVIE TITLE","Date Released","RELEASED DATE"},inplace=True)

SyntaxError: ':' expected after dictionary key (1381028010.py, line 1)

In [24]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,569,570,571,572,573,574,575,576,577,578
Movie Title,Snow White and the Seven Dwarfs,Pinocchio,Fantasia,Song of the South,Cinderella,"20,000 Leagues Under the Sea",Lady and the Tramp,Sleeping Beauty,101 Dalmatians,The Absent Minded Professor,...,Captain America: Civil War,Alice Through the Looking Glass,Finding Dory,The BFG,Pete’s Dragon,The Light Between Oceans,Queen of Katwe,Doctor Strange,Moana,Rogue One: A Star Wars Story
Date Released,21/12/1937,09/02/1940,13/11/1940,12/11/1946,15/02/1950,23/12/1954,22/06/1955,29/01/1959,25/01/1961,16/03/1961,...,06/05/2016,27/05/2016,17/06/2016,01/07/2016,12/08/2016,02/09/2016,23/09/2016,04/11/2016,23/11/2016,16/12/2016
Genre,Musical,Adventure,Musical,Adventure,Drama,Adventure,Drama,Drama,Comedy,Comedy,...,Action,Adventure,Adventure,Adventure,Adventure,Drama,Drama,Adventure,Adventure,Adventure
MPAA Rating,G,G,G,G,G,Unknown,G,Unknown,G,Unknown,...,PG-13,PG,PG,PG,PG,PG-13,PG,PG-13,PG,PG-13
Total Gross,184925485,84300000,83320000,65000000,85000000,28200000,93600000,9464608,153000000,25381407,...,408084349,77042381,486295561,55483770,76233151,12545979,8874389,232532923,246082029,529483936
Inflation Adjusted Gross,5228953251,2188229052,2187090808,1078510579,920608730,528279994,1236035515,21505832,1362870985,310094574,...,408084349,77042381,486295561,55483770,76233151,12545979,8874389,232532923,246082029,529483936

In [27]:
df.describe

<bound method NDFrame.describe of                          Movie Title Date Released      Genre MPAA Rating  \
0    Snow White and the Seven Dwarfs    21/12/1937    Musical           G
1                          Pinocchio    09/02/1940  Adventure           G
2                           Fantasia    13/11/1940    Musical           G
3                  Song of the South    12/11/1946  Adventure           G
4                         Cinderella    15/02/1950      Drama           G
..                               ...           ...        ...         ...
574         The Light Between Oceans    02/09/2016      Drama       PG-13
575                   Queen of Katwe    23/09/2016      Drama          PG
576                   Doctor Strange    04/11/2016  Adventure       PG-13
577                            Moana    23/11/2016  Adventure          PG
578     Rogue One: A Star Wars Story    16/12/2016  Adventure       PG-13

     Total Gross  Inflation Adjusted Gross
0      184925485                5228953251
1       84300000                2188229052
2       83320000                2187090808
3       65000000                1078510579
4       85000000                 920608730
..           ...                       ...
574     12545979                  12545979
575      8874389                   8874389
576    232532923                 232532923
577    246082029                 246082029
578    529483936                 529483936

[579 rows x 6 columns]>