In [1]:
import pandas as pd
file = pd.read_excel("practice_dataset.xlsx")
print(file)

     Age  Salary  Gender  Experience_Years Education_Level    City  Job_Role  \
0     18   63930  Female                 5     High School  City_B     Clerk
1     21   76774  Female                19          Master  City_B  Engineer
2     21   58651    Male                29     High School  City_B     Clerk
3     57   92885    Male                15          Master  City_D  Engineer
4     27   45997  Female                19     High School  City_D  Engineer
..   ...     ...     ...               ...             ...     ...       ...
195   41   32679    Male                 2        Bachelor  City_B   Manager
196   50  106723    Male                27             PhD  City_D   Analyst
197   29  100486  Female                 4     High School  City_D     Clerk
198   58   61222  Female                26        Bachelor  City_B   Analyst
199   38   98201    Male                19     High School  City_C     Clerk

     Work_Hours_Per_Week
0                     32
1                     37
2                     49
3                     39
4                     30
..                   ...
195                   31
196                   33
197                   46
198                   33
199                   35

[200 rows x 8 columns]

## File head

In [2]:
print(file.head(10))

   Age  Salary  Gender  Experience_Years Education_Level    City  Job_Role  \
0   18   63930  Female                 5     High School  City_B     Clerk
1   21   76774  Female                19          Master  City_B  Engineer
2   21   58651    Male                29     High School  City_B     Clerk
3   57   92885    Male                15          Master  City_D  Engineer
4   27   45997  Female                19     High School  City_D  Engineer
5   37   95180    Male                 2     High School  City_A  Engineer
6   39  104498    Male                13          Master  City_A   Manager
7   54   93003  Female                 1        Bachelor  City_B     Clerk
8   41  115971    Male                10     High School  City_B   Analyst
9   24   64009  Female                17             PhD  City_A   Manager

   Work_Hours_Per_Week
0                   32
1                   37
2                   49
3                   39
4                   30
5                   46
6                   47
7                   38
8                   49
9                   45

## **Generating File_info**

In [3]:
print(file.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  200 non-null    int64
 1   Salary               200 non-null    int64
 2   Gender               200 non-null    object
 3   Experience_Years     200 non-null    int64
 4   Education_Level      200 non-null    object
 5   City                 200 non-null    object
 6   Job_Role             200 non-null    object
 7   Work_Hours_Per_Week  200 non-null    int64
dtypes: int64(4), object(4)
memory usage: 12.6+ KB
None

## **Generating file columns**

In [4]:
print(file.columns)

Index(['Age', 'Salary', 'Gender', 'Experience_Years', 'Education_Level',
       'City', 'Job_Role', 'Work_Hours_Per_Week'],
      dtype='object')

## **Generate Tails**

In [5]:
print(file.tail(10))

     Age  Salary  Gender  Experience_Years Education_Level    City Job_Role  \
190   30   75463    Male                 2          Master  City_C  Manager
191   56   96589  Female                 6          Master  City_B    Clerk
192   53   49361  Female                 8        Bachelor  City_D  Manager
193   40   51875    Male                 1             PhD  City_B  Analyst
194   23   66661    Male                27             PhD  City_D    Clerk
195   41   32679    Male                 2        Bachelor  City_B  Manager
196   50  106723    Male                27             PhD  City_D  Analyst
197   29  100486  Female                 4     High School  City_D    Clerk
198   58   61222  Female                26        Bachelor  City_B  Analyst
199   38   98201    Male                19     High School  City_C    Clerk

     Work_Hours_Per_Week
190                   32
191                   31
192                   34
193                   38
194                   48
195                   31
196                   33
197                   46
198                   33
199                   35

## **describe the dataset**

In [6]:
print(file.describe())

              Age         Salary  Experience_Years  Work_Hours_Per_Week
count  200.000000     200.000000        200.000000           200.000000
mean    38.110000   78343.185000         14.905000            39.700000
std     12.817933   25908.587651          8.508699             6.130081
min     18.000000   30894.000000          1.000000            30.000000
25%     28.000000   55852.000000          7.000000            34.000000
50%     37.500000   78744.500000         15.000000            40.000000
75%     50.000000  100550.500000         22.000000            46.000000
max     59.000000  119987.000000         29.000000            49.000000

## **slicing the dataset**
Slice rows based on a condition in a column


 slicing with a condition

In [7]:
sliced_data_condition = file[file['Salary'] > 50000]  
print(sliced_data_condition)

     Age  Salary  Gender  Experience_Years Education_Level    City  Job_Role  \
0     18   63930  Female                 5     High School  City_B     Clerk
1     21   76774  Female                19          Master  City_B  Engineer
2     21   58651    Male                29     High School  City_B     Clerk
3     57   92885    Male                15          Master  City_D  Engineer
5     37   95180    Male                 2     High School  City_A  Engineer
..   ...     ...     ...               ...             ...     ...       ...
194   23   66661    Male                27             PhD  City_D     Clerk
196   50  106723    Male                27             PhD  City_D   Analyst
197   29  100486  Female                 4     High School  City_D     Clerk
198   58   61222  Female                26        Bachelor  City_B   Analyst
199   38   98201    Male                19     High School  City_C     Clerk

     Work_Hours_Per_Week
0                     32
1                     37
2                     49
3                     39
5                     46
..                   ...
194                   48
196                   33
197                   46
198                   33
199                   35

[165 rows x 8 columns]

## **Select rows where the value in 'Age' column matches the first value in 'Age' column**

In [8]:
sliced_data = file.loc[file['Age'] == 43]
print(sliced_data)

     Age  Salary  Gender  Experience_Years Education_Level    City Job_Role  \
20    43   32121  Female                 1     High School  City_C  Manager
162   43  113725    Male                 2          Master  City_D  Analyst

     Work_Hours_Per_Week
20                    32
162                   37

## ***Selection by position***
if a DataFrame has rows at positions 0, 1, 2, 3, etc., then df.iloc[3] will return the row at position 3 (which is the 4th row).

In [3]:
file.iloc[0]

Age                             18
Salary                       63930
Gender                      Female
Experience_Years                 5
Education_Level        High School
City                        City_B
Job_Role                     Clerk
Work_Hours_Per_Week             32
Name: 0, dtype: object

## ***Integer slices acts similar to NumPy/Python:***

In [7]:
file.iloc[0:10, 10:15]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## ***Lists of integer position locations:***

In [17]:

file.iloc[[66,10,21], [3,5]]

    Experience_Years    City
66                24  City_C
10                 3  City_A
21                 6  City_D

## ***For slicing rows explicitly:***

In [22]:

file.iloc[0:10, :]

,Age,Salary,Gender,Experience_Years,Education_Level,City,Job_Role,Work_Hours_Per_Week
0,18,63930,Female,5,High School,City_B,Clerk,32
1,21,76774,Female,19,Master,City_B,Engineer,37
2,21,58651,Male,29,High School,City_B,Clerk,49
3,57,92885,Male,15,Master,City_D,Engineer,39
4,27,45997,Female,19,High School,City_D,Engineer,30
5,37,95180,Male,2,High School,City_A,Engineer,46
6,39,104498,Male,13,Master,City_A,Manager,47
7,54,93003,Female,1,Bachelor,City_B,Clerk,38
8,41,115971,Male,10,High School,City_B,Analyst,49
9,24,64009,Female,17,PhD,City_A,Manager,45

## ***For slicing columns explicitly:***

In [28]:
file.iloc[:, 0:5]

     Age  Salary  Gender  Experience_Years Education_Level
0     18   63930  Female                 5     High School
1     21   76774  Female                19          Master
2     21   58651    Male                29     High School
3     57   92885    Male                15          Master
4     27   45997  Female                19     High School
..   ...     ...     ...               ...             ...
195   41   32679    Male                 2        Bachelor
196   50  106723    Male                27             PhD
197   29  100486  Female                 4     High School
198   58   61222  Female                26        Bachelor
199   38   98201    Male                19     High School

[200 rows x 5 columns]

## ***For getting a value explicitly:***

In [41]:
file.iloc[196,5]

'City_D'

## ***Boolean indexing***

In [49]:

file[file["Work_Hours_Per_Week"] > 47]

,Age,Salary,Gender,Experience_Years,Education_Level,City,Job_Role,Work_Hours_Per_Week
2,21,58651,Male,29,High School,City_B,Clerk,49
8,41,115971,Male,10,High School,City_B,Analyst,49
27,33,105523,Female,15,Master,City_D,Clerk,49
48,18,98955,Female,23,Bachelor,City_C,Clerk,48
58,49,117069,Female,26,Master,City_A,Engineer,48
66,36,55484,Male,24,Bachelor,City_C,Manager,48
72,38,52571,Female,27,Bachelor,City_B,Manager,49
77,21,113349,Male,9,Master,City_B,Manager,48
78,30,74889,Male,8,High School,City_C,Analyst,49
83,38,46363,Female,11,Master,City_D,Engineer,49
88,39,96576,Male,28,High School,City_C,Clerk,49
94,23,55907,Female,27,High School,City_A,Engineer,48
103,57,82237,Male,27,Bachelor,City_C,Clerk,49
108,41,73723,Female,19,High School,City_D,Engineer,49
120,59,63415,Male,13,High School,City_D,Engineer,49
128,34,82141,Female,29,Bachelor,City_B,Analyst,48
130,18,63354,Male,15,High School,City_B,Clerk,48
134,31,57867,Female,10,High School,City_C,Manager,49
151,50,106853,Female,19,High School,City_C,Manager,49
158,34,112865,Male,4,Bachelor,City_D,Analyst,49
163,34,77993,Male,24,Master,City_B,Engineer,48
179,33,38472,Male,10,High School,City_B,Engineer,49
194,23,66661,Male,27,PhD,City_D,Clerk,48

## ***Selecting values from a DataFrame where a boolean condition is met:***

In [61]:

file[file.select_dtypes(include='number') >  50-500]
file[(file.select_dtypes(include='number') > 50) & (file.select_dtypes(include='number') <= 200)]

,Age,Salary,Gender,Experience_Years,Education_Level,City,Job_Role,Work_Hours_Per_Week
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,57.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## ***Setting***
Setting a new column automatically aligns the data by the indexes:

In [17]:
import pandas as pd
s1 = pd.Series([202, 203, 204, 205, 206], index=pd.date_range("2023-09-21", periods=5))
s1

2023-09-21    202
2023-09-22    203
2023-09-23    204
2023-09-24    205
2023-09-25    206
Freq: D, dtype: int64

## ***Setting values by label:***

## ***Setting values by position:***

In [46]:
import pandas as pd
file = pd.read_excel("practice_dataset.xlsx")
print(file)

     Age  Salary  Gender  Experience_Years Education_Level    City  Job_Role  \
0     18   63930  Female                 5     High School  City_B     Clerk
1     21   76774  Female                19          Master  City_B  Engineer
2     21   58651    Male                29     High School  City_B     Clerk
3     57   92885    Male                15          Master  City_D  Engineer
4     27   45997  Female                19     High School  City_D  Engineer
..   ...     ...     ...               ...             ...     ...       ...
195   41   32679    Male                 2        Bachelor  City_B   Manager
196   50  106723    Male                27             PhD  City_D   Analyst
197   29  100486  Female                 4     High School  City_D     Clerk
198   58   61222  Female                26        Bachelor  City_B   Analyst
199   38   98201    Male                19     High School  City_C     Clerk

     Work_Hours_Per_Week
0                     32
1                     37
2                     49
3                     39
4                     30
..                   ...
195                   31
196                   33
197                   46
198                   33
199                   35

[200 rows x 8 columns]

## ***Missing data***
For NumPy data types, np.nan represents missing data. It is by default not included in computations. See the Missing Data section.

Reindexing allows you to change/add/delete the index on a specified axis. This returns a copy of the data:

In [54]:
import pandas as pd
import numpy as np



# Assuming 'file' is your original DataFrame

# Create a new DataFrame with the first 10 rows
file1 = file.reindex(index=file.index[0:10])

# Add a new column "E" based on the "Age" column
file1['E'] = np.where(file1['Age'] <= 20, file1['Age'], np.nan)

# Display the resulting DataFrame
print(file1)

   Age  Salary  Gender  Experience_Years Education_Level    City  Job_Role  \
0   18   63930  Female                 5     High School  City_B     Clerk
1   21   76774  Female                19          Master  City_B  Engineer
2   21   58651    Male                29     High School  City_B     Clerk
3   57   92885    Male                15          Master  City_D  Engineer
4   27   45997  Female                19     High School  City_D  Engineer
5   37   95180    Male                 2     High School  City_A  Engineer
6   39  104498    Male                13          Master  City_A   Manager
7   54   93003  Female                 1        Bachelor  City_B     Clerk
8   41  115971    Male                10     High School  City_B   Analyst
9   24   64009  Female                17             PhD  City_A   Manager

   Work_Hours_Per_Week     E
0                   32  18.0
1                   37   NaN
2                   49   NaN
3                   39   NaN
4                   30   NaN
5                   46   NaN
6                   47   NaN
7                   38   NaN
8                   49   NaN
9                   45   NaN

## ***DataFrame.dropna() drops any rows that have missing data***

In [61]:

file1 = file1.dropna(how='any')


file2 = file1.dropna(how='any')
print(file2)

   Age  Salary  Gender  Experience_Years Education_Level    City Job_Role  \
0   18   63930  Female                 5     High School  City_B    Clerk

   Work_Hours_Per_Week     E
0                   32  18.0

## ***DataFrame.fillna() fills missing data:***

In [71]:
file.fillna(value=5)

,Age,Salary,Gender,Experience_Years,Education_Level,City,Job_Role,Work_Hours_Per_Week,E
0,18,63930,Female,5,High School,City_B,Clerk,32,18.0
1,21,76774,Female,19,Master,City_B,Engineer,37,5.0
2,21,58651,Male,29,High School,City_B,Clerk,49,5.0
3,57,92885,Male,15,Master,City_D,Engineer,39,5.0
4,27,45997,Female,19,High School,City_D,Engineer,30,5.0
...,...,...,...,...,...,...,...,...,...
195,41,32679,Male,2,Bachelor,City_B,Manager,31,5.0
196,50,106723,Male,27,PhD,City_D,Analyst,33,5.0
197,29,100486,Female,4,High School,City_D,Clerk,46,5.0
198,58,61222,Female,26,Bachelor,City_B,Analyst,33,5.0
199,38,98201,Male,19,High School,City_C,Clerk,35,5.0

## ***isna() gets the boolean mask where values are nan***

In [72]:
pd.isna(file)

,Age,Salary,Gender,Experience_Years,Education_Level,City,Job_Role,Work_Hours_Per_Week,E
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...
195,False,False,False,False,False,False,False,False,True
196,False,False,False,False,False,False,False,False,True
197,False,False,False,False,False,False,False,False,True
198,False,False,False,False,False,False,False,False,True
199,False,False,False,False,False,False,False,False,True

## ***Operations***
See the Basic section on Binary Ops.

***Stats***
Operations in general exclude missing data.

Calculate the mean value for each column:

In [3]:
import pandas as pd

# Assuming you load your DataFrame here
file = pd.DataFrame({
    'Age': [22, 19, 25, np.nan, 18],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
})

# Check the mean of numeric columns (this will compute on the 'Age' column)
print(file.mean())

NameError: name 'np' is not defined

## ***Calculate the mean value for each row:***

In [10]:
import pandas as pd


file = pd.read_excel("practice_dataset.xlsx")

#  numeric columns
numeric_file = file.select_dtypes(include=[float, int])


mean_values = numeric_file.mean(axis=1)


print(mean_values)

0      15996.25
1      19212.75
2      14687.50
3      23249.00
4      11518.25
         ...
195     8188.25
196    26708.25
197    25141.25
198    15334.75
199    24573.25
Length: 200, dtype: float64

## ***User defined functions***
DataFrame.agg() and DataFrame.transform() applies a user defined function that reduces or broadcasts its result respectively.

In [13]:
import numpy as np

file.select_dtypes(include=[float, int]).agg(lambda x: np.mean(x) * 5.6)

Age                       213.416
Salary                 438721.836
Experience_Years           83.468
Work_Hours_Per_Week       222.320
dtype: float64

In [16]:
file.select_dtypes(include=[float, int, 'object']).transform(lambda x: x * 100 if x.dtype != 'object' else x)

,Age,Salary,Gender,Experience_Years,Education_Level,City,Job_Role,Work_Hours_Per_Week
0,1800,6393000,Female,500,High School,City_B,Clerk,3200
1,2100,7677400,Female,1900,Master,City_B,Engineer,3700
2,2100,5865100,Male,2900,High School,City_B,Clerk,4900
3,5700,9288500,Male,1500,Master,City_D,Engineer,3900
4,2700,4599700,Female,1900,High School,City_D,Engineer,3000
...,...,...,...,...,...,...,...,...
195,4100,3267900,Male,200,Bachelor,City_B,Manager,3100
196,5000,10672300,Male,2700,PhD,City_D,Analyst,3300
197,2900,10048600,Female,400,High School,City_D,Clerk,4600
198,5800,6122200,Female,2600,Bachelor,City_B,Analyst,3300
199,3800,9820100,Male,1900,High School,City_C,Clerk,3500

## ***Value Counts***
See more at Histogramming and Discretization.

In [19]:
s = pd.Series(np.random.randint(0, 200 , size=10))
s

0     76
1    152
2    138
3    190
4      9
5    136
6    148
7    126
8     49
9     50
dtype: int32

## ***String Methods***
Series is equipped with a set of string processing methods in the str attribute that make it easy to operate on each element of the array, as in the code snippet below. See more at Vectorized String Methods.

In [20]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])
s

0       A
1       B
2       C
3    Aaba
4    Baca
5     NaN
6    CABA
7     dog
8     cat
dtype: object

## ***Merge***
Concat
pandas provides various facilities for easily combining together Series and DataFrame objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join / merge-type operations.

See the Merging section.

Concatenating pandas objects together row-wise with concat():

In [27]:
concat = pd.DataFrame(np.random.randn(20, 1) , columns=["satisfaction level"])
concat

    satisfaction level
0             0.709474
1             1.400928
2            -1.024029
3             0.166078
4             0.095733
5             0.498703
6            -0.821032
7            -0.387069
8             0.058757
9            -2.248391
10           -0.442666
11           -0.328608
12            0.353761
13           -0.070147
14           -0.098121
15            0.677918
16            0.228704
17           -0.029956
18           -0.222385
19            0.544703

## ***Join***
merge() enables SQL style join types along specific columns. See the Database style joining section.

In [33]:
left = pd.DataFrame({
    "key": ["People like", "People dislike"],
    "benchmark": [56, 2]})

left

              key  benchmark
0     People like         56
1  People dislike          2

In [34]:
right = pd.DataFrame({
    "key": ["People like", "People dislike"], "rval": [50, 52]
    })
right

              key  rval
0     People like    50
1  People dislike    52

## ***Grouping***
By “group by” we are referring to a process involving one or more of the following steps:

Splitting the data into groups based on some criteria

Applying a function to each group independently

Combining the results into a data structure

In [38]:
data = ({
    "Satisfaction": np.random.choice(["satisfied", "neutral", "dissatisfied"], size=200),  # Random satisfaction levels
    "Age": np.random.randint(18, 65, size=200)
})
s = pd.DataFrame(data)
s

     Satisfaction  Age
0       satisfied   27
1         neutral   59
2         neutral   19
3       satisfied   48
4         neutral   18
..            ...  ...
195       neutral   54
196  dissatisfied   63
197       neutral   63
198     satisfied   62
199  dissatisfied   20

[200 rows x 2 columns]

## ***Grouping by a column label***
, selecting column labels, and then applying the DataFrameGroupBy.sum() function to the resulting groups:

In [43]:
import pandas as pd
import numpy as np

# Sample DataFrame
data = {
    "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
    "Satisfaction": np.random.choice(["satisfied", "neutral", "dissatisfied"], size=8),
    "Age": np.random.randint(18, 65, size=8),
}

file = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(file)

# Group by column "A" and aggregate
grouped = file.groupby("A").agg({"Satisfaction": lambda x: ', '.join(x), "Age": "sum"}).reset_index()

# Display the grouped DataFrame
print("\nGrouped by 'A' with aggregated Satisfaction and sum of Age:")
print(grouped)

Original DataFrame:
     A  Satisfaction  Age
0  foo     satisfied   52
1  bar  dissatisfied   43
2  foo  dissatisfied   47
3  bar  dissatisfied   22
4  foo  dissatisfied   40
5  bar       neutral   27
6  foo     satisfied   26
7  foo     satisfied   39

Grouped by 'A' with aggregated Satisfaction and sum of Age:
     A                                       Satisfaction  Age
0  bar                dissatisfied, dissatisfied, neutral   92
1  foo  satisfied, dissatisfied, dissatisfied, satisfi...  204

In [45]:
file.groupby(["A", "Age"]).sum()

         Satisfaction
A   Age
bar 22   dissatisfied
    27        neutral
    43   dissatisfied
foo 26      satisfied
    39      satisfied
    40   dissatisfied
    47   dissatisfied
    52      satisfied

## ***Reshaping***
See the sections on Hierarchical Indexing and Reshaping.

Stack

In [46]:
arrays = [
   ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
   ["one", "two", "one", "two", "one", "two", "one", "two"],
]


index = pd.MultiIndex.from_arrays(arrays, names=["first", "second"])

df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=["A", "B"])

df2 = df[:4]

df2

                     A         B
first second
bar   one     0.086100 -0.629587
      two     0.968370 -1.903710
baz   one     3.178022  0.765735
      two     0.927556  0.847010

In [47]:
stacked = df2.stack(future_stack=True)

stacked

first  second
bar    one     A    0.086100
               B   -0.629587
       two     A    0.968370
               B   -1.903710
baz    one     A    3.178022
               B    0.765735
       two     A    0.927556
               B    0.847010
dtype: float64

In [48]:
stacked.unstack()

                     A         B
first second
bar   one     0.086100 -0.629587
      two     0.968370 -1.903710
baz   one     3.178022  0.765735
      two     0.927556  0.847010

## ***Pivot tables***
See the section on Pivot Tables.

In [7]:
import pandas as pd
import numpy as np
s1 = pd.DataFrame(
    {
        "A": ["Alm", "hassan", "qayn", "Atom", ] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
    }
)
s1

         A  B    C         D         E
0      Alm  A  foo  1.559936  1.136817
1   hassan  B  foo  0.602295  0.161525
2     qayn  C  foo  1.181204  0.797678
3     Atom  A  bar -0.784165  1.173478
4      Alm  B  bar -0.006172 -0.417124
5   hassan  C  bar -0.197504 -1.865363
6     qayn  A  foo  1.469763 -1.148470
7     Atom  B  foo -0.135304  0.386448
8      Alm  C  foo  0.815804 -1.057166
9   hassan  A  bar  0.678627  0.098030
10    qayn  B  bar -1.300316 -0.572511
11    Atom  C  bar -0.352718 -0.584214

***pivot_table() pivots a DataFrame specifying the values, index and columns***

In [9]:
pd.pivot_table(s1, values="D", index=["A", "B"], columns=["C"])

C              bar       foo
A      B
Alm    A       NaN  1.559936
       B -0.006172       NaN
       C       NaN  0.815804
Atom   A -0.784165       NaN
       B       NaN -0.135304
       C -0.352718       NaN
hassan A  0.678627       NaN
       B       NaN  0.602295
       C -0.197504       NaN
qayn   A       NaN  1.469763
       B -1.300316       NaN
       C       NaN  1.181204

## ***Time series***
pandas has simple, powerful, and efficient functionality for performing resampling operations during frequency conversion (e.g., converting secondly data into 5-minutely data). This is extremely common in, but not limited to, financial applications. See the Time Series section.

In [13]:
rng = pd.date_range("1/1/2012", periods=100, freq="s")
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

ts.resample("5Min").sum()

2012-01-01    25619
Freq: 5min, dtype: int32

In [14]:
rng = pd.date_range("3/6/2012 00:00", periods=5, freq="D")

ts = pd.Series(np.random.randn(len(rng)), rng)

ts

2012-03-06   -1.045802
2012-03-07    0.307808
2012-03-08   -1.814335
2012-03-09   -0.143225
2012-03-10    0.208220
Freq: D, dtype: float64

## ***Series.tz_convert() converts a timezones aware time series to another time zone:***

In [15]:
ts_utc = ts.tz_localize("UTC")

ts_utc
ts_utc.tz_convert("US/Eastern")

2012-03-05 19:00:00-05:00   -1.045802
2012-03-06 19:00:00-05:00    0.307808
2012-03-07 19:00:00-05:00   -1.814335
2012-03-08 19:00:00-05:00   -0.143225
2012-03-09 19:00:00-05:00    0.208220
Freq: D, dtype: float64

## ***Categoricals***
pandas can include categorical data in a DataFrame. For full docs, see the categorical introduction and the API documentation.

In [1]:
df = pd.DataFrame(
    {"id": [1, 2, 3, 4, 5, 6], "raw_grade": ["a", "b", "b", "a", "a", "e"]}
)

NameError: name 'pd' is not defined