<h> Rawal </h>

# Rawal

## ***Heading level 2***
### Heading level 3
#### Heading level 4
##### Heading level 5
###### *Heading level 6*

In [80]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\cca\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\cca\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\cca\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\cca\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\cca\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\cca\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [81]:
import pandas as pd
import numpy as np

In [82]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [83]:
dates = pd.date_range("20130101", periods=30)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12',
               '2013-01-13', '2013-01-14', '2013-01-15', '2013-01-16',
               '2013-01-17', '2013-01-18', '2013-01-19', '2013-01-20',
               '2013-01-21', '2013-01-22', '2013-01-23', '2013-01-24',
               '2013-01-25', '2013-01-26', '2013-01-27', '2013-01-28',
               '2013-01-29', '2013-01-30'],
              dtype='datetime64[ns]', freq='D')

In [84]:
df = pd.DataFrame(np.random.rand(30, 9), index=dates, columns=list("abcdefghi"))
df

,a,b,c,d,e,f,g,h,i
2013-01-01,0.313374,0.316666,0.709251,0.104673,0.716685,0.969819,0.471530,0.602515,0.393495
2013-01-02,0.490783,0.500192,0.351451,0.772179,0.003880,0.836305,0.769511,0.586469,0.197456
2013-01-03,0.718212,0.670086,0.579865,0.053438,0.665982,0.163135,0.156511,0.200904,0.265334
2013-01-04,0.693224,0.446972,0.865069,0.734866,0.288804,0.389667,0.035184,0.902117,0.643734
2013-01-05,0.581214,0.249054,0.089884,0.027062,0.182272,0.875436,0.520876,0.140544,0.981304
2013-01-06,0.936684,0.704694,0.120436,0.740035,0.470077,0.835734,0.888669,0.592782,0.737497
2013-01-07,0.574679,0.714499,0.830452,0.828422,0.763556,0.845336,0.579175,0.670655,0.821684
2013-01-08,0.734575,0.650148,0.143294,0.663381,0.294232,0.259362,0.485726,0.058464,0.117326
2013-01-09,0.288439,0.775292,0.710490,0.135348,0.991541,0.784233,0.422323,0.274876,0.417442
2013-01-10,0.210707,0.361741,0.497455,0.245530,0.791140,0.795758,0.686144,0.282190,0.168349
2013-01-11,0.678147,0.770498,0.378933,0.779457,0.812670,0.972313,0.217958,0.673682,0.965111
2013-01-12,0.454016,0.261572,0.845958,0.188389,0.609263,0.385139,0.655809,0.735410,0.768550
2013-01-13,0.467803,0.913330,0.903169,0.990863,0.723740,0.418897,0.520512,0.116531,0.342620
2013-01-14,0.557023,0.561511,0.333793,0.186635,0.152266,0.898904,0.512653,0.571092,0.158787
2013-01-15,0.661953,0.903133,0.168924,0.305505,0.403092,0.286361,0.698649,0.201185,0.954879
2013-01-16,0.863125,0.701466,0.512885,0.158071,0.087572,0.860538,0.735485,0.759496,0.108557
2013-01-17,0.269049,0.836495,0.727003,0.696132,0.865554,0.453556,0.241957,0.984840,0.907987
2013-01-18,0.555381,0.158600,0.572164,0.602450,0.146760,0.386537,0.153979,0.365405,0.251643
2013-01-19,0.247098,0.661723,0.128107,0.621378,0.769672,0.095690,0.761831,0.888030,0.708568
2013-01-20,0.196353,0.801850,0.759920,0.950558,0.328819,0.797859,0.886529,0.726935,0.017309
2013-01-21,0.929355,0.072454,0.357819,0.469036,0.981296,0.707666,0.596176,0.780218,0.830678
2013-01-22,0.660467,0.625296,0.461124,0.968658,0.772290,0.803524,0.978101,0.764113,0.896402
2013-01-23,0.718089,0.554224,0.955577,0.335993,0.753694,0.090205,0.952251,0.117499,0.302402
2013-01-24,0.406954,0.232384,0.838079,0.638940,0.854641,0.855546,0.081483,0.486682,0.147668
2013-01-25,0.630249,0.117974,0.584535,0.126946,0.623041,0.619993,0.917921,0.607711,0.952462
2013-01-26,0.122934,0.903878,0.264487,0.952278,0.509619,0.140279,0.391624,0.051875,0.518711
2013-01-27,0.954527,0.087282,0.677780,0.136288,0.369268,0.897892,0.851037,0.578086,0.479706
2013-01-28,0.533484,0.761522,0.292173,0.334673,0.830742,0.064721,0.857477,0.186176,0.230211
2013-01-29,0.844120,0.017821,0.393992,0.482984,0.436776,0.303226,0.056364,0.844767,0.711651
2013-01-30,0.690667,0.674036,0.651045,0.666203,0.577454,0.735630,0.410741,0.720478,0.583507

In [85]:
df.dtypes

a    float64
b    float64
c    float64
d    float64
e    float64
f    float64
g    float64
h    float64
i    float64
dtype: object

In [86]:
df.

SyntaxError: invalid syntax (1625957470.py, line 1)

In [10]:
import pandas as pd
df= pd.read_excel(r"C:\New folder\Data Bleanding File One.xlsx")
print(df.head(15))

     NAME  EMPID  SALARY
0     ABC      1   10000
1     XYZ      2   10000
2     PQR      3   10000
3     STU      4   10000
4    DSDS      5   10000
5    CVSD      6   10000
6    DCSD      7   10000
7     DCX      8   10000
8   DSCSD      9   10000
9   SDCXC     10   10000
10    DCX     11   10000
11    C X     12   10000
12    ABC     13   10000
13    SFS     14   10000
14     GD     15   10000

In [13]:
df2.<TAB>  # noqa: E225, E999
df.head()

SyntaxError: invalid syntax (3927641682.py, line 1)

In [14]:
df.describe()

          EMPID   SALARY
count  20.00000     20.0
mean   10.50000  10000.0
std     5.91608      0.0
min     1.00000  10000.0
25%     5.75000  10000.0
50%    10.50000  10000.0
75%    15.25000  10000.0
max    20.00000  10000.0

In [15]:
df.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
NAME,ABC,XYZ,PQR,STU,DSDS,CVSD,DCSD,DCX,DSCSD,SDCXC,DCX,C X,ABC,SFS,GD,GD,SG,GD,F,hskjh
EMPID,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
SALARY,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000

In [16]:
df.sort_index(axis=1, ascending=False)

    SALARY   NAME  EMPID
0    10000    ABC      1
1    10000    XYZ      2
2    10000    PQR      3
3    10000    STU      4
4    10000   DSDS      5
5    10000   CVSD      6
6    10000   DCSD      7
7    10000    DCX      8
8    10000  DSCSD      9
9    10000  SDCXC     10
10   10000    DCX     11
11   10000    C X     12
12   10000    ABC     13
13   10000    SFS     14
14   10000     GD     15
15   10000     GD     16
16   10000     SG     17
17   10000     GD     18
18   10000      F     19
19   10000  hskjh     20

In [17]:
df.sort_values(by="B")

KeyError: 'B'

In [18]:
df["A"]

KeyError: 'A'

In [19]:
df[0:3]

  NAME  EMPID  SALARY
0  ABC      1   10000
1  XYZ      2   10000
2  PQR      3   10000

In [20]:
df.loc[dates[0]]

KeyError: Timestamp('2013-01-01 00:00:00')

In [21]:
df.loc[:, ["A", "B"]]

KeyError: "None of [Index(['A', 'B'], dtype='object')] are in the [columns]"

In [22]:
df.iloc[3]

NAME        STU
EMPID         4
SALARY    10000
Name: 3, dtype: object

In [23]:
df.iloc[3:5, 0:2]

   NAME  EMPID
3   STU      4
4  DSDS      5

In [24]:
df.iloc[[1, 2, 4], [0, 2]]

   NAME  SALARY
1   XYZ   10000
2   PQR   10000
4  DSDS   10000

In [25]:
df.iloc[1:3, :]

  NAME  EMPID  SALARY
1  XYZ      2   10000
2  PQR      3   10000

In [26]:
df.iloc[:, 1:3]

    EMPID  SALARY
0       1   10000
1       2   10000
2       3   10000
3       4   10000
4       5   10000
5       6   10000
6       7   10000
7       8   10000
8       9   10000
9      10   10000
10     11   10000
11     12   10000
12     13   10000
13     14   10000
14     15   10000
15     16   10000
16     17   10000
17     18   10000
18     19   10000
19     20   10000

In [27]:
df.iloc[1, 1]

np.int64(2)

In [28]:
df.iat[1, 1]

np.int64(2)

In [29]:
df[df > 0]

TypeError: '>' not supported between instances of 'str' and 'int'

In [30]:
df2 = df.copy()

In [31]:
In [45]: s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))

In [46]: s1
Out[46]: 
2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [47]: df["F"] = s1

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (1444151879.py, line 5)

In [32]:
In [49]: df.iat[0, 1] = 0

In [33]:
In [51]: df
Out[51]: 
                   A         B         C    D    F
2013-01-01  0.000000  0.000000 -1.509059  5.0  NaN
2013-01-02  1.212112 -0.173215  0.119209  5.0  1.0
2013-01-03 -0.861849 -2.104569 -0.494929  5.0  2.0
2013-01-04  0.721555 -0.706771 -1.039575  5.0  3.0
2013-01-05 -0.424972  0.567020  0.276232  5.0  4.0
2013-01-06 -0.673690  0.113648 -1.478427  5.0  5.0

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (2360280605.py, line 4)

In [34]:
In [52]: df2 = df.copy()

In [53]: df2[df2 > 0] = -df2

In [54]: df2
Out[54]: 
                   A         B         C    D    F
2013-01-01  0.000000  0.000000 -1.509059 -5.0  NaN
2013-01-02 -1.212112 -0.173215 -0.119209 -5.0 -1.0
2013-01-03 -0.861849 -2.104569 -0.494929 -5.0 -2.0
2013-01-04 -0.721555 -0.706771 -1.039575 -5.0 -3.0
2013-01-05 -0.424972 -0.567020 -0.276232 -5.0 -4.0
2013-01-06 -0.673690 -0.113648 -1.478427 -5.0 -5.0

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (4073473519.py, line 8)

In [35]:
df2 = df.copy()

In [36]:
df1.dropna(how="any")

NameError: name 'df1' is not defined

In [38]:
df.mean()

TypeError: Could not convert ['ABCXYZPQRSTUDSDSCVSDDCSDDCXDSCSDSDCXCDCXC XABCSFSGDGDSGGDFhskjh'] to numeric

In [37]:
pd.isna(df1)

NameError: name 'df1' is not defined

In [39]:
pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(2)

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64

In [42]:
df= pd.read_excel(r"C:\New folder\Data Bleanding File One.xlsx")
print(df.head(15))

     NAME  EMPID  SALARY
0     ABC      1   10000
1     XYZ      2   10000
2     PQR      3   10000
3     STU      4   10000
4    DSDS      5   10000
5    CVSD      6   10000
6    DCSD      7   10000
7     DCX      8   10000
8   DSCSD      9   10000
9   SDCXC     10   10000
10    DCX     11   10000
11    C X     12   10000
12    ABC     13   10000
13    SFS     14   10000
14     GD     15   10000

In [1]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\cca\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\cca\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd

In [24]:
pd.read_excel("Data Bleanding File One.xlsx")

     NAME  EMPID  SALARY
0     ABC      1   10000
1     XYZ      2   10000
2     PQR      3   10000
3     STU      4   10000
4    DSDS      5   10000
5    CVSD      6   10000
6    DCSD      7   10000
7     DCX      8   10000
8   DSCSD      9   10000
9   SDCXC     10   10000
10    DCX     11   10000
11    C X     12   10000
12    ABC     13   10000
13    SFS     14   10000
14     GD     15   10000
15     GD     16   10000
16     SG     17   10000
17     GD     18   10000
18      F     19   10000
19  hskjh     20   10000

In [33]:
pd.tail(3)

AttributeError: module 'pandas' has no attribute 'tail'

In [32]:
pd.tail(3)

AttributeError: module 'pandas' has no attribute 'tail'

In [29]:
s=pd.Series("NAME")
s

0    NAME
dtype: object

In [35]:
df.loc[:,["NAME"]]

KeyError: "None of [Index(['NAME'], dtype='object')] are in the [columns]"

In [2]:
%pip install numpay

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement numpay (from versions: none)
ERROR: No matching distribution found for numpay

In [4]:
import numpy as np

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [20]:
np.array1([[1,2],[3,4]])
array=np.array

AttributeError: module 'numpy' has no attribute 'array1'

In [21]:
array1.size

NameError: name 'array1' is not defined

In [28]:
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [39]:
r=np.array([1,2,3,4,5,6])
r
r[0]
r[3]
r[5]
r[0]=10
r
r[:3]
r
r1=r[:3]
r1
r2=r[3:]
r2

array([4, 5, 6])

In [15]:
a = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])
a
# a[1, 3]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [16]:
a.shape

(2, 3, 4)

In [17]:
a.ndim

3

In [18]:
a.size

24

In [19]:
a.dtype

dtype('int64')

In [25]:
np.zeros([2,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [29]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [30]:
np.empty(2)

array([1., 1.])

In [32]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [38]:
np.arange(2, 15, 3)

array([ 2,  5,  8, 11, 14])

In [35]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [43]:
np.linspace(0, 15, num=6)

array([ 0.,  3.,  6.,  9., 12., 15.])

In [48]:
r3 = np.ones(25, dtype=np.int64)
r3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [50]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [52]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array([9, 10, 11, 12, 13, 14])

In [67]:
np.concatenate(((a,b,c)))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [73]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]

In [91]:
b = a.reshape(5, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

In [95]:
np.reshape(a, shape=(5, 2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])