# Name  <span style="color:blue"> ***Owais Ur Rehman***</span>
This note book contains the implementation of pandas function with their Usage

First of all we need to import the python libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("data_set_1.csv")
df.head()

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active
0,1,Alice,28,Female,Engineer,70000,New York,USA,2020-01-15,True
1,2,Bob,34,Male,Designer,65000,Los Angeles,USA,2019-03-22,True
2,3,Charlie,29,Male,Teacher,50000,Chicago,USA,2021-07-30,False
3,4,David,42,Male,Manager,80000,Houston,USA,2018-12-11,True
4,5,Eve,36,Female,Scientist,72000,San Francisco,USA,2022-05-18,True

<span style="color:green">The underline code will display the data-type of all column of our
data-set.For this purpose we used the **dtype** function</span>

In [5]:
df.dtypes

ID             int64
Name          object
Age            int64
Gender        object
Occupation    object
Salary         int64
City          object
Country       object
Join_Date     object
Active        object
dtype: object

## Viewing data
Pandas contains functions through which we can view our data<br>
1.**head()** This functoin can display the first 5 rows of the data set<br>
2.**tail()** This function will display the last 5 rows of the data set

In [6]:
df.tail()

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active
61,62,Jack,32,Male,Marketing,60000,Chicago,USA,2020-04-30,True
62,63,Kate,31,Female,Engineer,71000,San Francisco,USA,2021-02-20,True
63,64,Liam,27,Male,Sales,49000,Los Angeles,USA,2023-06-14,False
64,65,Mia,34,Female,Doctor,120000,Orlando,USA,2017-09-08,True
65,66,Nate,29,Male,Chef,55000,Nashville,USA,2022,NaN

## **DataFrame.index** or **DataFrame.columns**
<span style="color:red">The upper two function will display the name of rows and columns</span>

In [8]:
df.index

RangeIndex(start=0, stop=66, step=1)

In [9]:
df.columns

Index(['ID', 'Name', 'Age', 'Gender', 'Occupation', 'Salary', 'City',
       'Country', 'Join_Date', 'Active'],
      dtype='object')

### **describe()** shows a quick statistic summary of your data

In [10]:
df.describe()

              ID        Age         Salary
count  66.000000  66.000000      66.000000
mean   33.500000  32.878788   69666.666667
std    19.196354   5.166505   17725.542920
min     1.000000  26.000000   47000.000000
25%    17.250000  29.000000   55000.000000
50%    33.500000  31.500000   70000.000000
75%    49.750000  36.000000   78000.000000
max    66.000000  45.000000  120000.000000

**Sorting** of data by column and by index(Row) can be done by using ***DataFrame.sort_index()***<br> OR<br> 
***DataFrame.sort_values()***

In [12]:
df.sort_values(by="Age")

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active
14,15,Olivia,26,Female,Scientist,72000,San Jose,USA,2021-02-15,True
40,41,Olivia,26,Female,Scientist,72000,Seattle,USA,2020-06-22,True
11,12,Liam,27,Male,Sales,49000,Orlando,USA,2023-01-02,False
6,7,Grace,27,Female,Artist,48000,Denver,USA,2021-11-05,False
49,50,Xena,27,Female,Artist,47000,Chicago,USA,2022-09-15,True
...,...,...,...,...,...,...,...,...,...,...
29,30,David,42,Male,Manager,85000,Boston,USA,2018-05-11,True
3,4,David,42,Male,Manager,80000,Houston,USA,2018-12-11,True
8,9,Ivy,45,Female,Manager,85000,Philadelphia,USA,2019-06-21,True
60,61,Ivy,45,Female,Manager,85000,Miami,USA,2022-05-18,True
34,35,Ivy,45,Female,Manager,85000,Miami,USA,2019-05-22,True

## Getitem
    1.passing a single label selects a columns and yields a Series
    2.When try to get only a specific range of value we used the slicing

In [14]:
df["Age"].head(20)

0     28
1     34
2     29
3     42
4     36
5     30
6     27
7     38
8     45
9     32
10    31
11    27
12    34
13    29
14    26
15    40
16    33
17    39
18    28
19    35
Name: Age, dtype: int64

In [15]:
df[0:11]

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active
0,1,Alice,28,Female,Engineer,70000,New York,USA,2020-01-15,True
1,2,Bob,34,Male,Designer,65000,Los Angeles,USA,2019-03-22,True
2,3,Charlie,29,Male,Teacher,50000,Chicago,USA,2021-07-30,False
3,4,David,42,Male,Manager,80000,Houston,USA,2018-12-11,True
4,5,Eve,36,Female,Scientist,72000,San Francisco,USA,2022-05-18,True
5,6,Frank,30,Male,Developer,75000,Seattle,USA,2020-08-24,True
6,7,Grace,27,Female,Artist,48000,Denver,USA,2021-11-05,False
7,8,Henry,38,Male,Architect,90000,Boston,USA,2017-04-17,True
8,9,Ivy,45,Female,Manager,85000,Philadelphia,USA,2019-06-21,True
9,10,Jack,32,Male,Marketing,60000,Atlanta,USA,2022-09-10,True
10,11,Kate,31,Female,Engineer,71000,San Diego,USA,2020-03-14,True

### <span style="color:green" style="text-decoration-style: wavy">***<u>Selection by label</u>***</span>
by using **DataFrame.loc()** or **DataFrame.at().**
<br>Selecting a row matching a label: