# Name  <span style="color:blue"> <u>***Owais Ur Rehman***</u></span>
This note book contains the implementation of pandas function with their Usage

First of all we need to import the python libraries

In [24]:
import pandas as pd
import numpy as np

In [25]:
df=pd.read_csv("data_set_1.csv")
df.head()

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active
0,1,Alice,28,Female,Engineer,70000,New York,USA,2020-01-15,True
1,2,Bob,34,Male,Designer,65000,Los Angeles,USA,2019-03-22,True
2,3,Charlie,29,Male,Teacher,50000,Chicago,USA,2021-07-30,False
3,4,David,42,Male,Manager,80000,Houston,USA,2018-12-11,True
4,5,Eve,36,Female,Scientist,72000,San Francisco,USA,2022-05-18,True

<span style="color:green">The underline code will display the data-type of all column of our
data-set.For this purpose we used the **dtype** function</span>

In [26]:
df.dtypes

ID             int64
Name          object
Age            int64
Gender        object
Occupation    object
Salary         int64
City          object
Country       object
Join_Date     object
Active        object
dtype: object

## <span style="color:red"><u>Viewing data</u></span>
Pandas contains functions through which we can view our data<br>
1.**head()** This functoin can display the first 5 rows of the data set<br>
2.**tail()** This function will display the last 5 rows of the data set

In [27]:
df.tail()

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active
61,62,Jack,32,Male,Marketing,60000,Chicago,USA,2020-04-30,True
62,63,Kate,31,Female,Engineer,71000,San Francisco,USA,2021-02-20,True
63,64,Liam,27,Male,Sales,49000,Los Angeles,USA,2023-06-14,False
64,65,Mia,34,Female,Doctor,120000,Orlando,USA,2017-09-08,True
65,66,Nate,29,Male,Chef,55000,Nashville,USA,2022,NaN

## **DataFrame.index** or **DataFrame.columns**
<span style="color:red">The upper two function will display the name of rows and columns</span>

In [28]:
df.index

RangeIndex(start=0, stop=66, step=1)

In [29]:
df.columns

Index(['ID', 'Name', 'Age', 'Gender', 'Occupation', 'Salary', 'City',
       'Country', 'Join_Date', 'Active'],
      dtype='object')

### **describe()** shows a quick statistic summary of your data

In [30]:
df.describe()

              ID        Age         Salary
count  66.000000  66.000000      66.000000
mean   33.500000  32.878788   69666.666667
std    19.196354   5.166505   17725.542920
min     1.000000  26.000000   47000.000000
25%    17.250000  29.000000   55000.000000
50%    33.500000  31.500000   70000.000000
75%    49.750000  36.000000   78000.000000
max    66.000000  45.000000  120000.000000

**Sorting** of data by column and by index(Row) can be done by using ***DataFrame.sort_index()***<br> OR<br> 
***DataFrame.sort_values()***

In [31]:
df.sort_values(by="Age")

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active
14,15,Olivia,26,Female,Scientist,72000,San Jose,USA,2021-02-15,True
40,41,Olivia,26,Female,Scientist,72000,Seattle,USA,2020-06-22,True
11,12,Liam,27,Male,Sales,49000,Orlando,USA,2023-01-02,False
6,7,Grace,27,Female,Artist,48000,Denver,USA,2021-11-05,False
49,50,Xena,27,Female,Artist,47000,Chicago,USA,2022-09-15,True
...,...,...,...,...,...,...,...,...,...,...
29,30,David,42,Male,Manager,85000,Boston,USA,2018-05-11,True
3,4,David,42,Male,Manager,80000,Houston,USA,2018-12-11,True
8,9,Ivy,45,Female,Manager,85000,Philadelphia,USA,2019-06-21,True
60,61,Ivy,45,Female,Manager,85000,Miami,USA,2022-05-18,True
34,35,Ivy,45,Female,Manager,85000,Miami,USA,2019-05-22,True

# <span style="color:cyan"><u> Getitem</u></span>
    1.passing a single label selects a columns and yields a Series
    2.When try to get only a specific range of value we used the slicing

In [32]:
df["Age"].head(20)

0     28
1     34
2     29
3     42
4     36
5     30
6     27
7     38
8     45
9     32
10    31
11    27
12    34
13    29
14    26
15    40
16    33
17    39
18    28
19    35
Name: Age, dtype: int64

In [33]:
df[0:11]

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active
0,1,Alice,28,Female,Engineer,70000,New York,USA,2020-01-15,True
1,2,Bob,34,Male,Designer,65000,Los Angeles,USA,2019-03-22,True
2,3,Charlie,29,Male,Teacher,50000,Chicago,USA,2021-07-30,False
3,4,David,42,Male,Manager,80000,Houston,USA,2018-12-11,True
4,5,Eve,36,Female,Scientist,72000,San Francisco,USA,2022-05-18,True
5,6,Frank,30,Male,Developer,75000,Seattle,USA,2020-08-24,True
6,7,Grace,27,Female,Artist,48000,Denver,USA,2021-11-05,False
7,8,Henry,38,Male,Architect,90000,Boston,USA,2017-04-17,True
8,9,Ivy,45,Female,Manager,85000,Philadelphia,USA,2019-06-21,True
9,10,Jack,32,Male,Marketing,60000,Atlanta,USA,2022-09-10,True
10,11,Kate,31,Female,Engineer,71000,San Diego,USA,2020-03-14,True

### <span style="color:green" style="text-decoration-style: wavy">***<u>Selection by label</u>***</span>
by using **DataFrame.loc()** or **DataFrame.at().**
<br>    1.Selecting a row matching a label<br>
        2.Selecting all rows (:) with a select column labels<br>
        3.Selecting a single row and column label returns a scalar (only one value)

In [34]:
df.loc[1]

ID                      2
Name                  Bob
Age                    34
Gender               Male
Occupation       Designer
Salary              65000
City          Los Angeles
Country               USA
Join_Date      2019-03-22
Active               True
Name: 1, dtype: object

In [35]:
df.loc[2:10,["Name","Age","Gender"]]

       Name  Age  Gender
2   Charlie   29    Male
3     David   42    Male
4       Eve   36  Female
5     Frank   30    Male
6     Grace   27  Female
7     Henry   38    Male
8       Ivy   45  Female
9      Jack   32    Male
10     Kate   31  Female

In [36]:
df.at[5, 'Name']

'Frank'

# <span style="color:yellow"> <u> Selection by position </u> </span>
By Position using DataFrame.iloc() or DataFrame.iat().
<br>
1.Select via the position of the passed integers <br>
2.Integer slices acts similar to NumPy/Python

In [37]:
df.iloc[3]

ID                     4
Name               David
Age                   42
Gender              Male
Occupation       Manager
Salary             80000
City             Houston
Country              USA
Join_Date     2018-12-11
Active              True
Name: 3, dtype: object

In [38]:
df.iloc[3:5, 0:2]

   ID   Name
3   4  David
4   5    Eve

<span style="color:green">***This code will select only the rows whose no is 1,2,4,5 and only those columns are selected***<br>
***whose name are mention***</span>

In [39]:
df.iloc[[1, 2, 4,5], [0, 2]]

   ID  Age
1   2   34
2   3   29
4   5   36
5   6   30

# <span style="color:magenta"><u> ***Boolean indexing***</u></span><br>
By this method we can select only those rows which satisfied the certain condition<br>
Second line of code will check the multiple condition

In [40]:
df[df["Age"] > 27].head()

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active
0,1,Alice,28,Female,Engineer,70000,New York,USA,2020-01-15,True
1,2,Bob,34,Male,Designer,65000,Los Angeles,USA,2019-03-22,True
2,3,Charlie,29,Male,Teacher,50000,Chicago,USA,2021-07-30,False
3,4,David,42,Male,Manager,80000,Houston,USA,2018-12-11,True
4,5,Eve,36,Female,Scientist,72000,San Francisco,USA,2022-05-18,True

In [41]:
df[(df["Age"] > 30) & (df["Salary"] > 50000)].head(7)

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active
1,2,Bob,34,Male,Designer,65000,Los Angeles,USA,2019-03-22,True
3,4,David,42,Male,Manager,80000,Houston,USA,2018-12-11,True
4,5,Eve,36,Female,Scientist,72000,San Francisco,USA,2022-05-18,True
7,8,Henry,38,Male,Architect,90000,Boston,USA,2017-04-17,True
8,9,Ivy,45,Female,Manager,85000,Philadelphia,USA,2019-06-21,True
9,10,Jack,32,Male,Marketing,60000,Atlanta,USA,2022-09-10,True
10,11,Kate,31,Female,Engineer,71000,San Diego,USA,2020-03-14,True

# <u><span style="color:gold"> ***Setting*** </u></span>
We can add new column in dataset and also assign some values by using the following code

In [42]:
df.loc[:,"Status"]=np.nan
df.head()

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active,Status
0,1,Alice,28,Female,Engineer,70000,New York,USA,2020-01-15,True,NaN
1,2,Bob,34,Male,Designer,65000,Los Angeles,USA,2019-03-22,True,NaN
2,3,Charlie,29,Male,Teacher,50000,Chicago,USA,2021-07-30,False,NaN
3,4,David,42,Male,Manager,80000,Houston,USA,2018-12-11,True,NaN
4,5,Eve,36,Female,Scientist,72000,San Francisco,USA,2022-05-18,True,NaN

# <span style="color:teal"> <u>***Missing data***</u></span>
For NumPy data types, np.nan represents missing data. It is by default not included in computations <br>
 >Using ***sum()*** function we can find the total no of **NAN** values in each column<br>
 >Then ***dropna()*** will used to remove all that ***NAN***<br>
 >Functoin ***fillna()*** will fill that ***NAN** with some specified value

In [43]:
df.fillna(55).head()

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active,Status
0,1,Alice,28,Female,Engineer,70000,New York,USA,2020-01-15,True,55.0
1,2,Bob,34,Male,Designer,65000,Los Angeles,USA,2019-03-22,True,55.0
2,3,Charlie,29,Male,Teacher,50000,Chicago,USA,2021-07-30,False,55.0
3,4,David,42,Male,Manager,80000,Houston,USA,2018-12-11,True,55.0
4,5,Eve,36,Female,Scientist,72000,San Francisco,USA,2022-05-18,True,55.0

# <span style="color:violet"> <u>**User defined functions**</u> </span>
***DataFrame.agg()*** and ***DataFrame.transform()*** applies a user defined function that reduces or broadcasts its result respectively.

In [44]:
df1 = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})
def multiply_mean(x):
    return np.mean(x) * 100
df1.agg(multiply_mean).head()

A    200.0
B    500.0
dtype: float64

In [45]:
df.isnull().sum()

ID             0
Name           0
Age            0
Gender         0
Occupation     0
Salary         0
City           0
Country        0
Join_Date      0
Active         1
Status        66
dtype: int64

In [46]:
df.head()

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Join_Date,Active,Status
0,1,Alice,28,Female,Engineer,70000,New York,USA,2020-01-15,True,NaN
1,2,Bob,34,Male,Designer,65000,Los Angeles,USA,2019-03-22,True,NaN
2,3,Charlie,29,Male,Teacher,50000,Chicago,USA,2021-07-30,False,NaN
3,4,David,42,Male,Manager,80000,Houston,USA,2018-12-11,True,NaN
4,5,Eve,36,Female,Scientist,72000,San Francisco,USA,2022-05-18,True,NaN

# <span style="color:orange"><u>***Grouping***</u></span>
***group by*** we are referring to a process involving one or more of the following steps

**Splitting** the data into groups based on some criteria

**Applying** a function to each group independently

**Combining** the results into a data structure

This module contains the Grouping by multiple columns label forms

In [48]:
df.groupby("Gender")[["Salary","Age"]].sum()

         Salary   Age
Gender
Female  2256000  1043
Male    2342000  1127

In [57]:
df.groupby(["Age","Salary"]).sum().iloc[:,[0,2,3,5]]

             ID                Gender  \
Age Salary
26  72000    56          FemaleFemale
27  47000    74          FemaleFemale
    48000    99    FemaleFemaleFemale
    49000   114          MaleMaleMale
28  60000    64              MaleMale
    70000     1                Female
    78000    80          FemaleFemale
29  50000     3                  Male
    55000   120          MaleMaleMale
    62000    84              MaleMale
    70000    68          FemaleFemale
30  75000    96          MaleMaleMale
    78000    70              MaleMale
31  71000   111    FemaleFemaleFemale
    72000    76          FemaleFemale
32  60000   108          MaleMaleMale
33  68000    60          FemaleFemale
34  50000    82              MaleMale
    65000     2                  Male
    120000  117    FemaleFemaleFemale
35  55000    66          FemaleFemale
36  49000    88          FemaleFemale
    60000    72              MaleMale
    72000     5                Female
38  90000   180  MaleMaleMaleMaleMale
39  60000    62          FemaleFemale
40  95000    58              MaleMale
42  80000     4                  Male
    85000    86              MaleMale
45  85000   105    FemaleFemaleFemale

                                               Occupation          Country
Age Salary
26  72000                              ScientistScientist           USAUSA
27  47000                                    ArtistArtist           USAUSA
    48000                              ArtistArtistArtist        USAUSAUSA
    49000                                 SalesSalesSales        USAUSAUSA
28  60000                                  AnalystAnalyst           USAUSA
    70000                                        Engineer              USA
    78000                              ScientistScientist           USAUSA
29  50000                                         Teacher              USA
    55000                                    ChefChefChef        USAUSAUSA
    62000                                DesignerDesigner           USAUSA
    70000                                  ManagerManager           USAUSA
30  75000                     DeveloperDeveloperDeveloper        USAUSAUSA
    78000                              DeveloperDeveloper           USAUSA
31  71000                        EngineerEngineerEngineer        USAUSAUSA
    72000                                EngineerEngineer           USAUSA
32  60000                     MarketingMarketingMarketing        USAUSAUSA
33  68000                              DeveloperDeveloper           USAUSA
34  50000                                  TeacherTeacher           USAUSA
    65000                                        Designer              USA
    120000                             DoctorDoctorDoctor        USAUSAUSA
35  55000                                  TeacherTeacher           USAUSA
36  49000                                        ChefChef           USAUSA
    60000                              MarketingMarketing           USAUSA
    72000                                       Scientist              USA
38  90000   ArchitectArchitectArchitectArchitectArchitect  USAUSAUSAUSAUSA
39  60000                                DesignerDesigner           USAUSA
40  95000                                EngineerEngineer           USAUSA
42  80000                                         Manager              USA
    85000                                  ManagerManager           USAUSA
45  85000                           ManagerManagerManager        USAUSAUSA