# Pandas Functions

In [13]:
import pandas as pd
import numpy as np

First of all we have to import libraries

In [25]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
df = pd.DataFrame({
    'Name': ['Adnan', "usman", "Fakhar", 'Ali', 'Adeel', 'Ajmal'],
    'age': [11, 13, 15, np.nan, 16, 18],
}, index=[ 1, 2, 3, 4, 5,6])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [26]:
print(df)

     Name   age
1   Adnan  11.0
2   usman  13.0
3  Fakhar  15.0
4     Ali   NaN
5   Adeel  16.0
6   Ajmal  18.0

**pd.series()** is Singe Dimentional *labeled array*

**pd.DataFrame()** is Two Dimentional *Data Frame* which contains multiple rows and columns

In [15]:
date = pd.date_range(start='20140715', end = '20240915', freq = "Y")
date

C:\Users\dit\AppData\Local\Temp\ipykernel_4552\3555385800.py:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  date = pd.date_range(start='20140715', end = '20240915', freq = "Y")

DatetimeIndex(['2014-12-31', '2015-12-31', '2016-12-31', '2017-12-31',
               '2018-12-31', '2019-12-31', '2020-12-31', '2021-12-31',
               '2022-12-31', '2023-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')

**pd.date_range()** is single dimentional aray of date or time based on defined parameters like:
- start =
- end =
- freq =
- periods =

In [16]:
df1 = pd.DataFrame(np.random.rand(10, 4), columns=['y','x1','x2','x3'])

df1

          y        x1        x2        x3
0  0.329451  0.338238  0.320801  0.974597
1  0.963802  0.876812  0.208270  0.465062
2  0.715445  0.547000  0.171166  0.414529
3  0.425257  0.789973  0.178012  0.640145
4  0.066779  0.498029  0.243267  0.994032
5  0.933529  0.067380  0.382479  0.227026
6  0.062183  0.024573  0.179724  0.909630
7  0.250086  0.011924  0.008626  0.753556
8  0.970105  0.306655  0.453312  0.435030
9  0.903288  0.005746  0.321485  0.596094

**pd.DataFrame()** is Two Dimentional *Data Frame* which contains multiple rows and columns as defined in parameters.

**np.random.rand()** is used to genrate random rows and column entries the size defined 6 rows and 4 columns

**index =** is used to define costume index by defualt index is 0,1,2,3,4,5...

**columns =** is used to define costume columns heading by defualt columns headings are 0,1,2,3,4,5...

In [17]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

## DataFrame Functons

**pd.Timestamp** is used for Date and time.

**pd.Series** is used for list.

**pd.Categorical** is used for catagorica values.

- Simple numeric values (_1_) int64
- Desimal values (_1.0_) are stored in float64
- String (_'abc'_) is stored in object

## Viewing data

In [18]:
df1.head()

          y        x1        x2        x3
0  0.329451  0.338238  0.320801  0.974597
1  0.963802  0.876812  0.208270  0.465062
2  0.715445  0.547000  0.171166  0.414529
3  0.425257  0.789973  0.178012  0.640145
4  0.066779  0.498029  0.243267  0.994032

**df1.head()** is used for viewing head of data set by it preview _5 rows_ of all columns but number of rows can be costmize by **df1.head(number of rows)**

In [19]:
df1.tail(2)

          y        x1        x2        x3
8  0.970105  0.306655  0.453312  0.435030
9  0.903288  0.005746  0.321485  0.596094

**df1.tail()** is used for viewing tail of data set by it preview last _5 rows_ of all columns but number of rows can be costmize by **df1.tail(number of rows)**

In [20]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

**df2.dtypes** is used for finding datatypes of all columns.

In [21]:
df1.describe()

               y         x1         x2         x3
count  10.000000  10.000000  10.000000  10.000000
mean    0.561992   0.346633   0.246714   0.640970
std     0.375822   0.325289   0.127054   0.262215
min     0.062183   0.005746   0.008626   0.227026
25%     0.269927   0.035275   0.178440   0.442538
50%     0.570351   0.322446   0.225769   0.618119
75%     0.925969   0.534757   0.321314   0.870612
max     0.970105   0.876812   0.453312   0.994032

**df1.discribe()** discribe function is used to find:

- _count_ to total number of entiies in all columns.

- _mean_ mean of all columns.

- _std_ standard deaviation of all columns.

- _min_ minum values of all columns.

- _25% | 50% | 75%_ first seacond and third quantiles

- _max_ maximum values of all columns.

In [22]:
df1.T

,0,1,2,3,4,5,6,7,8,9
y,0.329451,0.963802,0.715445,0.425257,0.066779,0.933529,0.062183,0.250086,0.970105,0.903288
x1,0.338238,0.876812,0.547000,0.789973,0.498029,0.067380,0.024573,0.011924,0.306655,0.005746
x2,0.320801,0.208270,0.171166,0.178012,0.243267,0.382479,0.179724,0.008626,0.453312,0.321485
x3,0.974597,0.465062,0.414529,0.640145,0.994032,0.227026,0.909630,0.753556,0.435030,0.596094

**df1.T** is used for Transposition of the dataset. For converting rows in to columns and columns in to rows

In [23]:
df1.sort_index(axis=0, ascending=False)

          y        x1        x2        x3
9  0.903288  0.005746  0.321485  0.596094
8  0.970105  0.306655  0.453312  0.435030
7  0.250086  0.011924  0.008626  0.753556
6  0.062183  0.024573  0.179724  0.909630
5  0.933529  0.067380  0.382479  0.227026
4  0.066779  0.498029  0.243267  0.994032
3  0.425257  0.789973  0.178012  0.640145
2  0.715445  0.547000  0.171166  0.414529
1  0.963802  0.876812  0.208270  0.465062
0  0.329451  0.338238  0.320801  0.974597

**df1.sort_index()** is used for sorting indexes under controled parameters:
- *axis=0* is for index
- *axis=1* is for column names 
- *ascending=True* is for sorting in ascending order.
- *ascending=False* is for sorting in descending order.

In [24]:
df1.sort_values(by="y", ascending=False)

          y        x1        x2        x3
8  0.970105  0.306655  0.453312  0.435030
1  0.963802  0.876812  0.208270  0.465062
5  0.933529  0.067380  0.382479  0.227026
9  0.903288  0.005746  0.321485  0.596094
2  0.715445  0.547000  0.171166  0.414529
3  0.425257  0.789973  0.178012  0.640145
0  0.329451  0.338238  0.320801  0.974597
7  0.250086  0.011924  0.008626  0.753556
4  0.066779  0.498029  0.243267  0.994032
6  0.062183  0.024573  0.179724  0.909630

**df1.sort_values()** is used for sorting values in selected column:
- *ascending=True* is for sorting in ascending order.
- *ascending=False* is for sorting in descending order.