# Pandas Functions

In [226]:
import pandas as pd
import numpy as np

First of all we have to import libraries

In [227]:
pd.Series([1, 3, 5, pd.NaT, 6, 8])

0      1
1      3
2      5
3    NaT
4      6
5      8
dtype: object

In [228]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
df = pd.DataFrame({
    'Name': ['Adnan', "usman", "Fakhar", 'Ali', 'Adeel', 'Ajmal'],
    'age': [24, 23, pd.NaT, 25, 26, 24],
}, index=[ 1, 2, 3, 4, 5,6])
print(df)

     Name  age
1   Adnan   24
2   usman   23
3  Fakhar  NaT
4     Ali   25
5   Adeel   26
6   Ajmal   24

In [229]:
df.dropna( axis= 0)

    Name age
1  Adnan  24
2  usman  23
4    Ali  25
5  Adeel  26
6  Ajmal  24

In [230]:
df.fillna(df['age'].mean(), inplace= True)
df

/tmp/ipykernel_10417/4141655554.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(df['age'].mean(), inplace= True)

     Name   age
1   Adnan  24.0
2   usman  23.0
3  Fakhar  24.4
4     Ali  25.0
5   Adeel  26.0
6   Ajmal  24.0

In [231]:
df.dtypes

Name     object
age     float64
dtype: object

**pd.series()** is Singe Dimentional *labeled array*

**pd.DataFrame()** is Two Dimentional *Data Frame* which contains multiple rows and columns

In [232]:
date = pd.date_range(start='20140715', end = '20240915', freq = "Y")
date

/tmp/ipykernel_10417/3555385800.py:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  date = pd.date_range(start='20140715', end = '20240915', freq = "Y")

DatetimeIndex(['2014-12-31', '2015-12-31', '2016-12-31', '2017-12-31',
               '2018-12-31', '2019-12-31', '2020-12-31', '2021-12-31',
               '2022-12-31', '2023-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')

**pd.date_range()** is single dimentional aray of date or time based on defined parameters like:
- start =
- end =
- freq =
- periods =

In [233]:
df1 = pd.DataFrame(np.random.rand(10, 4), columns=['y','x1','x2','x3'])

df1

          y        x1        x2        x3
0  0.659099  0.970486  0.498371  0.901113
1  0.082001  0.450570  0.304455  0.358020
2  0.188035  0.939828  0.649063  0.694966
3  0.803701  0.729772  0.019839  0.466174
4  0.506206  0.288221  0.026700  0.335281
5  0.188787  0.351004  0.073301  0.715155
6  0.435847  0.621501  0.390888  0.271340
7  0.601323  0.360312  0.292023  0.561754
8  0.956804  0.257879  0.965260  0.800513
9  0.716887  0.559258  0.126950  0.980727

**pd.DataFrame()** is Two Dimentional *Data Frame* which contains multiple rows and columns as defined in parameters.

**np.random.rand()** is used to genrate random rows and column entries the size defined 6 rows and 4 columns

**index =** is used to define costume index by defualt index is 0,1,2,3,4,5...

**columns =** is used to define costume columns heading by defualt columns headings are 0,1,2,3,4,5...

In [234]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

## DataFrame Functons

**pd.Timestamp** is used for Date and time.

**pd.Series** is used for list.

**pd.Categorical** is used for catagorica values.

- Simple numeric values (_1_) int64
- Desimal values (_1.0_) are stored in float64
- String (_'abc'_) is stored in object

## Viewing data

In [235]:
df1.head()

          y        x1        x2        x3
0  0.659099  0.970486  0.498371  0.901113
1  0.082001  0.450570  0.304455  0.358020
2  0.188035  0.939828  0.649063  0.694966
3  0.803701  0.729772  0.019839  0.466174
4  0.506206  0.288221  0.026700  0.335281

**df1.head()** is used for viewing head of data set by it preview _5 rows_ of all columns but number of rows can be costmize by **df1.head(number of rows)**

In [236]:
df1.tail(2)

          y        x1       x2        x3
8  0.956804  0.257879  0.96526  0.800513
9  0.716887  0.559258  0.12695  0.980727

**df1.tail()** is used for viewing tail of data set by it preview last _5 rows_ of all columns but number of rows can be costmize by **df1.tail(number of rows)**

In [237]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

**df2.dtypes** is used for finding datatypes of all columns.

In [238]:
df1.describe()

               y         x1         x2         x3
count  10.000000  10.000000  10.000000  10.000000
mean    0.513869   0.552883   0.334685   0.608504
std     0.289569   0.259387   0.304522   0.247970
min     0.082001   0.257879   0.019839   0.271340
25%     0.250552   0.353331   0.086713   0.385058
50%     0.553765   0.504914   0.298239   0.628360
75%     0.702440   0.702704   0.471500   0.779173
max     0.956804   0.970486   0.965260   0.980727

**df1.discribe()** discribe function is used to find:

- _count_ to total number of entiies in all columns.

- _mean_ mean of all columns.

- _std_ standard deaviation of all columns.

- _min_ minum values of all columns.

- _25% | 50% | 75%_ first seacond and third quantiles

- _max_ maximum values of all columns.

In [239]:
df1.T

,0,1,2,3,4,5,6,7,8,9
y,0.659099,0.082001,0.188035,0.803701,0.506206,0.188787,0.435847,0.601323,0.956804,0.716887
x1,0.970486,0.450570,0.939828,0.729772,0.288221,0.351004,0.621501,0.360312,0.257879,0.559258
x2,0.498371,0.304455,0.649063,0.019839,0.026700,0.073301,0.390888,0.292023,0.965260,0.126950
x3,0.901113,0.358020,0.694966,0.466174,0.335281,0.715155,0.271340,0.561754,0.800513,0.980727

**df1.T** is used for Transposition of the dataset. For converting rows in to columns and columns in to rows

In [240]:
df1.sort_index(axis=0, ascending=False)

          y        x1        x2        x3
9  0.716887  0.559258  0.126950  0.980727
8  0.956804  0.257879  0.965260  0.800513
7  0.601323  0.360312  0.292023  0.561754
6  0.435847  0.621501  0.390888  0.271340
5  0.188787  0.351004  0.073301  0.715155
4  0.506206  0.288221  0.026700  0.335281
3  0.803701  0.729772  0.019839  0.466174
2  0.188035  0.939828  0.649063  0.694966
1  0.082001  0.450570  0.304455  0.358020
0  0.659099  0.970486  0.498371  0.901113

**df1.sort_index()** is used for sorting indexes under controled parameters:
- *axis=0* is for index
- *axis=1* is for column names 
- *ascending=True* is for sorting in ascending order.
- *ascending=False* is for sorting in descending order.

In [241]:
df1.sort_values(by="y", ascending=False)

          y        x1        x2        x3
8  0.956804  0.257879  0.965260  0.800513
3  0.803701  0.729772  0.019839  0.466174
9  0.716887  0.559258  0.126950  0.980727
0  0.659099  0.970486  0.498371  0.901113
7  0.601323  0.360312  0.292023  0.561754
4  0.506206  0.288221  0.026700  0.335281
6  0.435847  0.621501  0.390888  0.271340
5  0.188787  0.351004  0.073301  0.715155
2  0.188035  0.939828  0.649063  0.694966
1  0.082001  0.450570  0.304455  0.358020

**df1.sort_values()** is used for sorting values in selected column:
- *ascending=True* is for sorting in ascending order.
- *ascending=False* is for sorting in descending order.

### Read PSL CSV

In [242]:
psl=pd.read_csv('PSL.csv')
psl.head()

,Player,Runs,Balls,4s,6s,Strike_Rate,Team,Opposition,Ground,Match Date
0,CA Ingram,127*,59,NaN,8.0,215.25,Kings,v Gladiators,Sharjah,24-Feb-19
1,CS Delport,117*,60,13.0,6.0,195.00,United,v Qalandars,Karachi,9-Mar-19
2,Sharjeel Khan,NaN,6,12.0,8.0,188.70,United,v Zalmi,Dubai (DSC),21-Feb-16
3,CA Lynn,113*,55,12.0,8.0,205.45,Qalandars,v Sultans,Lahore,15-Mar-20
4,Kamran Akmal,107*,61,11.0,NaN,175.40,Zalmi,v Qalandars,Sharjah,16-Mar-18

**Checking info of null values**

In [243]:
psl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player       50 non-null     object
 1   Runs         49 non-null     object
 2   Balls        50 non-null     int64
 3   4s           44 non-null     float64
 4   6s           46 non-null     float64
 5   Strike_Rate  48 non-null     float64
 6   Team         50 non-null     object
 7   Opposition   50 non-null     object
 8   Ground       50 non-null     object
 9   Match Date   50 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 4.0+ KB

In [244]:

psl['4s'].fillna(psl['4s'].mean())
psl['6s'].fillna(psl['6s'].mean())
psl.fillna({'6s': psl['6s'].mean(),'4s':psl['4s'].mean(),'Strike_Rate':psl['Strike_Rate'].mean()},inplace=True)
psl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player       50 non-null     object
 1   Runs         49 non-null     object
 2   Balls        50 non-null     int64
 3   4s           50 non-null     float64
 4   6s           50 non-null     float64
 5   Strike_Rate  50 non-null     float64
 6   Team         50 non-null     object
 7   Opposition   50 non-null     object
 8   Ground       50 non-null     object
 9   Match Date   50 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 4.0+ KB

In [251]:
# psl['Player'].value_counts()
psl=psl.groupby(by='Player',axis=0,sort=True).sum()
psl1=pd.DataFrame(psl)
# psl1
psl1['Player'].value_count()

/tmp/ipykernel_10417/1890534332.py:2: FutureWarning: The 'axis' keyword in DataFrame.groupby is deprecated and will be removed in a future version.
  psl=psl.groupby(by='Player',axis=0,sort=True).sum()

KeyError: 'Player'

In [223]:
psl

,Runs,Balls,4s,6s,Strike_Rate,Team,Opposition,Ground,Match Date
Player,,,,,,,,,
AD Hales,80*,48,6.000000,5.000000,166.660000,Kings,v Qalandars,Lahore,8-Mar-20
Ahmed Shehzad,99,57,7.113636,6.000000,173.680000,Gladiators,v Kings,Karachi,10-Mar-19
BJ Hodge,85*,45,6.000000,6.000000,188.880000,Zalmi,v Kings,Dubai (DSC),17-Feb-16
BR Dunk,99*93,83,6.000000,22.000000,463.770000,QalandarsQalandars,v Kingsv Gladiators,LahoreLahore,8-Mar-203-Mar-20
Babar Azam,7877,115,13.000000,3.000000,269.780000,KingsKings,v Zalmiv Sultans,KarachiDubai (DSC),21-Feb-2015-Feb-19
C Munro,87*,59,8.000000,3.000000,147.450000,United,v Qalandars,Lahore,4-Mar-20
CA Ingram,127*,59,7.113636,8.000000,215.250000,Kings,v Gladiators,Sharjah,24-Feb-19
CA Lynn,113*,55,12.000000,8.000000,205.450000,Qalandars,v Sultans,Lahore,15-Mar-20
CS Delport,117*78,121,19.000000,9.000000,322.860000,UnitedQalandars,v Qalandarsv Zalmi,KarachiSharjah,9-Mar-1913-Feb-16
EJG Morgan,80*,57,8.000000,3.000000,140.350000,Zalmi,v Kings,Dubai (DSC),10-Feb-17
Fakhar Zaman,94,50,9.000000,6.000000,188.000000,Qalandars,v Gladiators,Sharjah,14-Mar-18
JL Denly,79*78,101,17.113636,9.478261,313.540000,KingsKings,v Zalmiv Sultans,LahoreDubai (DSC),21-Mar-1810-Mar-18
JM Vince,84,41,7.000000,6.000000,204.870000,Sultans,v Qalandars,Sharjah,22-Feb-19
KP Pietersen,88*,42,3.000000,8.000000,209.520000,Gladiators,v Qalandars,Sharjah,18-Feb-17
Kamran Akmal,107*10410188867775,355,55.113636,41.478261,1313.750000,ZalmiZalmiZalmiZalmiZalmiZalmiZalmi,v Qalandarsv Kingsv Gladiatorsv Unitedv Kingsv...,SharjahDubai (DSC)KarachiDubai (DSC)KarachiLah...,16-Mar-183-Mar-1722-Feb-209-Feb-1711-Mar-1921-...
L Ronchi,94*85*77,138,26.000000,13.478261,575.370000,UnitedUnitedUnited,v Kingsv Kingsv Qalandars,Dubai (DSC)RawalpindiDubai (DSC),18-Mar-181-Mar-208-Mar-18
LJ Wright,86*,53,11.000000,4.000000,179.236042,Gladiators,v United,Dubai (DSC),4-Feb-16
LS Livingstone,82,43,6.000000,6.000000,190.690000,Kings,v Sultans,Dubai (DSC),15-Feb-19
Mohammad Hafeez,98*7774*,150,21.000000,15.000000,496.600000,QalandarsZalmiQalandars,v Unitedv Gladiatorsv Zalmi,LahoreSharjahKarachi,23-Feb-2028-Feb-1714-Nov-20
RR Rossouw,100*76*,97,14.113636,9.000000,370.660000,SultansGladiators,v Gladiatorsv Kings,MultanDubai (DSC),29-Feb-2011-Feb-17
SR Watson,91*90*81*8079,256,28.000000,31.000000,844.876042,GladiatorsGladiatorsGladiatorsGladiatorsUnited,v Zalmiv Kingsv Unitedv Sultansv Qalandars,Abu DhabiDubai (DSC)Dubai (DSC)MultanSharjah,4-Mar-198-Mar-1817-Feb-1929-Feb-2010-Feb-16
SW Billings,78*,50,8.000000,3.000000,156.000000,United,v Gladiators,Sharjah,15-Feb-17
Shadab Khan,77,42,5.000000,4.000000,183.330000,United,v Zalmi,Rawalpindi,7-Mar-20
Sharjeel Khan,79*74*,108,22.000000,18.478261,497.840000,UnitedUnitedKings,v Zalmiv Qalandarsv Qalandars,Dubai (DSC)SharjahKarachi,21-Feb-1610-Feb-1612-Mar-20
Sohaib Maqsood,85*,42,4.000000,7.000000,202.380000,Sultans,v Zalmi,Dubai (DSC),6-Mar-18
Sohail Akhtar,75,34,8.000000,5.000000,220.580000,Qalandars,v United,Karachi,9-Mar-19
Tamim Iqbal,80*,58,6.000000,3.000000,137.930000,Zalmi,v United,Sharjah,12-Feb-16
Umar Akmal,9375*,90,13.113636,11.000000,382.500000,QalandarsGladiators,v Gladiatorsv Zalmi,Dubai (DSC)Dubai (DSC),8-Feb-1615-Feb-19